import {values} from "../../../db/sales-hierarchy";
import { getRawDb } from "../../../db";
import { requireUser } from "../../../db/auth";

const columns="id,salesman_code AS code,name,phone,email,active,notes,created_at AS createdAt,supervisor_id AS supervisorId";
export async function GET(request:Request){const auth=await requireUser(request);if(auth instanceof Response)return auth;try{return Response.json({salesmen:(await getRawDb().prepare(`SELECT ${columns} FROM salesmen WHERE company_code=? ORDER BY active DESC,name COLLATE NOCASE`).bind(auth.companyCode.toLowerCase()).all()).results})}catch(error){console.error(error);return Response.json({error:"Could not load salesmen."},{status:500})}}
export async function POST(request:Request){const auth=await requireUser(request);if(auth instanceof Response)return auth;try{const body=await request.json() as Record<string,unknown>,value=values(body),supervisorId=await parent(body,auth.companyCode.toLowerCase()),salesman=await getRawDb().prepare(`INSERT INTO salesmen(company_code,salesman_code,name,phone,email,active,notes,supervisor_id) VALUES(?,?,?,?,?,?,?,?) RETURNING ${columns}`).bind(auth.companyCode.toLowerCase(),value.code,value.name,value.phone,value.email,value.active?1:0,value.notes,supervisorId).first();return Response.json({salesman},{status:201})}catch(error){const message=error instanceof Error?error.message:"Could not create salesman.";return Response.json({error:/UNIQUE/i.test(message)?"This salesman code already exists.":message},{status:/UNIQUE/i.test(message)?409:400})}}
export async function PUT(request:Request){const auth=await requireUser(request);if(auth instanceof Response)return auth;try{const body=await request.json() as Record<string,unknown>,id=Number(body.id),value=values(body);if(!Number.isSafeInteger(id)||id<1)return Response.json({error:"Invalid salesman."},{status:400});const current=await getRawDb().prepare("SELECT supervisor_id AS supervisorId FROM salesmen WHERE id=? AND company_code=?").bind(id,auth.companyCode.toLowerCase()).first<{supervisorId:number|null}>();if(!current)return Response.json({error:"Salesman not found."},{status:404});const supervisorId=body.supervisorId===undefined?current.supervisorId:await parent(body,auth.companyCode.toLowerCase(),current.supervisorId);const salesman=await getRawDb().prepare(`UPDATE salesmen SET salesman_code=?,name=?,phone=?,email=?,active=?,notes=?,supervisor_id=? WHERE id=? AND company_code=? RETURNING ${columns}`).bind(value.code,value.name,value.phone,value.email,value.active?1:0,value.notes,supervisorId,id,auth.companyCode.toLowerCase()).first();if(!salesman)return Response.json({error:"Salesman not found."},{status:404});return Response.json({salesman})}catch(error){const message=error instanceof Error?error.message:"Could not update salesman.";return Response.json({error:/UNIQUE/i.test(message)?"This salesman code already exists.":message},{status:/UNIQUE/i.test(message)?409:400})}}

async function parent(body:Record<string,unknown>,company:string,current?:number|null){
 const id=body.supervisorId==null||body.supervisorId===""?null:Number(body.supervisorId);
 if(id===null){if(current===null)return null;throw new Error("Select a supervisor.");}
 if(!Number.isSafeInteger(id)||id<1)throw new Error("Select a valid supervisor.");
 const row=await getRawDb().prepare("SELECT s.id FROM sales_supervisors s JOIN area_managers a ON a.id=s.area_manager_id AND a.company_code=s.company_code WHERE s.id=? AND s.company_code=? AND ((s.active=1 AND a.active=1) OR s.id=?)").bind(id,company,current??0).first();
 if(!row)throw new Error("Select an active supervisor from this company.");return id;
}
