import {getRawDb} from '../../../db';
import {requireUser} from '../../../db/auth';
import {ensureStockLedger} from '../../../db/stock';
import {ensureWarehouses} from '../../../db/warehouses';
export async function GET(request:Request){const auth=await requireUser(request);if(auth instanceof Response)return auth;try{const company=auth.companyCode.toLowerCase(),db=getRawDb();await ensureStockLedger(company,db);await ensureWarehouses(company,db);const itemId=Number(new URL(request.url).searchParams.get('itemId')||0);if(!Number.isSafeInteger(itemId)||itemId<0)throw new Error('Invalid item.');const result=await db.prepare(`SELECT w.id,w.code,w.name,w.address,w.active,COALESCE((SELECT SUM(t.quantity) FROM stock_transactions t WHERE t.company_code=w.company_code AND t.warehouse_code=w.code AND t.item_id=?),0) AS quantity FROM warehouses w WHERE w.company_code=? ORDER BY CASE WHEN w.code='MAIN' THEN 0 ELSE 1 END,w.name`).bind(itemId,company).all();return Response.json({warehouses:result.results})}catch(e){return Response.json({error:(e as Error).message},{status:400})}}
async function save(request:Request){const auth=await requireUser(request);if(auth instanceof Response)return auth;try{const db=getRawDb(),company=auth.companyCode.toLowerCase(),b=await request.json() as Record<string,unknown>,code=String(b.code??'').trim().toUpperCase(),name=String(b.name??'').trim(),address=String(b.address??'').trim(),active=b.active===false||b.active===0?0:1;
 if(!/^[A-Z0-9_-]{1,20}$/.test(code)||!name||name.length>100||address.length>1000)throw new Error('Enter a code (up to 20 letters/numbers), name and valid address.');await ensureStockLedger(company,db);await ensureWarehouses(company,db);
 if(request.method==='POST'){await db.prepare('INSERT INTO warehouses(company_code,code,name,address,active) VALUES(?,?,?,?,?)').bind(company,code,name,address,active).run();return Response.json({ok:true},{status:201})}
 const existing=await db.prepare('SELECT code FROM warehouses WHERE id=? AND company_code=?').bind(Number(b.id),company).first<{code:string}>();if(!existing)throw new Error('Warehouse not found.');if(existing.code!==code)throw new Error('Warehouse codes cannot change.');if(code==='MAIN'&&!active)throw new Error('Main Warehouse must remain active.');
 const token=crypto.randomUUID();await db.batch([
 db.prepare(`INSERT INTO item_master_guards(token,valid) VALUES(?,CASE WHEN ?=1 OR NOT EXISTS(SELECT item_id FROM stock_transactions WHERE company_code=? AND warehouse_code=? GROUP BY item_id HAVING ABS(SUM(quantity))>0.000000001) THEN 1 ELSE NULL END)`).bind(token,active,company,code),
 db.prepare('UPDATE warehouses SET name=?,address=?,active=? WHERE id=? AND company_code=?').bind(name,address,active,b.id,company),db.prepare('DELETE FROM item_master_guards WHERE token=?').bind(token)]);return Response.json({ok:true});
 }catch(e){const m=(e as Error).message;return Response.json({error:/UNIQUE/.test(m)?'This warehouse code already exists.':/NOT NULL/.test(m)?'Move or adjust all stock before deactivating this warehouse.':m},{status:400})}}
export const POST=save;export const PUT=save;
