import {getRawDb} from '../../../db';
import {requireUser} from '../../../db/auth';
export async function GET(request:Request){const auth=await requireUser(request);if(auth instanceof Response)return auth;try{const db=getRawDb(),company=auth.companyCode.toLowerCase();
 // Preserve legacy brands and materialize only small, company-scoped master values.
 await db.prepare("INSERT OR IGNORE INTO item_master_values(company_code,category,name,parent) SELECT DISTINCT company_code,'brand',brand,'' FROM items WHERE company_code=? AND trim(brand)<>''").bind(company).run();
 return Response.json({values:(await db.prepare('SELECT id,category,name,parent,active FROM item_master_values WHERE company_code=? ORDER BY category,parent,name').bind(company).all()).results});
 }catch{return Response.json({error:'Could not load item lists.'},{status:500})}}
export async function POST(request:Request){const auth=await requireUser(request);if(auth instanceof Response)return auth;try{const b=await request.json() as Record<string,unknown>,db=getRawDb(),company=auth.companyCode.toLowerCase(),category=String(b.category),name=String(b.name??'').trim(),parent=category==='subgroup'?String(b.parent??'').trim():'';if(!['group','subgroup','brand'].includes(category)||!name||name.length>100)throw new Error('Enter a name and valid list.');if(category==='subgroup'&&!await db.prepare("SELECT id FROM item_master_values WHERE company_code=? AND category='group' AND name=? AND active=1").bind(company,parent).first())throw new Error('Choose an active parent group.');await db.prepare('INSERT INTO item_master_values(company_code,category,name,parent) VALUES(?,?,?,?)').bind(company,category,name,parent).run();return Response.json({ok:true});}catch(e){return Response.json({error:/UNIQUE/.test(String(e))?'This list value already exists.':(e as Error).message},{status:400})}}
export async function PUT(request:Request){const auth=await requireUser(request);if(auth instanceof Response)return auth;try{const b=await request.json() as Record<string,unknown>;await getRawDb().prepare('UPDATE item_master_values SET active=? WHERE id=? AND company_code=?').bind(b.active?1:0,Number(b.id),auth.companyCode.toLowerCase()).run();return Response.json({ok:true});}catch{return Response.json({error:'Could not update list value.'},{status:400})}}
