import { getRawDb } from "../../../db";
import { requireUser } from "../../../db/auth";
import { getWorkshopSettings } from "../../../db/settings";
import {journalVoucherNumber} from '../../../db/journal-voucher-types';
import {accountAssertion} from '../../../db/coa-write';
import {getCurrencies} from "../../../db/currencies";

type JournalLine={accountNumber:string;description:string;currency:string;debit:number;credit:number;localAmount:number};
function readLines(value:unknown){
 if(!Array.isArray(value))throw new Error("Add at least two journal lines.");
 const lines=value.map(item=>{const row=item as Record<string,unknown>,accountNumber=String(row.accountNumber??"").trim(),description=String(row.description??"").trim(),currency=String(row.currency??"").trim().toUpperCase(),debit=Number(row.debit??0),credit=Number(row.credit??0),localAmount=Number(row.localAmount??0);if(!accountNumber||accountNumber.length>100)throw new Error("Select an account for every line.");if(!/^[A-Z]{3}$/.test(currency))throw new Error("Every line must use a three-letter currency code, such as USD.");if(description.length>500)throw new Error("Line descriptions must be 500 characters or fewer.");if(!Number.isFinite(debit)||!Number.isFinite(credit)||debit<0||credit<0||(!debit&&!credit)||(debit>0&&credit>0))throw new Error("Each line must contain one positive debit or credit amount.");if(!Number.isFinite(localAmount)||localAmount<=0)throw new Error("Every line must contain a positive countervalue in local currency.");return{accountNumber,description,currency,debit,credit,localAmount} satisfies JournalLine});
 if(lines.length<2||lines.length>100)throw new Error("A journal voucher must contain between 2 and 100 lines.");
 const debitLocal=lines.reduce((sum,line)=>sum+(line.debit?line.localAmount:0),0),creditLocal=lines.reduce((sum,line)=>sum+(line.credit?line.localAmount:0),0);if(Math.abs(debitLocal-creditLocal)>=0.005)throw new Error("Journal voucher debits and credits must balance in local currency.");return lines;
}
async function validateLineCurrencies(company:string,lines:JournalLine[]){
 const active=new Set((await getCurrencies(company)).filter(currency=>currency.active).map(currency=>currency.code));
 if(lines.some(line=>!active.has(line.currency)))throw new Error("Every journal line must use an active currency from Company Configuration.");
}
export async function GET(request:Request){
 const auth=await requireUser(request);if(auth instanceof Response)return auth;
 const params=new URL(request.url).searchParams,page=Number(params.get("page")||1),query=(params.get("q")||"").trim(),type=params.get("type"),sourceId=Number(params.get("sourceId"));
 if(!Number.isSafeInteger(page)||page<1||page>100000)return Response.json({error:"Invalid page."},{status:400});
 try{const db=getRawDb(),company=auth.companyCode.toLowerCase();
  if(type&&Number.isSafeInteger(sourceId)&&sourceId>0){const[lines,voucher,settings]=await Promise.all([
   db.prepare(`SELECT tx.id,tx.account_number AS accountNumber,COALESCE(account.name,'') AS accountName,tx.currency,tx.amount_currency AS amountCurrency,tx.amount_local_currency AS amountLocalCurrency,tx.indicator,tx.notes FROM accounting_transactions tx LEFT JOIN accounts account ON account.company_code=tx.company_code AND account.account_number=tx.account_number WHERE tx.company_code=? AND tx.transaction_type=? AND tx.source_id=? ORDER BY tx.id`).bind(company,type,sourceId).all(),
   db.prepare(`SELECT MAX(tx.id) AS id,tx.transaction_type AS transactionType,tx.source_id AS sourceId,tx.transaction_date AS transactionDate,tx.reference,CASE WHEN COUNT(DISTINCT tx.currency)=1 THEN MIN(tx.currency) ELSE 'Multiple' END AS currency,SUM(CASE WHEN tx.indicator='debit' THEN tx.amount_local_currency ELSE 0 END) AS debitLocal,SUM(CASE WHEN tx.indicator='credit' THEN tx.amount_local_currency ELSE 0 END) AS creditLocal,COALESCE(MAX(jv.external_reference),'') AS externalReference,COALESCE(MAX(jv.notes),'') AS voucherNotes,MAX(jv.voucher_type_id) AS voucherTypeId,COALESCE(MAX(jvt.description),'') AS voucherTypeDescription FROM accounting_transactions tx LEFT JOIN journal_vouchers jv ON tx.transaction_type='journal' AND jv.id=tx.source_id AND jv.company_code=tx.company_code LEFT JOIN journal_voucher_types jvt ON jvt.id=jv.voucher_type_id AND jvt.company_code=jv.company_code WHERE tx.company_code=? AND tx.transaction_type=? AND tx.source_id=? GROUP BY tx.transaction_type,tx.source_id,tx.transaction_date,tx.reference`).bind(company,type,sourceId).first(),
   getWorkshopSettings(company,db),
  ]);if(!voucher)return Response.json({error:"Journal voucher not found."},{status:404});return Response.json({lines:lines.results,voucher,settings})}
  const result=await db.prepare(`SELECT MAX(tx.id) AS id,tx.transaction_type AS transactionType,tx.source_id AS sourceId,tx.transaction_date AS transactionDate,tx.reference,CASE WHEN COUNT(DISTINCT tx.currency)=1 THEN MIN(tx.currency) ELSE 'Multiple' END AS currency,COUNT(*) AS lineCount,SUM(CASE WHEN tx.indicator='debit' THEN tx.amount_currency ELSE 0 END) AS debit,SUM(CASE WHEN tx.indicator='credit' THEN tx.amount_currency ELSE 0 END) AS credit,SUM(CASE WHEN tx.indicator='debit' THEN tx.amount_local_currency ELSE 0 END) AS debitLocal,SUM(CASE WHEN tx.indicator='credit' THEN tx.amount_local_currency ELSE 0 END) AS creditLocal,COALESCE(MAX(jv.external_reference),'') AS externalReference,COALESCE(MAX(jv.notes),'') AS voucherNotes,MAX(jv.voucher_type_id) AS voucherTypeId,COALESCE(MAX(jvt.description),'') AS voucherTypeDescription FROM accounting_transactions tx LEFT JOIN journal_vouchers jv ON tx.transaction_type='journal' AND jv.id=tx.source_id AND jv.company_code=tx.company_code LEFT JOIN journal_voucher_types jvt ON jvt.id=jv.voucher_type_id AND jvt.company_code=jv.company_code WHERE tx.company_code=? AND (?='' OR instr(lower(tx.reference||' '||tx.transaction_type||' '||COALESCE(jv.external_reference,'')),lower(?))>0) GROUP BY tx.transaction_type,tx.source_id,tx.transaction_date,tx.reference ORDER BY tx.transaction_date DESC,id DESC LIMIT 51 OFFSET ?`).bind(company,query,query,(page-1)*50).all();return Response.json({vouchers:result.results.slice(0,50),hasMore:result.results.length>50});
 }catch(error){console.error(error);return Response.json({error:"Could not load journal vouchers."},{status:500})}
}
export async function POST(request:Request){
 const auth=await requireUser(request);if(auth instanceof Response)return auth;
 try{const body=await request.json() as Record<string,unknown>,company=auth.companyCode.toLowerCase(),voucherDate=String(body.voucherDate??"").trim(),externalReference=String(body.externalReference??"").trim(),notes=String(body.notes??"").trim(),lines=readLines(body.lines);if(!/^\d{4}-\d{2}-\d{2}$/.test(voucherDate))throw new Error("Enter a valid voucher date.");if(externalReference.length>200||notes.length>2000)throw new Error("The reference or notes are too long.");
  const db=getRawDb();await validateLineCurrencies(company,lines);const accountNumbers=[...new Set(lines.map(line=>line.accountNumber))],placeholders=accountNumbers.map(()=>"?").join(","),accounts=await db.prepare(`SELECT account_number AS accountNumber FROM accounts WHERE company_code=? AND active=1 AND length(account_number)=10 AND account_number NOT GLOB '*[^0-9]*' AND account_number IN (${placeholders})`).bind(company,...accountNumbers).all<{accountNumber:string}>();if(accounts.results.length!==accountNumbers.length)throw new Error("Every journal line must use an active account from the Chart of Accounts.");
  const allocated=await journalVoucherNumber(db,company,Number(body.voucherTypeId)),voucherNumber=allocated.number,settings=await getWorkshopSettings(company,db);
  const guard=accountAssertion(db,'EXISTS(SELECT 1 FROM journal_voucher_types WHERE id=? AND company_code=? AND prefix=? AND active=1)',[allocated.type.id,company,allocated.type.prefix]);
  const statements=[guard.check,db.prepare("INSERT INTO journal_vouchers(company_code,voucher_number,voucher_date,currency,external_reference,notes,voucher_type_id) VALUES(?,?,?,?,?,?,?)").bind(company,voucherNumber,voucherDate,settings.localCurrency,externalReference,notes,allocated.type.id),...lines.map(line=>{const amount=line.debit||line.credit,indicator=line.debit?"debit":"credit";return db.prepare("INSERT INTO accounting_transactions(company_code,transaction_type,source_id,transaction_date,account_number,currency,reference,amount_currency,amount_local_currency,indicator,notes) VALUES(?,'journal',(SELECT id FROM journal_vouchers WHERE company_code=? AND voucher_number=?),?,?,?,?,?,?,?,?)").bind(company,company,voucherNumber,voucherDate,line.accountNumber,line.currency,voucherNumber,amount,line.localAmount,indicator,line.description)}),guard.clear],results=await db.batch(statements);if(results.some(result=>!result.success))throw new Error("Could not post journal voucher.");return Response.json({voucherNumber},{status:201});
 }catch(error){const message=error instanceof Error?error.message:"Could not create journal voucher.",serverError=/Could not|UNIQUE/i.test(message);if(serverError)console.error(error);return Response.json({error:/UNIQUE/i.test(message)?"Please try again to generate the next JV number.":message},{status:serverError?500:400})}
}
export async function PUT(request:Request){
 const auth=await requireUser(request);if(auth instanceof Response)return auth;
 try{const body=await request.json() as Record<string,unknown>,company=auth.companyCode.toLowerCase(),sourceId=Number(body.sourceId),voucherDate=String(body.voucherDate??"").trim(),externalReference=String(body.externalReference??"").trim(),notes=String(body.notes??"").trim(),lines=readLines(body.lines);if(!Number.isSafeInteger(sourceId)||sourceId<1)throw new Error("Invalid journal voucher.");if(!/^\d{4}-\d{2}-\d{2}$/.test(voucherDate))throw new Error("Enter a valid voucher date.");if(externalReference.length>200||notes.length>2000)throw new Error("The reference or notes are too long.");
  const db=getRawDb();await validateLineCurrencies(company,lines);const existing=await db.prepare("SELECT voucher_number AS voucherNumber,voucher_type_id AS voucherTypeId FROM journal_vouchers WHERE id=? AND company_code=?").bind(sourceId,company).first<{voucherNumber:string;voucherTypeId:number|null}>();if(!existing)return Response.json({error:"Manual journal voucher not found."},{status:404});if(body.voucherTypeId!==undefined&&Number(body.voucherTypeId)!==Number(existing.voucherTypeId))throw new Error("The type of a posted voucher cannot change.");
  const accountNumbers=[...new Set(lines.map(line=>line.accountNumber))],placeholders=accountNumbers.map(()=>"?").join(","),accounts=await db.prepare(`SELECT account_number AS accountNumber FROM accounts WHERE company_code=? AND active=1 AND length(account_number)=10 AND account_number NOT GLOB '*[^0-9]*' AND account_number IN (${placeholders})`).bind(company,...accountNumbers).all<{accountNumber:string}>();if(accounts.results.length!==accountNumbers.length)throw new Error("Every journal line must use an active account from the Chart of Accounts.");
  const settings=await getWorkshopSettings(company,db),statements=[db.prepare("UPDATE journal_vouchers SET voucher_date=?,currency=?,external_reference=?,notes=? WHERE id=? AND company_code=?").bind(voucherDate,settings.localCurrency,externalReference,notes,sourceId,company),db.prepare("DELETE FROM accounting_transactions WHERE company_code=? AND transaction_type='journal' AND source_id=?").bind(company,sourceId),...lines.map(line=>{const amount=line.debit||line.credit,indicator=line.debit?"debit":"credit";return db.prepare("INSERT INTO accounting_transactions(company_code,transaction_type,source_id,transaction_date,account_number,currency,reference,amount_currency,amount_local_currency,indicator,notes) VALUES(?,'journal',?,?,?,?,?,?,?,?,?)").bind(company,sourceId,voucherDate,line.accountNumber,line.currency,existing.voucherNumber,amount,line.localAmount,indicator,line.description)})],results=await db.batch(statements);if(results.some(result=>!result.success))throw new Error("Could not update journal voucher.");return Response.json({voucherNumber:existing.voucherNumber});
 }catch(error){const message=error instanceof Error?error.message:"Could not update journal voucher.",serverError=/Could not|UNIQUE/i.test(message);if(serverError)console.error(error);return Response.json({error:message},{status:serverError?500:400})}
}
