"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Combobox, ComboboxContent, ComboboxEmpty, ComboboxInput, ComboboxItem, ComboboxList } from "@/components/ui/combobox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Account={id:number;accountNumber:string;name:string;accountType:string;currency:string;active:boolean};
type Transaction={id:number;transactionDate:string;transactionType:string;reference:string;currency:string;amountCurrency:number;amountLocalCurrency:number;indicator:"debit"|"credit";notes:string};
type Statement={account:Account;currency:string;openingBalance:number;transactions:Transaction[]};
const today=()=>{const date=new Date(),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,10)};
const firstDay=()=>today().slice(0,8)+"01";
const amount=(value:number)=>new Intl.NumberFormat("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Math.abs(value));
const csvCell=(value:unknown)=>`"${String(value).replaceAll('"','""')}"`;
const source=(value:string)=>value==="sale"?"Sale":value==="purchase"?"Purchase":value==="journal"?"JV":value;

export default function AccountStatement(){
 const[accounts,setAccounts]=useState<Account[]>([]),[selected,setSelected]=useState<Account|null>(null),[from,setFrom]=useState(firstDay),[to,setTo]=useState(today),[statement,setStatement]=useState<Statement|null>(null),[loadingAccounts,setLoadingAccounts]=useState(true),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();fetch("/api/accounts",{signal:controller.signal}).then(async response=>{const data=await response.json() as{accounts?:Account[];error?:string};if(!response.ok)throw new Error(data.error);setAccounts(data.accounts??[])}).catch(value=>{if(value.name!=="AbortError")setError(value instanceof Error?value.message:"Could not load accounts.")}).finally(()=>{if(!controller.signal.aborted)setLoadingAccounts(false)});return()=>controller.abort()},[]);
 async function generate(){if(!selected)return;setLoading(true);setError("");try{const response=await fetch(`/api/account-statement?${new URLSearchParams({accountNumber:selected.accountNumber,from,to})}`),data=await response.json() as Statement&{error?:string};if(!response.ok)throw new Error(data.error);setStatement(data)}catch(value){setStatement(null);setError(value instanceof Error?value.message:"Could not prepare the account statement.")}finally{setLoading(false)}}
 const rows=useMemo(()=>{let balance=Number(statement?.openingBalance??0);return(statement?.transactions??[]).map(transaction=>{balance+=transaction.indicator==="debit"?Number(transaction.amountLocalCurrency):-Number(transaction.amountLocalCurrency);return{...transaction,balance}})},[statement]);
 const totals=useMemo(()=>rows.reduce((sum,row)=>({debit:sum.debit+(row.indicator==="debit"?Number(row.amountLocalCurrency):0),credit:sum.credit+(row.indicator==="credit"?Number(row.amountLocalCurrency):0)}),{debit:0,credit:0}),[rows]);
 const closing=Number(statement?.openingBalance??0)+totals.debit-totals.credit;
 function exportCsv(){if(!statement)return;const header=["Date","Reference","Source","Description","Currency","Debit currency","Credit currency","Debit local","Credit local","Running balance local"],body=rows.map(row=>[row.transactionDate,row.reference,source(row.transactionType),row.notes,row.currency,row.indicator==="debit"?row.amountCurrency:"",row.indicator==="credit"?row.amountCurrency:"",row.indicator==="debit"?row.amountLocalCurrency:"",row.indicator==="credit"?row.amountLocalCurrency:"",row.balance]),csv=[header,...body].map(line=>line.map(csvCell).join(",")).join("\r\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`account-statement-${statement.account.accountNumber}-${from}-to-${to}.csv`;link.click();URL.revokeObjectURL(url)}
 return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">
  <div className="flex flex-wrap items-end justify-between gap-4 border-b p-5"><div><h2 className="text-lg font-bold">Statement of account</h2><p className="text-sm text-slate-500">Detailed movements and running balance in local currency.</p></div><div className="flex flex-wrap items-end gap-3"><div className="w-72"><Label>Account</Label><Combobox items={accounts} value={selected} onValueChange={account=>{setSelected(account);setStatement(null)}} itemToStringLabel={account=>`${account.accountNumber} · ${account.name}`} isItemEqualToValue={(item,value)=>item.id===value.id}><ComboboxInput className="mt-1 w-full" aria-label="Search account" placeholder={loadingAccounts?"Loading accounts…":"Search number or name"} disabled={loadingAccounts}/><ComboboxContent><ComboboxEmpty>No matching account.</ComboboxEmpty><ComboboxList>{account=><ComboboxItem key={account.id} value={account}><span className="font-mono text-xs font-semibold text-slate-500">{account.accountNumber}</span><span>{account.name}</span>{!account.active&&<small className="text-slate-400">Inactive</small>}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div><Field label="From"><Input type="date" value={from} onChange={event=>{setFrom(event.target.value);setStatement(null)}}/></Field><Field label="To"><Input type="date" value={to} onChange={event=>{setTo(event.target.value);setStatement(null)}}/></Field><Button onClick={()=>void generate()} disabled={loading||!selected||!from||!to||from>to}><RefreshCw className={loading?"animate-spin":""}/>Generate</Button><Button variant="outline" disabled={!statement} onClick={exportCsv}><Download/>Export CSV</Button></div></div>
  {error?<div className="p-8 text-center text-red-700">{error}</div>:loading?<div className="p-8 text-center text-slate-500">Preparing account statement…</div>:statement?<><div className="flex flex-wrap items-center justify-between gap-3 border-b bg-slate-50 px-5 py-4"><div><strong className="font-mono">{statement.account.accountNumber}</strong><span className="mx-2 text-slate-300">·</span><strong>{statement.account.name}</strong><small className="ml-2 capitalize text-slate-500">{statement.account.accountType}</small></div><div className="text-sm">Opening balance: <strong>{statement.openingBalance>=0?"Debit":"Credit"} {amount(statement.openingBalance)} {statement.currency}</strong></div></div>{rows.length?<div className="overflow-x-auto"><Table className="min-w-[1180px]"><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Reference</TableHead><TableHead>Source</TableHead><TableHead>Description</TableHead><TableHead>Currency</TableHead><TableHead className="text-right">Debit cur.</TableHead><TableHead className="text-right">Credit cur.</TableHead><TableHead className="border-l text-right">Debit local</TableHead><TableHead className="text-right">Credit local</TableHead><TableHead className="border-l text-right">Running balance</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.id}><TableCell>{new Date(row.transactionDate+"T00:00:00").toLocaleDateString()}</TableCell><TableCell className="font-mono text-xs">{row.reference}</TableCell><TableCell>{source(row.transactionType)}</TableCell><TableCell>{row.notes||"—"}</TableCell><TableCell>{row.currency}</TableCell><Money value={row.indicator==="debit"?row.amountCurrency:0}/><Money value={row.indicator==="credit"?row.amountCurrency:0}/><Money value={row.indicator==="debit"?row.amountLocalCurrency:0} border/><Money value={row.indicator==="credit"?row.amountLocalCurrency:0}/><TableCell className="border-l text-right font-semibold tabular-nums">{row.balance>=0?"Dr":"Cr"} {amount(row.balance)}</TableCell></TableRow>)}</TableBody><TableFooter><TableRow><TableCell colSpan={7}>Period totals · {statement.currency}</TableCell><Money value={totals.debit} border/><Money value={totals.credit}/><TableCell className="border-l text-right font-bold">{closing>=0?"Dr":"Cr"} {amount(closing)}</TableCell></TableRow></TableFooter></Table></div>:<div className="p-10 text-center text-slate-500">No transactions were found in this period.</div>}<div className="flex flex-wrap justify-between gap-3 border-t bg-slate-50 px-5 py-4 text-sm"><span>Period: <strong>{from}</strong> to <strong>{to}</strong></span><span>Closing balance: <strong>{closing>=0?"Debit":"Credit"} {amount(closing)} {statement.currency}</strong></span></div></>:<div className="p-10 text-center text-slate-500">Choose an account and date range, then select Generate.</div>}
 </section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="grid gap-1"><Label>{label}</Label>{children}</div>}
function Money({value,border}:{value:number;border?:boolean}){return <TableCell className={`text-right tabular-nums ${border?"border-l":""}`}>{Math.abs(Number(value))>=0.005?amount(Number(value)):"—"}</TableCell>}
