"use client";
import {useEffect,useState} from "react";
import {Button} from "./ui/button";
import {Input} from "./ui/input";
type Report={fingerprint:string;ready:{party:{id:number;kind:string;name:string};code:string;accountId:number|null}[];issues:{kind:string;id?:number;name?:string;code?:string;reason:string}[];historical:{code:string;count:number}[]};
export default function AccountSetup({onSaved=()=>{},showPrefixes=true}:{onSaved?:()=>void;showPrefixes?:boolean}){
 const [form,setForm]=useState({customerAccountPrefix:"4111",supplierAccountPrefix:"4011",customerGroupName:"Customer control group",supplierGroupName:"Supplier control group",createGroups:true}),[report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(!showPrefixes)return;fetch('/api/account-setup').then(r=>r.json() as Promise<{settings?:{customerAccountPrefix:string;supplierAccountPrefix:string}}>).then(d=>{if(d.settings)setForm(f=>({...f,customerAccountPrefix:d.settings!.customerAccountPrefix,supplierAccountPrefix:d.settings!.supplierAccountPrefix}))}).catch(()=>setMessage("Could not load prefix settings."))},[showPrefixes]);
 async function run(action:"save"|"review"|"apply"){
  setBusy(true);setMessage("");try{const r=await fetch(action==='save'?'/api/account-setup':'/api/account-migration',{method:action==='save'?'PUT':action==='apply'?'POST':'GET',headers:{'content-type':'application/json'},...(action==='review'?{}:{body:JSON.stringify(action==='save'?form:{fingerprint:report?.fingerprint})})});const d=await r.json() as Report & {error?:string;report:Report;message:string};if(!r.ok)throw new Error(d.error);if(action==='review')setReport(d);else if(action==='apply'){setReport(d.report);setMessage(d.message);onSaved()}else{setMessage("Prefixes saved. Existing accounts and links are unchanged.");setReport(null);onSaved()}}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}
 }
 return <section className="my-5 rounded-2xl border bg-white p-5 space-y-4"><h3 className="font-bold text-lg">{showPrefixes?"Account prefixes & migration":"Account migration"}</h3>{showPrefixes?<><p className="text-sm text-slate-600">Prefixes apply to newly created accounts only. Each is a four-digit company group; descriptions are configurable.</p><div className="grid gap-4 md:grid-cols-2">{(['customer','supplier'] as const).map(kind=><div key={kind} className="space-y-2"><label className="text-sm font-medium capitalize">{kind} account prefix<Input aria-label={`${kind} account prefix`} inputMode="numeric" maxLength={4} value={form[`${kind}AccountPrefix`]} onChange={e=>setForm({...form,[`${kind}AccountPrefix`]:e.target.value})}/></label><label className="text-sm">New group description<Input aria-label={`${kind} group description`} maxLength={200} value={form[`${kind}GroupName`]} onChange={e=>setForm({...form,[`${kind}GroupName`]:e.target.value})}/></label></div>)}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.createGroups} onChange={e=>setForm({...form,createGroups:e.target.checked})}/>Create missing prefix groups</label></>:<p className="text-sm text-slate-600">Review existing customers and suppliers before linking their accounts. Manage customer and supplier prefixes in Company Configuration.</p>}<div className="flex flex-wrap gap-2">{showPrefixes&&<Button disabled={busy} onClick={()=>void run('save')}>Save account prefixes</Button>}<Button variant="outline" disabled={busy} onClick={()=>void run('review')}>Review existing data</Button>{report&&report.ready.length>0&&<Button disabled={busy} onClick={()=>void run('apply')}>Apply {report.ready.length} eligible account links</Button>}</div>{message&&<p role="status" className="text-sm">{message}</p>}{report&&<div className="space-y-3"><h4 className="font-semibold">Migration review</h4><p className="text-sm">{report.ready.length} eligible · {report.issues.length} unresolved · {report.historical.reduce((n,r)=>n+r.count,0)} historical entries with missing or incompatible accounts. Historical entries will remain unchanged.</p>{report.ready.map(r=><p className="text-sm" key={`${r.party.kind}-${r.party.id}`}>{r.party.name} → {r.code} ({r.accountId?'preserve and link existing account':'create and link'})</p>)}<div className="max-h-96 overflow-auto space-y-2">{report.issues.map((r,i)=><div key={i} className="rounded border border-amber-200 bg-amber-50 p-3 text-sm"><strong>{r.kind} · {r.name??r.id} {r.code?`(${r.code})`:''}</strong><p>{r.reason}</p></div>)}{report.historical.map(r=><p className="text-sm" key={r.code}>Historical account {r.code||'(blank)'}: {r.count} entries retained for review.</p>)}</div></div>}</section>
}
