"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {Edit3,Plus,Search,WalletCards} from "lucide-react";
import {toast} from "sonner";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Textarea} from "@/components/ui/textarea";
import AccountSetup from "./account-setup";
import type {Currency} from "./currency-register";

type Account={kind?:string;depth?:number;parentId?:number|null;balance?:number;managed?:number;id:number;accountNumber:string;name:string;accountType:string;currency:string;active:boolean;notes:string};
const blank=(currency:string):Account=>({id:0,accountNumber:"",name:"",accountType:"asset",currency,active:true,notes:""});
const labels:Record<string,string>={asset:"Asset",liability:"Liability",equity:"Equity",income:"Income",expense:"Expense",other:"Other"};

export default function AccountMaster({currencies:providedCurrencies=[],defaultCurrency="USD"}:{currencies?:Currency[];defaultCurrency?:string}={}){
 const[accounts,setAccounts]=useState<Account[]>([]),[currencyMaster,setCurrencyMaster]=useState<Currency[]>(providedCurrencies),[companyDefaultCurrency,setCompanyDefaultCurrency]=useState(defaultCurrency),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(()=>blank(defaultCurrency));
 async function load(){setLoading(true);setError("");try{const response=await fetch("/api/accounts"),data=await response.json() as{accounts?:Account[];error?:string};if(!response.ok)throw new Error(data.error);setAccounts(data.accounts??[])}catch(value){setError(value instanceof Error?value.message:"Could not load accounts.")}finally{setLoading(false)}}
 useEffect(()=>{void load();if(!providedCurrencies.length)void Promise.all([fetch("/api/currencies"),fetch("/api/settings")]).then(async([currencyResponse,settingsResponse])=>{const currencyData=await currencyResponse.json() as{currencies?:Currency[]},settingsData=await settingsResponse.json() as{settings?:{defaultCurrency:string}};setCurrencyMaster(currencyData.currencies??[]);if(settingsData.settings?.defaultCurrency)setCompanyDefaultCurrency(settingsData.settings.defaultCurrency)}).catch(()=>{})},[]);
 const [collapsed,setCollapsed]=useState<Set<number>>(new Set());
 const filtered=useMemo(()=>{const matches=accounts.filter(a=>(a.accountNumber+' '+a.name+' '+a.accountType).toLowerCase().includes(query.toLowerCase()));return accounts.filter(a=>query?matches.some(m=>m.id===a.id||(a.kind==='group'&&m.accountNumber.startsWith(a.accountNumber))):!accounts.some(g=>collapsed.has(g.id)&&g.id!==a.id&&a.accountNumber.startsWith(g.accountNumber)))},[accounts,query,collapsed]);
 const currencyOptions=currencyMaster.filter(currency=>currency.active||currency.code===form.currency);
 function add(){setForm(blank(companyDefaultCurrency));setOpen(true)}
 function edit(account:Account){setForm({...account});setOpen(true)}
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);try{const response=await fetch("/api/accounts",{method:form.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),data=await response.json() as{error?:string};if(!response.ok)throw new Error(data.error);toast.success(form.id?"Account updated":"Account created");setOpen(false);await load()}catch(value){toast.error(value instanceof Error?value.message:"Could not save account.")}finally{setSaving(false)}}
 return <>
 <AccountSetup showPrefixes={false} onSaved={()=>void load()}/>
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">
   <div className="space-y-4 border-b p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Chart of accounts</h2><p className="text-sm text-slate-500">Groups contain 1–5 digits; posting accounts contain 10 digits. Balances are in local currency and include each descendant posting once.</p></div><Button onClick={add} className="bg-[#ef4e6f] hover:bg-[#c93454]"><Plus/>Create account</Button></div><div className="relative max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search number, name, or type…" className="pl-9"/></div></div>
   {loading?<p className="p-8 text-center text-slate-500">Loading accounts…</p>:error?<div className="p-8 text-center"><p className="mb-3 text-red-700">{error}</p><Button variant="outline" onClick={()=>void load()}>Try again</Button></div>:filtered.length?<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Account no.</TableHead><TableHead>Account name</TableHead><TableHead>Type</TableHead><TableHead>Grouping / posting</TableHead><TableHead>Balance (local)</TableHead><TableHead>Currency</TableHead><TableHead>Status</TableHead><TableHead>Notes</TableHead><TableHead/></TableRow></TableHeader><TableBody>{filtered.map(account=><TableRow key={account.id}><TableCell className="font-mono font-semibold" style={{paddingLeft:16+(account.depth??0)*20}}>{account.kind==="group"&&<button aria-label={`Toggle ${account.name}`} aria-expanded={!collapsed.has(account.id)} onClick={()=>setCollapsed(old=>{const next=new Set(old);if(next.has(account.id))next.delete(account.id);else next.add(account.id);return next})} className="mr-2">{collapsed.has(account.id)?"▸":"▾"}</button>}{account.accountNumber}</TableCell><TableCell className="font-semibold">{account.name}</TableCell><TableCell>{labels[account.accountType]??account.accountType}</TableCell><TableCell>{account.kind??"legacy"}</TableCell><TableCell className="tabular-nums">{(account.balance??0).toLocaleString(undefined,{maximumFractionDigits:2})}</TableCell><TableCell>{account.currency}</TableCell><TableCell><Badge variant="outline" className={account.active?"border-emerald-200 bg-emerald-50 text-emerald-700":"bg-slate-50 text-slate-600"}>{account.active?"Active":"Inactive"}</Badge></TableCell><TableCell className="max-w-56 truncate">{account.notes||"—"}</TableCell><TableCell><Button size="icon-sm" variant="ghost" aria-label={`Edit ${account.name}`} onClick={()=>edit(account)}><Edit3/></Button></TableCell></TableRow>)}</TableBody></Table></div>:<div className="grid min-h-72 place-items-center p-8 text-center"><div><WalletCards className="mx-auto mb-3 size-10 text-slate-400"/><h3 className="font-bold">No accounts found</h3><p className="mb-4 text-sm text-slate-500">Create the first account in your chart of accounts.</p><Button onClick={add} className="bg-[#ef4e6f] hover:bg-[#c93454]"><Plus/>Create account</Button></div></div>}
  </section>
  <Dialog open={open} onOpenChange={value=>{if(!saving)setOpen(value)}}><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>{form.id?"Edit account":"Create account"}</DialogTitle><DialogDescription>Use 1–5 digits for a group, or 10 digits for a posting account. Groups are optional. Codes with transactions cannot be renumbered.</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><Field label="Account number"><Input required inputMode="numeric" pattern={form.id?undefined:"([0-9]{1,5}|[0-9]{10})"} maxLength={form.id?100:10} readOnly={!!form.managed} value={form.accountNumber} onChange={event=>setForm({...form,accountNumber:event.target.value})} placeholder="Example: 4000"/></Field><Field label="Account name"><Input required maxLength={200} value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder="Example: Sales revenue"/></Field><div className="grid grid-cols-2 gap-4"><Field label="Account type"><Select value={form.accountType} onValueChange={accountType=>setForm({...form,accountType})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(labels).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="Currency"><Select value={form.currency} onValueChange={currency=>setForm({...form,currency})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{currencyOptions.map(currency=><SelectItem key={currency.code} value={currency.code}>{currency.code} · {currency.name}</SelectItem>)}</SelectContent></Select></Field></div><Field label="Status"><Select value={form.active?"active":"inactive"} onValueChange={value=>setForm({...form,active:value==="active"})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent></Select></Field><Field label="Notes"><Textarea maxLength={2000} rows={3} value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></Field></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving||!form.currency} className="bg-[#ef4e6f] hover:bg-[#c93454]">{saving?"Saving…":form.id?"Save changes":"Create account"}</Button></DialogFooter></form></DialogContent></Dialog>
 </>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="grid gap-1.5"><Label>{label}</Label>{children}</div>}
