"use client";
import {Fragment,useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";

type Row={id:number;groupKey:string;transactionDate:string;accountNumber:string;accountName:string;currency:string;reference:string;transactionType:string;amountCurrency:number;amountLocalCurrency:number;indicator:"debit"|"credit";notes:string};
const empty={from:"",to:"",reference:"",account:"",currency:"",type:"",side:"",notes:""};
const amount=(value:number)=>new Intl.NumberFormat("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}).format(value);
const title=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function AccountingTransactions(){
 const [rows,setRows]=useState<Row[]>([]),[filters,setFilters]=useState(empty),[page,setPage]=useState(1),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[refresh,setRefresh]=useState(0),[options,setOptions]=useState<{currencies:string[];types:string[]}>({currencies:[],types:[]});
 function filter(key:keyof typeof empty,value:string){setFilters(f=>({...f,[key]:value}));setPage(1);setLoading(true)}
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{setLoading(true);setError("");void fetch(`/api/accounting-transactions?${new URLSearchParams({page:String(page),...filters})}`,{signal:controller.signal}).then(async response=>{const data=await response.json() as {transactions?:Row[];hasMore?:boolean;error?:string;currencies:string[];types:string[]};if(!response.ok)throw new Error(data.error);if(!controller.signal.aborted){setRows(data.transactions??[]);setMore(!!data.hasMore);setOptions({currencies:data.currencies??[],types:data.types??[]})}}).catch(cause=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:"Could not load journal voucher report.")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})},200);return()=>{clearTimeout(timer);controller.abort()}},[page,filters,refresh]);
 const groups=new Map<string,Row[]>();for(const row of rows)groups.set(row.groupKey,[...(groups.get(row.groupKey)??[]),row]);
 const filtered=Object.values(filters).some(Boolean);
 return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">
 <div className="space-y-4 border-b p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Journal Voucher</h2><p className="text-sm text-slate-500">Entries grouped by reference. Totals reflect the displayed lines and are separated by currency.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>{setFilters(empty);setPage(1);setLoading(true)}} disabled={!filtered}>Clear filters</Button><Button variant="outline" onClick={()=>setRefresh(v=>v+1)}>Refresh</Button></div></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
 {([["from","From date","date"],["to","To date","date"],["reference","Reference","text"],["account","Account number or name","text"],["notes","Notes","text"]] as const).map(([key,label,type])=><div key={key} className="space-y-1"><Label htmlFor={`jv-${key}`}>{label}</Label><Input id={`jv-${key}`} type={type} value={filters[key]} onChange={e=>filter(key,e.target.value)}/></div>)}
 {([["currency","Currency",options.currencies],["type","Entry type",options.types],["side","Debit / credit",["debit","credit"]]] as const).map(([key,label,values])=><div key={key} className="space-y-1"><Label htmlFor={`jv-${key}`}>{label}</Label><select id={`jv-${key}`} className="h-9 w-full rounded-md border bg-white px-3 text-sm" value={filters[key]} onChange={e=>filter(key,e.target.value)}><option value="">All</option>{values.map(v=><option key={v} value={v}>{key==="currency"?v:title(v)}</option>)}</select></div>)}
 </div></div>
 {loading?<p className="p-8 text-center text-slate-500">Loading journal vouchers…</p>:error?<div className="p-8 text-center"><p role="alert" className="mb-3 text-red-700">{error}</p><Button variant="outline" onClick={()=>setRefresh(v=>v+1)}>Try again</Button></div>:rows.length?<div className="overflow-x-auto"><Table className="min-w-[1150px]"><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Account</TableHead><TableHead>Entry type</TableHead><TableHead>Notes</TableHead><TableHead>Currency</TableHead><TableHead className="text-right">Debit currency</TableHead><TableHead className="text-right">Credit currency</TableHead><TableHead className="text-right">Debit local</TableHead><TableHead className="text-right">Credit local</TableHead></TableRow></TableHeader><TableBody>
 {[...groups].map(([key,lines])=>{const currencies=[...new Set(lines.map(r=>r.currency))];return <Fragment key={key}><TableRow className="bg-slate-100"><TableCell colSpan={9} className="font-semibold">Reference: {lines[0].reference||`No reference · entry ${lines[0].id}`}<span className="ml-3 font-normal text-slate-500">{lines.length} {filtered?"matching ":""}lines</span></TableCell></TableRow>{lines.map(row=><TableRow key={row.id}><TableCell className="whitespace-nowrap">{row.transactionDate}</TableCell><TableCell className="font-mono font-semibold">{row.accountNumber||"—"}<span className="block font-sans font-normal text-slate-500">{row.accountName}</span></TableCell><TableCell>{title(row.transactionType)}</TableCell><TableCell className="max-w-72 whitespace-normal">{row.notes||"—"}</TableCell><TableCell>{row.currency}</TableCell>{(["debit","credit"] as const).map(side=><TableCell key={side} className="text-right tabular-nums">{row.indicator===side?amount(row.amountCurrency):"—"}</TableCell>)}{(["debit","credit"] as const).map(side=><TableCell key={side} className="text-right tabular-nums">{row.indicator===side?amount(row.amountLocalCurrency):"—"}</TableCell>)}</TableRow>)}{currencies.map(currency=>{const subset=lines.filter(r=>r.currency===currency),sum=(side:string,local=false)=>subset.filter(r=>r.indicator===side).reduce((n,r)=>n+(local?r.amountLocalCurrency:r.amountCurrency),0);return <TableRow key={currency} className="bg-slate-50 font-semibold"><TableCell colSpan={4}>{filtered?"Matching lines subtotal":"Reference subtotal"}</TableCell><TableCell>{currency}</TableCell><TableCell className="text-right tabular-nums">{amount(sum("debit"))}</TableCell><TableCell className="text-right tabular-nums">{amount(sum("credit"))}</TableCell><TableCell className="text-right tabular-nums">{amount(sum("debit",true))}</TableCell><TableCell className="text-right tabular-nums">{amount(sum("credit",true))}</TableCell></TableRow>})}</Fragment>})}
 </TableBody></Table></div>:<p className="p-8 text-center text-slate-500">No journal voucher entries match these filters.</p>}
 <div className="flex items-center justify-between border-t p-4"><Button variant="outline" disabled={loading||page===1} onClick={()=>{setLoading(true);setPage(v=>v-1)}}>Previous</Button><span className="text-sm text-slate-500">Page {page} · up to 20 references</span><Button variant="outline" disabled={loading||!!error||!more} onClick={()=>{setLoading(true);setPage(v=>v+1)}}>Next</Button></div>
 </section>;
}
