"use client";

import { FormEvent, useEffect, useState } from "react";
import { flushSync } from "react-dom";
import { ContactRound, Info, MapPin, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import type { PriceList } from "./price-list-register";
import type { Salesman } from "./salesman-register";
import type {Currency} from "./currency-register";
import type {CustomerMasterCategory,CustomerMasterValue} from "@/lib/customer-master-catalog";

export type CustomerContact={id?:number;name:string;role:string;phone:string;email:string;receives:string};
export type CustomerAddress={id?:number;addressType:string;label:string;line1:string;line2:string;city:string;region:string;postalCode:string;country:string};

export type CustomerRecord={
 id:number;code:string;accountNumber:string;salesmanId:number;priceListId:number;name:string;status:string;tradingName:string;customerType:string;
 mofNumber:string;companyRegistrationNumber:string;preferredLanguage:string;phone:string;mobile:string;email:string;website:string;address:string;city:string;country:string;
 defaultCurrency:string;paymentTerms:string;creditLimit:number;defaultDiscount:number;customerGroup:string;territory:string;defaultPaymentMethod:string;vatTreatment:string;
 taxRegistrationStatus:string;statementDelivery:string;statementEmail:string;allowCreditSales:boolean;applyWithholdingTax:boolean;creditHold:boolean;blockInvoices:boolean;
 warnCreditLimit:boolean;requirePoNumber:boolean;tags:string;acquisitionSource:string;internalNotes:string;
 contacts?:CustomerContact[];addresses?:CustomerAddress[];
};

const emptyContact=():CustomerContact=>({name:"",role:"",phone:"",email:"",receives:""});
const emptyAddress=():CustomerAddress=>({addressType:"service",label:"",line1:"",line2:"",city:"",region:"",postalCode:"",country:"Lebanon"});
const blankCustomer=(salesmanId:number,priceListId:number,currency:string):CustomerRecord=>({
 id:0,code:"",accountNumber:"",salesmanId,priceListId,name:"",status:"active",tradingName:"",customerType:"individual",mofNumber:"",companyRegistrationNumber:"",preferredLanguage:"English",
 phone:"",mobile:"",email:"",website:"",address:"",city:"",country:"Lebanon",defaultCurrency:currency,paymentTerms:"cash",creditLimit:0,defaultDiscount:0,customerGroup:"retail",territory:"",
 defaultPaymentMethod:"cash",vatTreatment:"standard",taxRegistrationStatus:"not_registered",statementDelivery:"on_request",statementEmail:"",allowCreditSales:true,applyWithholdingTax:false,
 creditHold:false,blockInvoices:false,warnCreditLimit:true,requirePoNumber:false,tags:"",acquisitionSource:"",internalNotes:"",contacts:[],addresses:[],
});

function normalize(value:CustomerRecord):CustomerRecord{return {...value,salesmanId:Number(value.salesmanId)||0,priceListId:Number(value.priceListId)||0,creditLimit:Number(value.creditLimit)||0,defaultDiscount:Number(value.defaultDiscount)||0,allowCreditSales:!!value.allowCreditSales,applyWithholdingTax:!!value.applyWithholdingTax,creditHold:!!value.creditHold,blockInvoices:!!value.blockInvoices,warnCreditLimit:!!value.warnCreditLimit,requirePoNumber:!!value.requirePoNumber,contacts:value.contacts??[],addresses:value.addresses??[]}}

export default function CustomerMasterDialog({open,customerId,salesmen,priceLists,currencies,masterValues,defaultCurrency,onOpenChange,onSaved}:{open:boolean;customerId:number;salesmen:Salesman[];priceLists:PriceList[];currencies:Currency[];masterValues:CustomerMasterValue[];defaultCurrency:string;onOpenChange:(value:boolean)=>void;onSaved:()=>void}){
 const defaultSalesman=salesmen.find(value=>value.active)?.id??0;
 const defaultPriceList=(priceLists.find(value=>value.active&&value.code==="DEFAULT")??priceLists.find(value=>value.active))?.id??0;
 const [form,setForm]=useState<CustomerRecord>(()=>blankCustomer(defaultSalesman,defaultPriceList,defaultCurrency));
 const [loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[tab,setTab]=useState("general");
 function masterOptions(category:CustomerMasterCategory|"currency",current:string,optional=false){
  const options=category==="currency"
   ?currencies.filter(value=>value.active||value.code===current).map(value=>[value.code,`${value.code} · ${value.name}`])
   :masterValues.filter(value=>value.category===category&&(value.active||value.code===current)).map(value=>[value.code,value.name]);
  if(current&&!options.some(([code])=>code===current))options.unshift([current,current.replaceAll("_"," ")]);
  return optional?[["__none__","Not specified"],...options]:options;
 }

 useEffect(()=>{
  if(!open)return;
  setTab("general");
  if(!customerId){setForm(blankCustomer(defaultSalesman,defaultPriceList,defaultCurrency));setLoading(false);return}
  const controller=new AbortController();setLoading(true);
  fetch(`/api/customers?id=${customerId}`,{signal:controller.signal}).then(async response=>{const data=await response.json() as {error?:string;customer?:CustomerRecord};if(!response.ok||!data.customer)throw new Error(data.error||"Could not load customer");setForm(normalize(data.customer))}).catch(error=>{if(error.name!=="AbortError"){toast.error(error instanceof Error?error.message:"Could not load customer");onOpenChange(false)}}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});
  return()=>controller.abort();
 },[open,customerId,defaultSalesman,defaultPriceList,defaultCurrency,onOpenChange]);

 function set<K extends keyof CustomerRecord>(key:K,value:CustomerRecord[K]){setForm(current=>({...current,[key]:value}))}
 function updateContact(index:number,patch:Partial<CustomerContact>){set("contacts",(form.contacts??[]).map((row,i)=>i===index?{...row,...patch}:row))}
 function updateAddress(index:number,patch:Partial<CustomerAddress>){set("addresses",(form.addresses??[]).map((row,i)=>i===index?{...row,...patch}:row))}
 async function submit(event:FormEvent){
  event.preventDefault();setSaving(true);
  try{const response=await fetch("/api/customers",{method:form.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Could not save customer");toast.success(form.id?"Customer updated":"Customer added");onOpenChange(false);onSaved()}
  catch(error){toast.error(error instanceof Error?error.message:"Could not save customer")}
  finally{setSaving(false)}
 }

 return <Dialog open={open} onOpenChange={value=>{if(!saving)onOpenChange(value)}}><DialogContent className="max-h-[94vh] overflow-hidden p-0 sm:max-w-6xl"><form onSubmit={submit} onInvalidCapture={event=>{const panel=(event.target as HTMLElement).closest<HTMLElement>("[data-customer-tab]");if(panel?.dataset.customerTab)flushSync(()=>setTab(panel.dataset.customerTab!))}} className="flex max-h-[94vh] flex-col">
  <DialogHeader className="border-b px-6 py-5 pr-14"><div className="flex flex-wrap items-start justify-between gap-3"><div><DialogTitle>{form.id?"Edit customer":"New customer"}</DialogTitle><DialogDescription>Maintain identity, sales defaults, accounting settings, contacts and addresses.</DialogDescription></div>{form.id&&<Badge variant="outline" className={form.status==="active"?"border-emerald-200 bg-emerald-50 text-emerald-700":form.status==="on_hold"?"border-amber-200 bg-amber-50 text-amber-700":"border-slate-200 bg-slate-50 text-slate-600"}>{form.status==="on_hold"?"On hold":form.status[0]?.toUpperCase()+form.status.slice(1)}</Badge>}</div></DialogHeader>
  {loading?<div className="grid min-h-[520px] place-items-center text-slate-500">Loading customer details…</div>:<Tabs value={tab} onValueChange={setTab} className="min-h-0 flex-1 gap-0 overflow-hidden">
   <div className="overflow-x-auto border-b px-5"><TabsList variant="line" className="h-12 min-w-max gap-3"><TabsTrigger value="general">General</TabsTrigger><TabsTrigger value="commercial">Commercial</TabsTrigger><TabsTrigger value="accounting">Accounting & tax</TabsTrigger><TabsTrigger value="contacts">Contacts & addresses</TabsTrigger><TabsTrigger value="controls">Controls & notes</TabsTrigger></TabsList></div>
   <div className="min-h-0 flex-1 overflow-y-auto bg-[#faf6f7] p-5 md:p-6"><div className="grid">
    <TabsContent forceMount data-customer-tab="general" value="general" inert={tab!=="general"} aria-hidden={tab!=="general"} className="col-start-1 row-start-1 self-start data-[state=inactive]:invisible mt-0 space-y-5">
     <Section title="Identity" description="The legal and operational identity used on invoices and statements."><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Customer code"><Input required={!form.id} inputMode="numeric" pattern={form.id?undefined:"[0-9]{6}"} readOnly={!!form.accountNumber} maxLength={form.id?40:6} value={form.code} onChange={event=>set("code",event.target.value.toUpperCase())} placeholder="000123"/></Field><Field label="Status" required><Choice value={form.status} onChange={value=>set("status",value)} options={[["active","Active"],["on_hold","On hold"],["inactive","Inactive"]]}/></Field><div className="md:col-span-2"><Field label="Legal / customer name" required><Input required maxLength={200} value={form.name} onChange={event=>set("name",event.target.value)}/></Field></div><Field label="Trading name"><Input maxLength={200} value={form.tradingName} onChange={event=>set("tradingName",event.target.value)} placeholder="Business name if different"/></Field><Field label="Customer type" required><Choice value={form.customerType} onChange={value=>set("customerType",value)} options={masterOptions("customer_type",form.customerType)}/></Field><Field label="MOF / VAT number"><Input maxLength={100} value={form.mofNumber} onChange={event=>set("mofNumber",event.target.value)}/></Field><Field label="Company registration number"><Input maxLength={100} value={form.companyRegistrationNumber} onChange={event=>set("companyRegistrationNumber",event.target.value)}/></Field><Field label="Preferred language"><Choice value={form.preferredLanguage} onChange={value=>set("preferredLanguage",value)} options={masterOptions("preferred_language",form.preferredLanguage)}/></Field></div></Section>
     <div className="grid gap-5 lg:grid-cols-2"><Section title="Primary communication" description="Used for routine service and document delivery."><div className="grid gap-4 sm:grid-cols-2"><Field label="Phone"><Input type="tel" maxLength={100} value={form.phone} onChange={event=>set("phone",event.target.value)}/></Field><Field label="Mobile"><Input type="tel" maxLength={100} value={form.mobile} onChange={event=>set("mobile",event.target.value)}/></Field><Field label="Email"><Input type="email" maxLength={320} value={form.email} onChange={event=>set("email",event.target.value)}/></Field><Field label="Website"><Input type="url" maxLength={500} value={form.website} onChange={event=>set("website",event.target.value)} placeholder="https://"/></Field></div></Section><Section title="Primary billing address" description="The default address printed on customer documents."><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Address line 1"><Input maxLength={500} value={form.address} onChange={event=>set("address",event.target.value)}/></Field></div><Field label="City"><Input maxLength={100} value={form.city} onChange={event=>set("city",event.target.value)}/></Field><Field label="Country"><Choice value={form.country} onChange={value=>set("country",value)} options={masterOptions("country",form.country)}/></Field></div></Section></div>
    </TabsContent>

    <TabsContent forceMount data-customer-tab="commercial" value="commercial" inert={tab!=="commercial"} aria-hidden={tab!=="commercial"} className="col-start-1 row-start-1 self-start data-[state=inactive]:invisible mt-0"><Section title="Sales defaults" description="Defaults used when documents are created for this customer."><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Salesman" required><Choice value={form.salesmanId?String(form.salesmanId):""} onChange={value=>set("salesmanId",Number(value))} placeholder="Select salesman" options={salesmen.filter(value=>value.active||value.id===form.salesmanId).map(value=>[String(value.id),`${value.code} · ${value.name}`])}/></Field><Field label="Price list" required><Choice value={form.priceListId?String(form.priceListId):""} onChange={value=>set("priceListId",Number(value))} placeholder="Select price list" options={priceLists.filter(value=>value.active||value.id===form.priceListId).map(value=>[String(value.id),`${value.code} · ${value.name}`])}/></Field><Field label="Default currency" required><Choice value={form.defaultCurrency} onChange={value=>set("defaultCurrency",value)} options={masterOptions("currency",form.defaultCurrency)}/></Field><Field label="Payment terms"><Choice value={form.paymentTerms} onChange={value=>set("paymentTerms",value)} options={masterOptions("payment_terms",form.paymentTerms)}/></Field><Field label="Credit limit"><Input type="number" min="0" step=".01" value={form.creditLimit} onChange={event=>set("creditLimit",Number(event.target.value))}/></Field><Field label="Default discount %"><Input type="number" min="0" max="100" step=".01" value={form.defaultDiscount} onChange={event=>set("defaultDiscount",Number(event.target.value))}/></Field><Field label="Customer group"><Choice value={form.customerGroup} onChange={value=>set("customerGroup",value)} options={masterOptions("customer_group",form.customerGroup)}/></Field><Field label="Territory"><Choice value={form.territory||"__none__"} onChange={value=>set("territory",value==="__none__"?"":value)} options={masterOptions("territory",form.territory,true)}/></Field></div></Section></TabsContent>

    <TabsContent forceMount data-customer-tab="accounting" value="accounting" inert={tab!=="accounting"} aria-hidden={tab!=="accounting"} className="col-start-1 row-start-1 self-start data-[state=inactive]:invisible mt-0"><Section title="Accounting setup" description="Controls posting, statements, tax treatment, and collection behavior."><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Receivable account"><Input readOnly value={form.accountNumber} placeholder="Generated from company prefix + customer code"/><p className="text-xs text-slate-500">Created and linked automatically. Existing account numbers are preserved.</p></Field><Field label="Default payment method"><Choice value={form.defaultPaymentMethod} onChange={value=>set("defaultPaymentMethod",value)} options={masterOptions("payment_method",form.defaultPaymentMethod)}/></Field><Field label="VAT treatment"><Choice value={form.vatTreatment} onChange={value=>set("vatTreatment",value)} options={[["standard","Standard VAT"],["zero_rated","Zero rated"],["exempt","Exempt"],["non_resident","Non-resident"]]}/></Field><Field label="Tax registration status"><Choice value={form.taxRegistrationStatus} onChange={value=>set("taxRegistrationStatus",value)} options={masterOptions("tax_registration_status",form.taxRegistrationStatus)}/></Field><Field label="Statement delivery"><Choice value={form.statementDelivery} onChange={value=>set("statementDelivery",value)} options={masterOptions("statement_delivery",form.statementDelivery)}/></Field><Field label="Statement email"><Input type="email" maxLength={320} value={form.statementEmail} onChange={event=>set("statementEmail",event.target.value)}/></Field></div><div className="mt-5 flex flex-wrap gap-5"><Check label="Allow credit sales" checked={form.allowCreditSales} onChange={value=>set("allowCreditSales",value)}/><Check label="Apply withholding tax" checked={form.applyWithholdingTax} onChange={value=>set("applyWithholdingTax",value)}/></div><div className="mt-5 flex gap-3 rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900"><Info className="mt-0.5 size-4 shrink-0"/><span>Enter opening balances through a journal voucher so the general ledger remains balanced.</span></div></Section></TabsContent>

    <TabsContent forceMount data-customer-tab="contacts" value="contacts" inert={tab!=="contacts"} aria-hidden={tab!=="contacts"} className="col-start-1 row-start-1 self-start data-[state=inactive]:invisible mt-0 space-y-5"><Section title="Contacts" description="People who receive invoices, statements, or service updates." action={<Button type="button" size="sm" variant="outline" onClick={()=>set("contacts",[...(form.contacts??[]),emptyContact()])}><Plus/>Add contact</Button>}>{form.contacts?.length?<div className="space-y-3">{form.contacts.map((row,index)=><div key={row.id??index} className="grid gap-3 rounded-xl border bg-slate-50 p-4 md:grid-cols-2 lg:grid-cols-[1.1fr_.8fr_1fr_1.2fr_1.2fr_auto]"><Field label="Name" required><Input value={row.name} onChange={event=>updateContact(index,{name:event.target.value})}/></Field><Field label="Role"><Input value={row.role} onChange={event=>updateContact(index,{role:event.target.value})} placeholder="Owner, Accounts…"/></Field><Field label="Phone"><Input type="tel" value={row.phone} onChange={event=>updateContact(index,{phone:event.target.value})}/></Field><Field label="Email"><Input type="email" value={row.email} onChange={event=>updateContact(index,{email:event.target.value})}/></Field><Field label="Receives"><Input value={row.receives} onChange={event=>updateContact(index,{receives:event.target.value})} placeholder="Invoices, statements…"/></Field><Button type="button" size="icon-sm" variant="ghost" className="self-end text-red-600" aria-label={`Remove contact ${index+1}`} onClick={()=>set("contacts",(form.contacts??[]).filter((_,i)=>i!==index))}><Trash2/></Button></div>)}</div>:<EmptyRelated icon={ContactRound} text="No additional contacts yet."/>}</Section>
     <Section title="Additional addresses" description="Service, delivery, or other addresses besides the primary billing address." action={<Button type="button" size="sm" variant="outline" onClick={()=>set("addresses",[...(form.addresses??[]),emptyAddress()])}><Plus/>Add address</Button>}>{form.addresses?.length?<div className="space-y-3">{form.addresses.map((row,index)=><div key={row.id??index} className="grid gap-3 rounded-xl border bg-slate-50 p-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Type"><Choice value={row.addressType} onChange={value=>updateAddress(index,{addressType:value})} options={[["billing","Billing"],["service","Service"],["delivery","Delivery"],["other","Other"]]}/></Field><Field label="Label"><Input value={row.label} onChange={event=>updateAddress(index,{label:event.target.value})} placeholder="Branch, warehouse…"/></Field><div className="md:col-span-2"><Field label="Address line 1" required><Input value={row.line1} onChange={event=>updateAddress(index,{line1:event.target.value})}/></Field></div><div className="md:col-span-2"><Field label="Address line 2"><Input value={row.line2} onChange={event=>updateAddress(index,{line2:event.target.value})}/></Field></div><Field label="City"><Input value={row.city} onChange={event=>updateAddress(index,{city:event.target.value})}/></Field><Field label="Region"><Input value={row.region} onChange={event=>updateAddress(index,{region:event.target.value})}/></Field><Field label="Postal code"><Input value={row.postalCode} onChange={event=>updateAddress(index,{postalCode:event.target.value})}/></Field><Field label="Country"><Choice value={row.country} onChange={value=>updateAddress(index,{country:value})} options={masterOptions("country",row.country)}/></Field><div className="md:col-span-2 lg:col-span-4 flex justify-end"><Button type="button" size="sm" variant="ghost" className="text-red-600" onClick={()=>set("addresses",(form.addresses??[]).filter((_,i)=>i!==index))}><Trash2/>Remove address</Button></div></div>)}</div>:<EmptyRelated icon={MapPin} text="No additional addresses yet."/>}</Section>
    </TabsContent>


    <TabsContent forceMount data-customer-tab="controls" value="controls" inert={tab!=="controls"} aria-hidden={tab!=="controls"} className="col-start-1 row-start-1 self-start data-[state=inactive]:invisible mt-0 space-y-5"><div className="grid gap-5 lg:grid-cols-2"><Section title="Transaction controls" description="Warnings and blocks applied before saving new documents."><div className="space-y-4"><Check label="Put customer on credit hold" checked={form.creditHold} onChange={value=>set("creditHold",value)}/><Check label="Block new invoices" checked={form.blockInvoices} onChange={value=>set("blockInvoices",value)}/><Check label="Warn when credit limit is exceeded" checked={form.warnCreditLimit} onChange={value=>set("warnCreditLimit",value)}/><Check label="Require purchase order number" checked={form.requirePoNumber} onChange={value=>set("requirePoNumber",value)}/></div></Section><Section title="Classification" description="Useful for reporting and future CRM segmentation."><div className="grid gap-4"><Field label="Tags"><Input maxLength={500} value={form.tags} onChange={event=>set("tags",event.target.value)} placeholder="Fleet, priority"/></Field><Field label="Acquisition source"><Choice value={form.acquisitionSource||"__none__"} onChange={value=>set("acquisitionSource",value==="__none__"?"":value)} options={masterOptions("acquisition_source",form.acquisitionSource,true)}/></Field></div></Section></div><Section title="Internal notes" description="Visible to staff only and never printed on customer documents."><Textarea maxLength={4000} rows={5} value={form.internalNotes} onChange={event=>set("internalNotes",event.target.value)}/></Section></TabsContent>
   </div>
  </div></Tabs>}
  <DialogFooter className="border-t bg-white px-6 py-4"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={saving||loading||!form.name||!form.salesmanId||!form.priceListId} className="bg-[#ef4e6f] hover:bg-[#c93454]">{saving?"Saving…":"Save customer"}</Button></DialogFooter>
 </form></DialogContent></Dialog>
}

function Field({label,required,children}:{label:string;required?:boolean;children:React.ReactNode}){return <div className="grid gap-1.5"><Label>{label}{required&&<span className="text-red-500"> *</span>}</Label>{children}</div>}
function Choice({value,onChange,options,placeholder}:{value:string;onChange:(value:string)=>void;options:string[][];placeholder?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="w-full"><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{options.map(([key,label])=><SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex cursor-pointer items-center gap-2 text-sm font-medium"><Checkbox checked={checked} onCheckedChange={value=>onChange(value===true)}/><span>{label}</span></label>}
function Section({title,description,action,children}:{title:string;description:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl border border-[#eadfe1] bg-white p-5 shadow-sm"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action}</div>{children}</section>}
function EmptyRelated({icon:Icon,text}:{icon:typeof ContactRound;text:string}){return <div className="grid min-h-36 place-items-center rounded-xl border border-dashed bg-slate-50 text-center text-sm text-slate-500"><div><Icon className="mx-auto mb-2 size-7 text-slate-300"/><p>{text}</p></div></div>}
