"use client";

import {FormEvent,useMemo,useState} from "react";
import {Edit3,ListChecks,Plus} from "lucide-react";
import {toast} from "sonner";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Switch} from "@/components/ui/switch";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {customerMasterCategories,type CustomerMasterCategory,type CustomerMasterValue} from "@/lib/customer-master-catalog";

type Form={id:number;category:CustomerMasterCategory;code:string;name:string;active:boolean;sortOrder:number};
const firstCategory=customerMasterCategories[0].key;
const blank=(category:CustomerMasterCategory):Form=>({id:0,category,code:"",name:"",active:true,sortOrder:0});

export default function CustomerMasterValues({data,query,onSaved}:{data:CustomerMasterValue[];query:string;onSaved:()=>void}){
 const[category,setCategory]=useState<CustomerMasterCategory>(firstCategory),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState<Form>(()=>blank(firstCategory));
 const info=customerMasterCategories.find(value=>value.key===category)??customerMasterCategories[0];
 const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return data.filter(value=>value.category===category&&(!needle||`${value.code} ${value.name}`.toLowerCase().includes(needle)))},[data,category,query]);
 function start(value?:CustomerMasterValue){setForm(value?{...value,category:value.category}:{...blank(category),sortOrder:data.filter(item=>item.category===category).length+1});setOpen(true)}
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);try{const response=await fetch("/api/customer-master-values",{method:form.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),result=await response.json() as{error?:string};if(!response.ok)throw new Error(result.error||"Could not save list value");toast.success(form.id?"List value updated":"List value added");setOpen(false);onSaved()}catch(error){toast.error(error instanceof Error?error.message:"Could not save list value")}finally{setSaving(false)}}
 return <div className="grid gap-5 xl:grid-cols-[260px_minmax(0,1fr)]">
  <aside className="h-fit overflow-hidden rounded-2xl border border-[#eadfe1] bg-white p-2 shadow-sm"><div className="px-3 py-3"><h2 className="font-bold">Customer lists</h2><p className="mt-1 text-sm text-slate-500">Values used by customer dropdowns. Currencies are managed in Company Configuration.</p></div><nav aria-label="Customer master lists" className="space-y-1">{customerMasterCategories.map(value=>{const count=data.filter(item=>item.category===value.key&&item.active).length;return <button type="button" key={value.key} onClick={()=>setCategory(value.key)} className={`flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-sm ${category===value.key?"bg-[#fde8ec] font-semibold text-[#a91f40]":"text-slate-600 hover:bg-slate-50"}`}><span>{value.label}</span><span className="text-xs text-slate-400">{count}</span></button>})}</nav></aside>
  <section className="overflow-hidden rounded-2xl border border-[#eadfe1] bg-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3 border-b p-5"><div><h2 className="font-bold">{info.label}</h2><p className="mt-1 text-sm text-slate-500">Add values or make old values inactive. Codes remain stable for reporting and integrations.</p></div><Button onClick={()=>start()} className="bg-[#ef4e6f] hover:bg-[#c93454]"><Plus/>Add {info.singular}</Button></div>{filtered.length?<Table><TableHeader><TableRow><TableHead>Code</TableHead><TableHead>Name</TableHead><TableHead className="text-right">Order</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{filtered.map(value=><TableRow key={value.id}><TableCell className="font-mono text-xs font-semibold">{value.code}</TableCell><TableCell className="font-semibold">{value.name}</TableCell><TableCell className="text-right">{value.sortOrder||"—"}</TableCell><TableCell><Badge variant="outline" className={value.active?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-slate-200 bg-slate-50 text-slate-600"}>{value.active?"Active":"Inactive"}</Badge></TableCell><TableCell><Button size="icon-sm" variant="ghost" aria-label={`Edit ${value.name}`} onClick={()=>start(value)}><Edit3/></Button></TableCell></TableRow>)}</TableBody></Table>:<div className="grid min-h-80 place-items-center p-8 text-center"><div><ListChecks className="mx-auto mb-3 size-10 text-slate-300"/><h3 className="font-bold">No values found</h3><p className="mt-1 text-sm text-slate-500">Add the first value to this list.</p></div></div>}</section>
  <Dialog open={open} onOpenChange={value=>{if(!saving)setOpen(value)}}><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>{form.id?`Edit ${info.singular}`:`Add ${info.singular}`}</DialogTitle><DialogDescription>{form.id?"Change the display name, order, or status. The code cannot be changed.":"The code is stored on the customer record and cannot be changed later."}</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><div className="grid gap-1.5"><Label>Code <span className="text-red-500">*</span></Label><Input required readOnly={!!form.id} className={form.id?"bg-slate-50":undefined} maxLength={50} value={form.code} onChange={event=>setForm({...form,code:event.target.value.replace(/\s+/g,"_")})} placeholder="corporate"/></div><div className="grid gap-1.5"><Label>Name <span className="text-red-500">*</span></Label><Input required maxLength={100} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></div><div className="grid gap-1.5"><Label>Display order</Label><Input type="number" min="0" step="1" value={form.sortOrder} onChange={event=>setForm({...form,sortOrder:Number(event.target.value)})}/></div><label className="flex items-center gap-3"><Switch checked={form.active} onCheckedChange={active=>setForm({...form,active})}/><span className="text-sm font-medium">Active</span></label></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving} className="bg-[#ef4e6f] hover:bg-[#c93454]">{saving?"Saving…":"Save value"}</Button></DialogFooter></form></DialogContent></Dialog>
 </div>;
}

export type {CustomerMasterValue};
