"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {Plus,Edit3} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from './ui/dialog';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from './ui/table';
export type ExpenseCategory={id:number;name:string;active:boolean};

export function ExpenseCategoryDialog({open,onOpenChange,category,onSaved}:{open:boolean;onOpenChange:(open:boolean)=>void;category?:ExpenseCategory;onSaved:(category:ExpenseCategory)=>void}){
 const [name,setName]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open){setName(category?.name??'');setError('')}},[open,category]);
 async function save(event:FormEvent){event.preventDefault();event.stopPropagation();if(!name.trim())return;setSaving(true);setError('');try{const r=await fetch('/api/expense-categories',{method:category?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...category,active:category?Boolean(category.active):true,name:name.trim()})}),data=await r.json() as {category:ExpenseCategory;error?:string};if(!r.ok)throw new Error(data.error);onSaved(data.category);onOpenChange(false);toast.success(category?'Category updated':'Category created')}catch(e){setError(e instanceof Error?e.message:'Could not save category')}finally{setSaving(false)}}
 return <Dialog open={open} onOpenChange={value=>{if(!saving)onOpenChange(value)}}><DialogContent><form onSubmit={save}><DialogHeader><DialogTitle>{category?'Edit expense category':'New expense category'}</DialogTitle><DialogDescription>Available in purchase expenses and the expense register.</DialogDescription></DialogHeader><div className="space-y-3 py-5"><label className="grid gap-2 text-sm font-medium">Category name<Input autoFocus required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Freight"/></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div><DialogFooter><Button type="button" variant="outline" disabled={saving} onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={saving||!name.trim()} className="bg-[#ef4e6f] hover:bg-[#c93454]">{saving?'Saving…':'Save category'}</Button></DialogFooter></form></DialogContent></Dialog>
}

export default function ExpenseCategoryMaster(){
 const [categories,setCategories]=useState<ExpenseCategory[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState<ExpenseCategory>(),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);try{const r=await fetch('/api/expense-categories'),data=await r.json() as {categories:ExpenseCategory[];error?:string};if(!r.ok)throw new Error(data.error);setCategories(data.categories);setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load categories')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function toggle(category:ExpenseCategory){setBusy(true);try{const r=await fetch('/api/expense-categories',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...category,active:!category.active})}),data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error);await load()}catch(e){toast.error(e instanceof Error?e.message:'Could not update category')}finally{setBusy(false)}}
 const filtered=categories.filter(c=>c.name.toLowerCase().includes(query.toLowerCase()));
 return <div className="space-y-5"><section className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-white p-5 shadow-sm"><div><h2 className="text-lg font-bold">Expense categories</h2><p className="text-sm text-slate-500">Master data for purchases and operating expenses.</p></div><Button className="bg-[#ef4e6f] hover:bg-[#c93454]" onClick={()=>{setEditing(undefined);setOpen(true)}}><Plus/>New category</Button></section><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-4"><Input className="max-w-sm" aria-label="Search expense categories" placeholder="Search categories…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading?<p className="p-6">Loading categories…</p>:error?<div role="alert" className="space-y-3 p-6"><p>{error}</p><Button onClick={()=>void load()}>Try again</Button></div>:!filtered.length?<p className="p-8 text-center text-slate-500">No categories found. Create a category to get started.</p>:<Table><TableHeader><TableRow><TableHead>Category</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{filtered.map(c=><TableRow key={c.id}><TableCell className="font-medium">{c.name}</TableCell><TableCell>{c.active?'Active':'Inactive'}</TableCell><TableCell><div className="flex justify-end gap-2"><Button variant="ghost" size="sm" disabled={busy} onClick={()=>{setEditing(c);setOpen(true)}}><Edit3/>Edit</Button><Button variant="outline" size="sm" disabled={busy} onClick={()=>void toggle(c)}>{c.active?'Deactivate':'Activate'}</Button></div></TableCell></TableRow>)}</TableBody></Table>}</section><ExpenseCategoryDialog open={open} onOpenChange={setOpen} category={editing} onSaved={()=>void load()}/></div>
}
