"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Edit3, Plus, ReceiptText, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import type { WorkshopSettings } from "../db/settings";
import type {Currency} from "./currency-register";

type Expense = { id:number; expenseDate:string; category:string; description:string; amount:number; currency:string; notes:string };
type Category = { id:number; name:string; active:boolean };
const today=()=>{const date=new Date(),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,10)};
const blank=(currency:string):Expense=>({id:0,expenseDate:today(),category:"",description:"",amount:0,currency,notes:""});
const money=(amount:number,currency:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency}).format(amount);

export default function ExpenseRegister({settings,currencies:providedCurrencies=[]}:{settings:WorkshopSettings;currencies?:Currency[]}){
 const [expenses,setExpenses]=useState<Expense[]>([]),[categories,setCategories]=useState<Category[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState<Expense>(()=>blank(settings.defaultCurrency));
 const [currencyMaster,setCurrencyMaster]=useState<Currency[]>(providedCurrencies);
 const [categoryOpen,setCategoryOpen]=useState(false),[categorySaving,setCategorySaving]=useState(false),[categoryForm,setCategoryForm]=useState({id:0,name:""});
 async function load(){setLoading(true);setError("");try{const [expenseResponse,categoryResponse]=await Promise.all([fetch("/api/expenses"),fetch("/api/expense-categories")]),expenseData=await expenseResponse.json() as {error?:string;expenses?:Expense[]},categoryData=await categoryResponse.json() as {error?:string;categories?:Category[]};if(!expenseResponse.ok||!categoryResponse.ok)throw new Error(expenseData.error||categoryData.error);setExpenses(expenseData.expenses??[]);setCategories(categoryData.categories??[])}catch(value){setError(value instanceof Error?value.message:"Could not load expenses") }finally{setLoading(false)}}
 useEffect(()=>{void load();if(!providedCurrencies.length)void fetch("/api/currencies").then(async response=>await response.json() as {currencies?:Currency[]}).then(data=>setCurrencyMaster(data.currencies??[])).catch(()=>{})},[]);
 const filtered=useMemo(()=>expenses.filter(expense=>`${expense.expenseDate} ${expense.category} ${expense.description} ${expense.currency} ${expense.notes}`.toLowerCase().includes(query.toLowerCase())),[expenses,query]);
 const totals=useMemo(()=>Object.entries(expenses.reduce<Record<string,number>>((sum,expense)=>({...sum,[expense.currency]:(sum[expense.currency]??0)+expense.amount}),{})),[expenses]);
 const currencies=currencyMaster.filter(currency=>currency.active||currency.code===form.currency).map(currency=>currency.code);
 const availableCategories=categories.filter(category=>category.active||category.name===form.category);
 function add(){setForm(blank(settings.defaultCurrency));setOpen(true)}
 function edit(expense:Expense){setForm({...expense});setOpen(true)}
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);try{const response=await fetch("/api/expenses",{method:form.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);toast.success(form.id?"Expense updated":"Expense registered");setOpen(false);await load()}catch(value){toast.error(value instanceof Error?value.message:"Could not save expense")}finally{setSaving(false)}}
 async function saveCategory(event:FormEvent){event.preventDefault();setCategorySaving(true);try{const response=await fetch("/api/expense-categories",{method:categoryForm.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(categoryForm)}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);toast.success(categoryForm.id?"Category updated":"Category added");setCategoryForm({id:0,name:""});await load()}catch(value){toast.error(value instanceof Error?value.message:"Could not save category")}finally{setCategorySaving(false)}}
 async function toggleCategory(category:Category){setCategorySaving(true);try{const response=await fetch("/api/expense-categories",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...category,active:!category.active})}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);await load()}catch(value){toast.error(value instanceof Error?value.message:"Could not update category")}finally{setCategorySaving(false)}}
 return <div className="space-y-5">
  <section className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-white p-5 shadow-sm"><div><h2 className="text-lg font-bold">Expense register</h2><p className="text-sm text-slate-500">Record workshop operating costs and purchases.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setCategoryOpen(true)}>Manage categories</Button><Button onClick={add} className="bg-[#ef4e6f] hover:bg-[#c93454]"><Plus/>Register expense</Button></div></section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{totals.length?totals.map(([currency,total])=><div key={currency} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Total expenses · {currency}</p><strong className="mt-2 block text-2xl">{money(total,currency)}</strong></div>):<div className="rounded-2xl border bg-white p-5 text-slate-500 shadow-sm">No expenses registered yet.</div>}</section>
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-4"><div className="relative max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search expenses…" className="pl-9"/></div></div>{loading?<p className="p-8 text-center text-slate-500">Loading expenses…</p>:error?<div className="p-8 text-center"><p className="mb-3 text-red-700">{error}</p><Button variant="outline" onClick={()=>void load()}>Try again</Button></div>:filtered.length?<Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Category</TableHead><TableHead>Description</TableHead><TableHead>Notes</TableHead><TableHead className="text-right">Amount</TableHead><TableHead/></TableRow></TableHeader><TableBody>{filtered.map(expense=><TableRow key={expense.id}><TableCell>{new Date(expense.expenseDate+"T00:00:00").toLocaleDateString()}</TableCell><TableCell className="font-semibold">{expense.category}</TableCell><TableCell>{expense.description}</TableCell><TableCell className="max-w-64 truncate">{expense.notes||"—"}</TableCell><TableCell className="text-right font-bold">{money(expense.amount,expense.currency)}</TableCell><TableCell><Button size="icon-sm" variant="ghost" aria-label={`Edit ${expense.description}`} onClick={()=>edit(expense)}><Edit3/></Button></TableCell></TableRow>)}</TableBody></Table>:<div className="grid min-h-64 place-items-center p-8 text-center"><div><ReceiptText className="mx-auto mb-3 size-10 text-slate-400"/><h3 className="font-bold">No expenses found</h3><p className="text-sm text-slate-500">Register the workshop’s first expense.</p></div></div>}</section>
  <Dialog open={open} onOpenChange={value=>{if(!saving)setOpen(value)}}><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>{form.id?"Edit expense":"Register expense"}</DialogTitle><DialogDescription>Enter the expense details for your records.</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><div className="grid grid-cols-2 gap-4"><div className="grid gap-1.5"><Label>Date *</Label><Input type="date" required value={form.expenseDate} onChange={event=>setForm({...form,expenseDate:event.target.value})}/></div><div className="grid gap-1.5"><Label>Category *</Label><Select value={form.category} onValueChange={category=>setForm({...form,category})} required><SelectTrigger><SelectValue placeholder="Select category"/></SelectTrigger><SelectContent>{availableCategories.map(category=><SelectItem key={category.id} value={category.name}>{category.name}</SelectItem>)}</SelectContent></Select></div></div><div className="grid gap-1.5"><Label>Description *</Label><Input required maxLength={2000} value={form.description} onChange={event=>setForm({...form,description:event.target.value})} placeholder="What was paid for?"/></div><div className="grid grid-cols-2 gap-4"><div className="grid gap-1.5"><Label>Amount *</Label><Input type="number" min="0.01" step="0.01" required value={form.amount||""} onChange={event=>setForm({...form,amount:+event.target.value})}/></div><div className="grid gap-1.5"><Label>Currency *</Label><Select value={form.currency} onValueChange={currency=>setForm({...form,currency})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{currencies.map(currency=><SelectItem key={currency} value={currency}>{currency}</SelectItem>)}</SelectContent></Select></div></div><div className="grid gap-1.5"><Label>Notes</Label><Textarea maxLength={2000} rows={3} value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})} placeholder="Receipt number, supplier, payment method…"/></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving} className="bg-[#ef4e6f] hover:bg-[#c93454]">{saving?"Saving…":form.id?"Save changes":"Register expense"}</Button></DialogFooter></form></DialogContent></Dialog>
  <Dialog open={categoryOpen} onOpenChange={value=>{if(!categorySaving){setCategoryOpen(value);if(!value)setCategoryForm({id:0,name:""})}}}><DialogContent><DialogHeader><DialogTitle>Expense categories</DialogTitle><DialogDescription>Add, rename, activate, or deactivate expense categories.</DialogDescription></DialogHeader><form onSubmit={saveCategory} className="flex gap-2"><Input required maxLength={100} aria-label="Category name" value={categoryForm.name} onChange={event=>setCategoryForm({...categoryForm,name:event.target.value})} placeholder="Category name"/><Button disabled={categorySaving} className="bg-[#ef4e6f] hover:bg-[#c93454]">{categoryForm.id?"Save":"Add"}</Button>{categoryForm.id>0&&<Button type="button" variant="outline" onClick={()=>setCategoryForm({id:0,name:""})}>Cancel</Button>}</form><div className="max-h-80 divide-y overflow-y-auto rounded-xl border">{categories.map(category=><div key={category.id} className="flex items-center gap-3 p-3"><div className="min-w-0 flex-1"><p className="truncate font-medium">{category.name}</p><p className={`text-xs ${category.active?"text-emerald-700":"text-slate-500"}`}>{category.active?"Active":"Inactive"}</p></div><Button size="sm" variant="ghost" disabled={categorySaving} onClick={()=>setCategoryForm({id:category.id,name:category.name})}><Edit3/>Rename</Button><Button size="sm" variant="outline" disabled={categorySaving} onClick={()=>void toggleCategory(category)}>{category.active?"Deactivate":"Activate"}</Button></div>)}</div><DialogFooter><Button variant="outline" onClick={()=>setCategoryOpen(false)}>Close</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
