"use client";
import {WarehouseSelect,warehouseApi,type Warehouse} from './warehouses';
import {useEffect,useState,type ReactNode} from 'react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from './ui/dialog';
import {defaultMaster,validateMaster,type ItemMaster} from '../lib/item-master';
export type MasterItem=ItemMaster&{id:number;sku:string;name:string;brand:string;salePrice:number;vatRate:number;discountRate:number;stockQty:number;averageCost:number|null};
type ListValue={id:number;category:string;name:string;parent:string;active:number};
const control='h-10 w-full rounded-md border bg-white px-3 text-sm';
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label>}
export default function ItemMasterDialog({item,suppliers,onClose,onSaved,currency}:{item:MasterItem;suppliers:{id:number;name:string;code:string}[];onClose:()=>void;onSaved:()=>void;currency:string}){
 const [form,setForm]=useState<MasterItem>(()=>({...defaultMaster(),...item})),[tab,setTab]=useState('General'),[values,setValues]=useState<ListValue[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[adjust,setAdjust]=useState(false),[adjustment,setAdjustment]=useState({quantity:'',unit:item.baseUnit||'unit',reason:'',requestKey:crypto.randomUUID()}),[list,setList]=useState({category:'group',name:'',parent:''});
 const [warehouseCode,setWarehouseCode]=useState('MAIN'),[warehouseStocks,setWarehouseStocks]=useState<Warehouse[]>([]);
 const loadWarehouseStocks=()=>warehouseApi<{warehouses:Warehouse[]}>('/api/warehouses?itemId='+form.id).then(d=>setWarehouseStocks(d.warehouses));
 useEffect(()=>{void loadWarehouseStocks().catch(e=>setError(e.message))},[form.id]);
 const warehouseQty=warehouseStocks.find(w=>w.code===warehouseCode)?.quantity??0;
 const patch=(change:Partial<MasterItem>)=>setForm(f=>({...f,...change}));
 async function api(url:string,method='GET',body?:unknown){const r=await fetch(url,{method,headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),d=await r.json() as {error?:string;values:ListValue[];stockQty:number};if(!r.ok)throw new Error(d.error||'Could not save.');return d}
 const loadLists=()=>api('/api/item-master-values').then(d=>setValues(d.values));
 useEffect(()=>{void loadLists().catch(e=>setError(e.message))},[]);
 async function run(task:()=>Promise<void>){setBusy(true);setError('');try{await task()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function options(category:string,current:string,parent=''){const rows=values.filter(v=>v.category===category&&(category!=='subgroup'||v.parent===parent)&&(v.active||v.name===current));return <><option value="">Not assigned</option>{current&&!rows.some(v=>v.name===current)&&<option>{current}</option>}{rows.map(v=><option key={v.id} value={v.name}>{v.name}{v.active?'':' (inactive)'}</option>)}</>}
 function units(value:string,onChange:(value:string)=>void){return <select aria-label="Unit" className={control} value={value} onChange={e=>onChange(e.target.value)}>{form.units.map(u=><option key={u.code} value={u.code}>{u.code}</option>)}</select>}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="max-h-[94vh] overflow-y-auto sm:max-w-4xl"><form onSubmit={e=>{e.preventDefault();void run(async()=>{validateMaster(form);await api('/api/items',form.id?'PUT':'POST',form);onSaved();onClose()})}}><DialogHeader><DialogTitle>{form.id?'Edit item':'New item'}</DialogTitle><DialogDescription>{form.sku?form.sku+' · ':''}Item details, units, barcodes and suppliers</DialogDescription></DialogHeader>
 <div role="tablist" aria-label="Item details" className="my-5 flex flex-wrap gap-1 border-b pb-2">{['General','Units','Barcodes','Suppliers','Stock','Manage lists'].map(t=><button key={t} type="button" role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} className={'rounded-lg px-4 py-2 text-sm font-medium '+(tab===t?'bg-[#fde8ec] text-[#a91f40]':'text-slate-600 hover:bg-slate-100')}>{t}</button>)}</div>
 {error&&<p role="alert" className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
 <div role="tabpanel" aria-label={tab} className="min-h-72 space-y-4 pb-5">
 {tab==='General'&&<><div className="grid gap-4 sm:grid-cols-2"><Field label="Item code"><Input required value={form.sku} onChange={e=>patch({sku:e.target.value})}/></Field><Field label="Status"><select className={control} value={form.active?'active':'inactive'} onChange={e=>patch({active:e.target.value==='active'})}><option value="active">Active</option><option value="inactive">Inactive</option></select></Field></div><Field label="Item name"><Input required value={form.name} onChange={e=>patch({name:e.target.value})}/></Field><div className="grid gap-4 sm:grid-cols-3"><Field label="Group"><select className={control} value={form.group} onChange={e=>patch({group:e.target.value,subgroup:''})}>{options('group',form.group)}</select></Field><Field label="Subgroup"><select className={control} disabled={!form.group} value={form.subgroup} onChange={e=>patch({subgroup:e.target.value})}>{options('subgroup',form.subgroup,form.group)}</select></Field><Field label="Brand"><select className={control} value={form.brand} onChange={e=>patch({brand:e.target.value})}>{options('brand',form.brand)}</select></Field><Field label={'Sale price / '+form.baseUnit+' · '+currency}><Input type="number" min="0" step="any" value={form.salePrice} onChange={e=>patch({salePrice:+e.target.value})}/></Field><Field label="VAT %"><Input type="number" min="0" max="100" step="any" value={form.vatRate} onChange={e=>patch({vatRate:+e.target.value})}/></Field><Field label="Default discount %"><Input type="number" min="0" max="100" step="any" value={form.discountRate} onChange={e=>patch({discountRate:+e.target.value})}/></Field></div><p className="text-sm text-slate-500">Inactive items remain in history and cannot be selected for new sales or purchases.</p></>}
 {tab==='Units'&&<><p className="text-sm text-slate-600">Factor = number of base stock units. For example, a box of 12 has factor 12. Saved units and factors are retained to protect history.</p><div className="space-y-2">{form.units.map((u,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] items-center gap-3"><Field label="Unit"><Input aria-label={'Unit name '+(i+1)} disabled={!!item.id&&item.units.some(v=>v.code===u.code)} value={u.code} onChange={e=>{const code=e.target.value;patch({units:form.units.map((v,n)=>n===i?{...v,code}:v),...(form.baseUnit===u.code?{baseUnit:code}:{}),...(form.salesUnit===u.code?{salesUnit:code}:{}),...(form.purchaseUnit===u.code?{purchaseUnit:code}:{})})}}/></Field><Field label="Base units per unit"><Input aria-label={'Conversion factor '+(i+1)} type="number" min="0.000000001" step="any" disabled={u.code===form.baseUnit||!!item.id&&item.units.some(v=>v.code===u.code)} value={u.factor} onChange={e=>patch({units:form.units.map((v,n)=>n===i?{...v,factor:+e.target.value}:v)})}/></Field><Button type="button" variant="ghost" disabled={u.code===form.baseUnit||!!item.id&&item.units.some(v=>v.code===u.code)} onClick={()=>patch({units:form.units.filter((_,n)=>n!==i)})}>Remove</Button></div>)}</div><Button type="button" variant="outline" onClick={()=>patch({units:[...form.units,{code:'',factor:1}]})}>Add unit</Button><div className="grid gap-4 sm:grid-cols-3"><Field label="Base stock unit"><select className={control} disabled={!!form.id} value={form.baseUnit} onChange={e=>patch({baseUnit:e.target.value,units:form.units.map(u=>u.code===e.target.value?{...u,factor:1}:u)})}>{form.units.map(u=><option key={u.code}>{u.code}</option>)}</select></Field><Field label="Default sales unit">{units(form.salesUnit,salesUnit=>patch({salesUnit}))}</Field><Field label="Default purchase unit">{units(form.purchaseUnit,purchaseUnit=>patch({purchaseUnit}))}</Field></div></>}
 {tab==='Barcodes'&&<><p className="text-sm text-slate-600">Barcodes are unique across items in this company. Keep leading zeroes; choose one primary barcode.</p>{form.barcodes.map((b,i)=><div key={i} className="grid gap-3 rounded-lg border p-3 sm:grid-cols-[1fr_150px_100px_auto]"><Field label="Barcode"><Input value={b.code} onChange={e=>patch({barcodes:form.barcodes.map((v,n)=>n===i?{...v,code:e.target.value}:v)})}/></Field><Field label="Unit">{units(b.unit,unit=>patch({barcodes:form.barcodes.map((v,n)=>n===i?{...v,unit}:v)}))}</Field><label className="flex items-center gap-2 text-sm"><input type="radio" name="primaryBarcode" checked={b.primary} onChange={()=>patch({barcodes:form.barcodes.map((v,n)=>({...v,primary:n===i}))})}/>Primary</label><Button type="button" variant="ghost" onClick={()=>{const next=form.barcodes.filter((_,n)=>n!==i);if(b.primary&&next.length)next[0]={...next[0],primary:true};patch({barcodes:next})}}>Remove</Button></div>)}<Button type="button" variant="outline" onClick={()=>patch({barcodes:[...form.barcodes,{code:'',unit:form.baseUnit,primary:!form.barcodes.length}]})}>Add barcode</Button></>}
 {tab==='Suppliers'&&<>{form.itemSuppliers.map((s,i)=><div key={i} className="grid gap-3 rounded-lg border p-3 sm:grid-cols-2"><Field label="Supplier"><select className={control} value={s.supplierId} onChange={e=>patch({itemSuppliers:form.itemSuppliers.map((v,n)=>n===i?{...v,supplierId:+e.target.value}:v)})}><option value="0">Select supplier</option>{suppliers.map(v=><option key={v.id} value={v.id}>{v.code} · {v.name}</option>)}</select></Field><Field label="Supplier item code"><Input value={s.itemCode} onChange={e=>patch({itemSuppliers:form.itemSuppliers.map((v,n)=>n===i?{...v,itemCode:e.target.value}:v)})}/></Field><Field label="Purchase unit">{units(s.unit,unit=>patch({itemSuppliers:form.itemSuppliers.map((v,n)=>n===i?{...v,unit}:v)}))}</Field><div className="flex items-center justify-between"><label className="flex items-center gap-2 text-sm"><input type="radio" name="defaultSupplier" checked={s.isDefault} onChange={()=>patch({itemSuppliers:form.itemSuppliers.map((v,n)=>({...v,isDefault:n===i}))})}/>Default supplier</label><Button type="button" variant="ghost" onClick={()=>{const next=form.itemSuppliers.filter((_,n)=>n!==i);if(s.isDefault&&next.length)next[0]={...next[0],isDefault:true};patch({itemSuppliers:next})}}>Remove</Button></div></div>)}<Button type="button" variant="outline" onClick={()=>patch({itemSuppliers:[...form.itemSuppliers,{supplierId:0,itemCode:'',unit:form.purchaseUnit,isDefault:!form.itemSuppliers.length}]})}>Add supplier</Button></>}
 {tab==='Stock'&&<><div className="divide-y rounded-xl border">{warehouseStocks.map(w=><div key={w.code} className="flex justify-between p-3 text-sm"><span>{w.code} · {w.name}</span><strong>{w.quantity} {form.baseUnit}</strong></div>)}</div><div className="grid gap-4 rounded-xl bg-slate-50 p-5 sm:grid-cols-2"><Field label={'Stock on hand · '+form.baseUnit}><Input readOnly aria-readonly value={form.stockQty}/></Field><Field label={'Average purchase cost / '+form.baseUnit+' · '+currency}><Input readOnly value={form.averageCost??'No recorded cost'}/></Field></div><p className="text-sm text-slate-600">Stock changes through purchases, posted invoices, returns and reasoned adjustments.</p><Button type="button" variant="outline" disabled={!form.id} onClick={()=>setAdjust(!adjust)}>Adjust stock</Button>{!form.id&&<p className="text-sm text-slate-500">Save the item first, then enter opening stock using an adjustment.</p>}{adjust&&<div className="space-y-3 rounded-xl border p-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Warehouse"><WarehouseSelect value={warehouseCode} onChange={setWarehouseCode}/></Field><Field label="Quantity change (+ add / − remove)"><Input type="number" step="any" value={adjustment.quantity} onChange={e=>setAdjustment({...adjustment,quantity:e.target.value})}/></Field><Field label="Unit">{units(adjustment.unit,unit=>setAdjustment({...adjustment,unit}))}</Field></div><Field label="Reason"><Input value={adjustment.reason} onChange={e=>setAdjustment({...adjustment,reason:e.target.value})} placeholder="Stock count correction, damaged goods…"/></Field><p className="text-sm">Warehouse stock after adjustment: {warehouseQty+Number(adjustment.quantity)*(form.units.find(u=>u.code===adjustment.unit)?.factor??1)} {form.baseUnit}</p><Button type="button" disabled={busy} onClick={()=>void run(async()=>{const d=await api('/api/items/adjust-stock','POST',{...adjustment,itemId:form.id,warehouseCode,expectedStock:warehouseQty});patch({stockQty:d.stockQty});await loadWarehouseStocks();setAdjust(false);setAdjustment({...adjustment,quantity:'',reason:'',requestKey:crypto.randomUUID()});onSaved()})}>Apply adjustment</Button></div>}</>}
 {tab==='Manage lists'&&<><p className="text-sm text-slate-600">Add or deactivate groups, subgroups and brands. Existing item assignments remain visible.</p><div className="grid gap-3 sm:grid-cols-3"><Field label="List"><select className={control} value={list.category} onChange={e=>setList({...list,category:e.target.value})}><option value="group">Groups</option><option value="subgroup">Subgroups</option><option value="brand">Brands</option></select></Field>{list.category==='subgroup'&&<Field label="Parent group"><select className={control} value={list.parent} onChange={e=>setList({...list,parent:e.target.value})}>{options('group',list.parent)}</select></Field>}<Field label="New name"><Input value={list.name} onChange={e=>setList({...list,name:e.target.value})}/></Field></div><Button type="button" variant="outline" disabled={busy} onClick={()=>void run(async()=>{await api('/api/item-master-values','POST',list);setList({...list,name:''});await loadLists()})}>Add to list</Button><div className="divide-y rounded-lg border">{values.filter(v=>v.category===list.category).map(v=><div key={v.id} className="flex items-center justify-between gap-3 p-3 text-sm"><span>{v.parent?v.parent+' / ':''}{v.name}{v.active?'':' · Inactive'}</span><Button type="button" variant="ghost" disabled={busy} onClick={()=>void run(async()=>{await api('/api/item-master-values','PUT',{id:v.id,active:!v.active});await loadLists()})}>{v.active?'Deactivate':'Activate'}</Button></div>)}</div></>}
 </div><DialogFooter><Button type="button" variant="outline" onClick={onClose} disabled={busy}>Cancel</Button><Button disabled={busy} className="bg-[#ef4e6f] hover:bg-[#c93454]">{busy?'Saving…':'Save item'}</Button></DialogFooter></form></DialogContent></Dialog>
}
