"use client";
import {useState,type RefObject} from 'react';
import {Combobox,ComboboxContent,ComboboxEmpty,ComboboxInput,ComboboxItem,ComboboxList} from './ui/combobox';
import type {ItemMaster} from '../lib/item-master';
type PickItem=ItemMaster&{id:number;sku:string;name:string};
export default function ItemPicker<T extends PickItem>({items,value,onSelect,container,kind='sales',supplierId}:{items:T[];value:number|null;onSelect:(item:T|null,unit:string)=>void;container?:RefObject<HTMLDivElement|null>;kind?:'sales'|'purchase';supplierId?:number}){
 const [query,setQuery]=useState('');
 function select(item:T|null){const barcode=item?.barcodes.find(b=>b.code.toLowerCase()===query.trim().toLowerCase()),unit=barcode?.unit||(kind==='purchase'?(item?.itemSuppliers.find(s=>supplierId?s.supplierId===supplierId:s.isDefault)?.unit||item?.purchaseUnit):item?.salesUnit)||'unit';onSelect(item,unit);setQuery('')}
 return <Combobox items={items.filter(i=>i.active||i.id===value)} value={items.find(i=>i.id===value)??null} onValueChange={select} itemToStringLabel={i=>`${i.sku} · ${i.name} ${i.barcodes.map(b=>b.code).join(' ')}`} isItemEqualToValue={(a,b)=>a.id===b.id}><ComboboxInput className="w-full" aria-label="Search item or barcode" placeholder="Item name, code or barcode" showClear onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){const item=items.find(i=>i.active&&i.barcodes.some(b=>b.code.toLowerCase()===query.trim().toLowerCase()));if(item){e.preventDefault();select(item)}}}}/><ComboboxContent portalContainer={container}><ComboboxEmpty>No matching active item.</ComboboxEmpty><ComboboxList>{i=><ComboboxItem key={i.id} value={i}><span className="font-mono text-xs">{i.sku}</span><span>{i.name}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox>
}
export function UnitSelect({item,value,onChange}:{item?:PickItem;value?:string;onChange:(unit:string,factor:number,previousFactor:number)=>void}){if(!item)return null;const current=value||item.salesUnit;return <select aria-label="Transaction unit" className="mt-1 h-9 w-full rounded-md border bg-white px-1 text-sm" value={current} onChange={e=>onChange(e.target.value,item.units.find(u=>u.code===e.target.value)!.factor,item.units.find(u=>u.code===current)?.factor??1)}>{!item.units.some(u=>u.code===current)&&<option>{current}</option>}{item.units.map(u=><option key={u.code} value={u.code}>{u.code} (×{u.factor})</option>)}</select>}
