"use client";
import {useEffect,useState} from 'react';
import type {MasterItem} from './item-master-dialog';
import {Combobox,ComboboxContent,ComboboxEmpty,ComboboxInput,ComboboxItem,ComboboxList} from './ui/combobox';
import {Button} from './ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from './ui/table';

type Movement={id:number;type:string;reference:string;date:string;warehouse:string;quantity:number;balance:number;notes:string};
type Data={item:MasterItem;warehouses:{code:string;name:string;active:number;quantity:number}[];summary:{transactionCount:number;firstPurchase:string|null;lastPurchase:string|null;firstSale:string|null;lastSale:string|null;purchased:number;sold:number;returned:number};averages:{kind:string;currency:string|null;quantity:number;average:number|null}[];transactions:Movement[];hasMore:boolean};
type DocumentData={document:{reference:string;date:string;party?:string;currency?:string;subtotal?:number;tax?:number;total?:number;notes?:string};lines:{description:string;quantity:number;unit:string;price?:number;amount?:number;warehouse?:string}[];printUrl:string|null};
const qty=(n:number)=>Number(n).toLocaleString(undefined,{maximumFractionDigits:9});
const price=(n:number,currency:string)=>Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:4})+' '+currency;
const labels:Record<string,string>={purchase:'Purchase',sale:'Sale',sales_return:'Sales return',credit_return:'Credit return',opening:'Opening balance',adjustment:'Stock adjustment',transfer_in:'Transfer in',transfer_out:'Transfer out'};
export default function ItemDashboard({items,currency}:{items:MasterItem[];currency:string}){
 const [selected,setSelected]=useState<MasterItem|null>(null),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [reference,setReference]=useState<Movement|null>(null),[document,setDocument]=useState<DocumentData|null>(null),[documentError,setDocumentError]=useState('');
 useEffect(()=>{setData(null);setError('');if(!selected){setLoading(false);return}const controller=new AbortController();setLoading(true);fetch(`/api/item-dashboard?itemId=${selected.id}&page=${page}`,{signal:controller.signal}).then(async response=>{const body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||'Could not load item.');setData(body)}).catch(error=>{if(!controller.signal.aborted)setError(error.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[selected,page,refresh]);
 useEffect(()=>{setDocument(null);setDocumentError('');if(!reference||!selected)return;const controller=new AbortController();fetch(`/api/item-dashboard?itemId=${selected.id}&transactionId=${reference.id}`,{signal:controller.signal}).then(async response=>{const body=await response.json() as DocumentData&{error?:string};if(!response.ok)throw new Error(body.error||'Could not open reference.');setDocument(body)}).catch(error=>{if(!controller.signal.aborted)setDocumentError(error.message)});return()=>controller.abort()},[reference,selected]);
 const unit=data?.item.baseUnit??selected?.baseUnit??'unit';
 return <section className="space-y-5">
 <div className="flex flex-wrap items-end justify-between gap-4 rounded-2xl border bg-white p-5"><div className="w-full max-w-xl"><label htmlFor="dashboard-item" className="mb-2 block text-sm font-semibold">Select an item</label><Combobox items={items} value={selected} onValueChange={item=>{setSelected(item);setData(null);setPage(1);setReference(null)}} itemToStringLabel={item=>item.sku+' · '+item.name} isItemEqualToValue={(a,b)=>a.id===b.id} filter={(item,query)=>[item.sku,item.name,...item.barcodes.map(b=>b.code)].join(' ').toLowerCase().includes(query.trim().toLowerCase())}><ComboboxInput id="dashboard-item" className="w-full" placeholder="Search item code, name, or barcode" showClear/><ComboboxContent><ComboboxEmpty>No matching items.</ComboboxEmpty><ComboboxList>{item=><ComboboxItem key={item.id} value={item}>{item.sku} · {item.name}{!item.active?' (inactive)':''}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div><Button variant="outline" disabled={!selected||loading} onClick={()=>setRefresh(v=>v+1)}>Refresh</Button></div>
 {!selected?<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-slate-500">Select an item to see its stock, trading history, and transactions.</div>:loading?<p role="status" className="p-8 text-center">Loading item dashboard…</p>:error?<div role="alert" className="rounded-xl border bg-white p-6 text-red-700">{error}<Button variant="outline" className="ml-3" onClick={()=>setRefresh(v=>v+1)}>Try again</Button></div>:data&&<>
 <div className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-sm text-slate-500">{data.item.sku}</p><h2 className="text-2xl font-bold">{data.item.name}</h2><p className="mt-1 text-sm text-slate-500">{[data.item.group,data.item.subgroup,data.item.brand].filter(Boolean).join(' · ')||'No group or brand assigned'}</p></div><span className={'rounded-full px-3 py-1 text-sm '+(data.item.active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600')}>{data.item.active?'Active':'Inactive'}</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Stock on hand" value={qty(data.item.stockQty)+' '+unit}/><Metric label="Current selling price / base unit" value={price(data.item.salePrice,currency)}/><Metric label="VAT / default discount" value={qty(data.item.vatRate)+'% / '+qty(data.item.discountRate)+'%'}/><Metric label="Sales / purchase unit" value={data.item.salesUnit+' / '+data.item.purchaseUnit}/></div><p className="mt-4 text-sm text-slate-500">Units: {data.item.units.map(u=>u.code+' = '+qty(u.factor)+' '+unit).join(' · ')}</p>{data.item.barcodes.length>0&&<p className="mt-1 break-words text-sm text-slate-500">Barcodes: {data.item.barcodes.map(b=>b.code+' ('+b.unit+')').join(' · ')}</p>}</div>
 <div className="grid gap-5 lg:grid-cols-2"><div className="overflow-hidden rounded-2xl border bg-white"><h3 className="p-5 font-bold">Quantity by warehouse</h3><Table><TableHeader><TableRow><TableHead>Warehouse</TableHead><TableHead className="text-right">Quantity ({unit})</TableHead></TableRow></TableHeader><TableBody>{data.warehouses.map(w=><TableRow key={w.code}><TableCell>{w.code} · {w.name}{!w.active&&<small className="ml-2 text-slate-500">Inactive</small>}</TableCell><TableCell className={'text-right tabular-nums '+(w.quantity<0?'text-amber-700':'')}>{qty(w.quantity)}</TableCell></TableRow>)}<TableRow><TableCell className="font-bold">Total</TableCell><TableCell className="text-right font-bold">{qty(data.warehouses.reduce((sum,w)=>sum+w.quantity,0))}</TableCell></TableRow></TableBody></Table></div><div className="rounded-2xl border bg-white p-5"><h3 className="mb-4 font-bold">Trading history</h3><div className="grid grid-cols-2 gap-5"><Metric label="First purchase" value={data.summary.firstPurchase??'No purchases'}/><Metric label="Last purchase" value={data.summary.lastPurchase??'No purchases'}/><Metric label="First sale" value={data.summary.firstSale??'No sales'}/><Metric label="Last sale" value={data.summary.lastSale??'No sales'}/><Metric label="Purchased" value={qty(data.summary.purchased)+' '+unit}/><Metric label="Sold / returned" value={qty(data.summary.sold)+' / '+qty(data.summary.returned)+' '+unit}/></div><p className="mt-4 text-xs text-slate-500">All recorded stock history. Sales and returns are shown separately; draft documents are excluded.</p></div></div>
 <div className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Average cost and selling price</h3><p className="mt-1 text-sm text-slate-500">Quantity-weighted per {unit}, separately for each currency. Purchase cost includes recorded landed costs. Selling prices are before discounts and VAT. Returns, transfers, and uncosted opening stock are excluded.</p>{data.averages.length?<div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{data.averages.map(a=><Metric key={a.kind+':'+a.currency} label={(a.kind==='purchase'?'Average purchase cost':'Average selling price')+' · '+(a.currency??'Unknown currency')} value={a.average==null?'—':price(a.average,a.currency??'')} />)}</div>:<p className="mt-4 text-slate-500">No priced purchases or sales recorded.</p>}</div>
 <div className="overflow-hidden rounded-2xl border bg-white"><div className="p-5"><h3 className="font-bold">Item transactions <span className="font-normal text-slate-500">({data.summary.transactionCount})</span></h3><p className="mt-1 text-sm text-slate-500">Click a reference to open its details. Quantities and warehouse balances are in {unit}; newest postings first.</p></div><div className="overflow-x-auto"><Table><TableHeader><TableRow>{['Date','Reference','Type','Warehouse','Qty in','Qty out','Warehouse balance'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{data.transactions.map(row=><TableRow key={row.id}><TableCell>{row.date||'Opening'}</TableCell><TableCell><button type="button" className="font-semibold text-[#a91f40] underline" onClick={()=>setReference(row)}>{row.reference||'Movement '+row.id}</button></TableCell><TableCell>{labels[row.type]??row.type}</TableCell><TableCell>{row.warehouse}</TableCell><TableCell>{row.quantity>0?qty(row.quantity):'—'}</TableCell><TableCell>{row.quantity<0?qty(-row.quantity):'—'}</TableCell><TableCell>{qty(row.balance)}</TableCell></TableRow>)}</TableBody></Table></div>{!data.transactions.length&&<p className="p-6 text-slate-500">No recorded movements.</p>}<div className="flex items-center justify-between border-t p-4"><Button variant="outline" disabled={page===1} onClick={()=>setPage(v=>v-1)}>Previous</Button><span className="text-sm text-slate-500">Page {page}</span><Button variant="outline" disabled={!data.hasMore} onClick={()=>setPage(v=>v+1)}>Next</Button></div></div>
 </>}
 <Dialog open={!!reference} onOpenChange={open=>{if(!open)setReference(null)}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>{reference?.reference||'Transaction details'}</DialogTitle><DialogDescription>{reference?labels[reference.type]??reference.type:''}</DialogDescription></DialogHeader>{documentError?<p role="alert" className="text-red-700">{documentError}</p>:!document?<p role="status">Loading reference…</p>:<><div className="flex flex-wrap justify-between gap-3"><p>{document.document.date||'Opening balance'}{document.document.party&&<strong className="block">{document.document.party}</strong>}</p>{document.printUrl&&<a className="text-[#a91f40] underline" href={document.printUrl} target="_blank" rel="noreferrer">Open full printable document</a>}</div><Table><TableHeader><TableRow><TableHead>Description</TableHead><TableHead>Qty / unit</TableHead><TableHead>Price</TableHead><TableHead>Line amount / warehouse</TableHead></TableRow></TableHeader><TableBody>{document.lines.map((line,index)=><TableRow key={index}><TableCell className="whitespace-normal">{line.description}</TableCell><TableCell>{qty(line.quantity)} {line.unit}</TableCell><TableCell>{line.price==null?'—':price(line.price,document.document.currency??'')}</TableCell><TableCell>{line.amount==null?line.warehouse??'—':price(line.amount,document.document.currency??'')}</TableCell></TableRow>)}</TableBody></Table>{document.document.total!=null&&<p className="text-right font-bold">Document total: {price(document.document.total,document.document.currency??'')}</p>}{document.document.notes&&<p className="whitespace-pre-wrap text-sm text-slate-600">{document.document.notes}</p>}</>}</DialogContent></Dialog>
 </section>;
}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>}