"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { Edit3, Eye, Plus, Printer, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Combobox, ComboboxContent, ComboboxEmpty, ComboboxInput, ComboboxItem, ComboboxList } from "@/components/ui/combobox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import type {Currency} from "./currency-register";

type Voucher={id:number;transactionType:string;sourceId:number;transactionDate:string;reference:string;currency:string;lineCount:number;debit:number;credit:number;debitLocal:number;creditLocal:number;externalReference:string;voucherNotes:string};
type Line={id:number;accountNumber:string;accountName:string;currency:string;amountCurrency:number;amountLocalCurrency:number;indicator:"debit"|"credit";notes:string};
type Account={id:number;accountNumber:string;name:string;accountType:string;currency:string;active:boolean};
type EntryLine={accountNumber:string;description:string;currency:string;debit:number;credit:number;localAmount:number};
type EntryForm={voucherDate:string;externalReference:string;notes:string;lines:EntryLine[]};
const amount=(value:number)=>new Intl.NumberFormat("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}).format(value);
const source=(value:string)=>value==="sale"?"Sales invoice":value==="purchase"?"Purchase invoice":value==="journal"?"Manual journal":value;
const today=()=>{const date=new Date(),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,10)};
const emptyLine=(currency:string):EntryLine=>({accountNumber:"",description:"",currency,debit:0,credit:0,localAmount:0});
const blank=(currency:string):EntryForm=>({voucherDate:today(),externalReference:"",notes:"",lines:[emptyLine(currency),emptyLine(currency)]});

export default function JournalVouchers({currencies:providedCurrencies=[]}:{currencies?:Currency[]}={}){
 const dialogRef=useRef<HTMLDivElement>(null);
 const[vouchers,setVouchers]=useState<Voucher[]>([]),[query,setQuery]=useState(""),[page,setPage]=useState(1),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
 const[selected,setSelected]=useState<Voucher|null>(null),[lines,setLines]=useState<Line[]>([]),[detailLoading,setDetailLoading]=useState(false);
 const[currencyMaster,setCurrencyMaster]=useState<Currency[]>(providedCurrencies);
 const[entryOpen,setEntryOpen]=useState(false),[editing,setEditing]=useState<Voucher|null>(null),[saving,setSaving]=useState(false),[accounts,setAccounts]=useState<Account[]>([]),[form,setForm]=useState<EntryForm>(()=>blank("USD")),[currencyInfo,setCurrencyInfo]=useState({defaultCurrency:"USD",localCurrency:"USD",localCurrencyRate:1});
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{setLoading(true);setError("");void fetch(`/api/journal-vouchers?${new URLSearchParams({page:String(page),q:query})}`,{signal:controller.signal}).then(async response=>{const data=await response.json() as{vouchers?:Voucher[];hasMore?:boolean;error?:string};if(!response.ok)throw new Error(data.error);if(!controller.signal.aborted){setVouchers(data.vouchers??[]);setMore(!!data.hasMore)}}).catch(value=>{if(!controller.signal.aborted)setError(value instanceof Error?value.message:"Could not load journal vouchers.")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})},200);return()=>{clearTimeout(timer);controller.abort()}},[page,query,refresh]);
 useEffect(()=>{if(!providedCurrencies.length)void fetch("/api/currencies").then(async response=>await response.json() as {currencies?:Currency[]}).then(data=>setCurrencyMaster(data.currencies??[])).catch(()=>{})},[]);
 const totals=useMemo(()=>form.lines.reduce((sum,line)=>({debitLocal:sum.debitLocal+(line.debit?(Number(line.localAmount)||0):0),creditLocal:sum.creditLocal+(line.credit?(Number(line.localAmount)||0):0)}),{debitLocal:0,creditLocal:0}),[form.lines]);
 const currencies=useMemo(()=>currencyMaster.filter(currency=>currency.active||form.lines.some(line=>line.currency===currency.code)).map(currency=>currency.code),[currencyMaster,form.lines]);
 const balanced=form.lines.length>=2&&totals.debitLocal>0&&Math.abs(totals.debitLocal-totals.creditLocal)<0.005;
 async function openVoucher(voucher:Voucher){setSelected(voucher);setLines([]);setDetailLoading(true);try{const response=await fetch(`/api/journal-vouchers?${new URLSearchParams({type:voucher.transactionType,sourceId:String(voucher.sourceId)})}`),data=await response.json() as{lines?:Line[];error?:string};if(!response.ok)throw new Error(data.error);setLines(data.lines??[])}catch(value){setError(value instanceof Error?value.message:"Could not open journal voucher.");setSelected(null)}finally{setDetailLoading(false)}}
 async function addVoucher(){try{const[accountResponse,settingsResponse]=await Promise.all([fetch("/api/accounts?posting=1"),fetch("/api/settings")]),accountData=await accountResponse.json() as{accounts?:Account[];error?:string},settingsData=await settingsResponse.json() as{settings?:{defaultCurrency:string;localCurrency:string;localCurrencyRate:number};error?:string};if(!accountResponse.ok||!settingsResponse.ok)throw new Error(accountData.error||settingsData.error);const active=(accountData.accounts??[]).filter(account=>account.active),info=settingsData.settings??{defaultCurrency:"USD",localCurrency:"USD",localCurrencyRate:1};if(active.length<2)throw new Error("Create at least two active accounts before entering a JV.");setAccounts(active);setCurrencyInfo(info);setEditing(null);setForm(blank(info.defaultCurrency));setEntryOpen(true)}catch(value){toast.error(value instanceof Error?value.message:"Could not load accounts.")}}
 async function editVoucher(voucher:Voucher){try{const params=new URLSearchParams({type:"journal",sourceId:String(voucher.sourceId)}),[accountResponse,settingsResponse,detailResponse]=await Promise.all([fetch("/api/accounts?posting=1"),fetch("/api/settings"),fetch(`/api/journal-vouchers?${params}`)]),accountData=await accountResponse.json() as{accounts?:Account[];error?:string},settingsData=await settingsResponse.json() as{settings?:{defaultCurrency:string;localCurrency:string;localCurrencyRate:number};error?:string},detailData=await detailResponse.json() as{lines?:Line[];error?:string};if(!accountResponse.ok||!settingsResponse.ok||!detailResponse.ok)throw new Error(accountData.error||settingsData.error||detailData.error);const active=(accountData.accounts??[]).filter(account=>account.active),info=settingsData.settings??{defaultCurrency:"USD",localCurrency:"USD",localCurrencyRate:1};setAccounts(active);setCurrencyInfo(info);setEditing(voucher);setForm({voucherDate:voucher.transactionDate,externalReference:voucher.externalReference,notes:voucher.voucherNotes,lines:(detailData.lines??[]).map(line=>({accountNumber:line.accountNumber,description:line.notes,currency:line.currency,debit:line.indicator==="debit"?line.amountCurrency:0,credit:line.indicator==="credit"?line.amountCurrency:0,localAmount:line.amountLocalCurrency}))});setEntryOpen(true)}catch(value){toast.error(value instanceof Error?value.message:"Could not load journal voucher.")}}
 function updateLine(index:number,change:Partial<EntryLine>){setForm(current=>({...current,lines:current.lines.map((line,lineIndex)=>lineIndex===index?{...line,...change}:line)}))}
 function rateFor(currency:string){return Number(currencyMaster.find(value=>value.code===currency)?.rate)||1}
 function updateCurrency(index:number,currency:string){setForm(current=>({...current,lines:current.lines.map((line,lineIndex)=>lineIndex===index?{...line,currency,localAmount:(line.debit||line.credit)*rateFor(currency)}:line)}))}
 function updateAmount(index:number,side:"debit"|"credit",value:number){setForm(current=>({...current,lines:current.lines.map((line,lineIndex)=>lineIndex===index?{...line,[side]:value,[side==="debit"?"credit":"debit"]:0,localAmount:value*rateFor(line.currency)}:line)}))}
 function removeLine(index:number){setForm(current=>({...current,lines:current.lines.filter((_,lineIndex)=>lineIndex!==index)}))}
 async function submit(event:FormEvent){event.preventDefault();if(!balanced)return;setSaving(true);try{const response=await fetch("/api/journal-vouchers",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,...(editing?{sourceId:editing.sourceId}:{})})}),data=await response.json() as{voucherNumber?:string;error?:string};if(!response.ok)throw new Error(data.error);toast.success(`${data.voucherNumber??"JV"} ${editing?"updated":"posted"}`);setEntryOpen(false);setEditing(null);setPage(1);setRefresh(value=>value+1)}catch(value){toast.error(value instanceof Error?value.message:"Could not save journal voucher.")}finally{setSaving(false)}}
 return <>
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">
   <div className="space-y-4 border-b p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Journal vouchers (JV)</h2><p className="text-sm text-slate-500">Enter and review balanced debit and credit entries by reference.</p></div><Button onClick={()=>void addVoucher()} className="bg-[#ef4e6f] hover:bg-[#c93454]"><Plus/>New JV</Button></div><div className="relative max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Label htmlFor="jv-search" className="sr-only">Search references</Label><Input id="jv-search" value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Search reference or source…" className="pl-9"/></div></div>
   {loading?<p className="p-8 text-center text-slate-500">Loading journal vouchers…</p>:error?<div className="p-8 text-center text-red-700">{error}</div>:vouchers.length?<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>JV reference</TableHead><TableHead>External reference</TableHead><TableHead>Source</TableHead><TableHead>Currencies</TableHead><TableHead className="text-right">Debit local</TableHead><TableHead className="text-right">Credit local</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{vouchers.map(voucher=>{const isBalanced=Math.abs(voucher.debitLocal-voucher.creditLocal)<0.005;return <TableRow key={`${voucher.transactionType}-${voucher.sourceId}`}><TableCell>{new Date(voucher.transactionDate+"T00:00:00").toLocaleDateString()}</TableCell><TableCell className="font-mono font-semibold">{voucher.reference}</TableCell><TableCell>{voucher.externalReference||"—"}</TableCell><TableCell>{source(voucher.transactionType)}<small className="block text-slate-500">{voucher.lineCount} lines</small></TableCell><TableCell>{voucher.currency}</TableCell><TableCell className="text-right tabular-nums">{amount(voucher.debitLocal)}</TableCell><TableCell className="text-right tabular-nums">{amount(voucher.creditLocal)}</TableCell><TableCell><Badge variant="outline" className={isBalanced?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-red-200 bg-red-50 text-red-700"}>{isBalanced?"Balanced":"Unbalanced"}</Badge></TableCell><TableCell><div className="flex gap-2">{voucher.transactionType==="journal"&&<Button size="sm" variant="outline" onClick={()=>void editVoucher(voucher)}><Edit3/>Edit</Button>}<Button size="sm" variant="outline" onClick={()=>void openVoucher(voucher)}><Eye/>View</Button><a className="inline-flex h-8 items-center gap-1.5 rounded-md border px-3 text-sm font-medium hover:bg-slate-100" href={`/jv-print?type=${encodeURIComponent(voucher.transactionType)}&sourceId=${voucher.sourceId}`} target="_blank" rel="noopener noreferrer" aria-label={`Print ${voucher.reference}`}><Printer className="size-3.5"/>Print</a></div></TableCell></TableRow>})}</TableBody></Table></div>:<p className="p-8 text-center text-slate-500">No journal vouchers found.</p>}
   <div className="flex items-center justify-between border-t p-4"><Button variant="outline" disabled={loading||page===1} onClick={()=>setPage(value=>value-1)}>Previous</Button><span className="text-sm text-slate-500">Page {page}</span><Button variant="outline" disabled={loading||!more} onClick={()=>setPage(value=>value+1)}>Next</Button></div>
  </section>
  <Dialog open={entryOpen} onOpenChange={value=>{if(!saving){setEntryOpen(value);if(!value)setEditing(null)}}}>
   <DialogContent ref={dialogRef} className="max-h-[94vh] w-[96vw] max-w-none overflow-y-auto sm:max-w-[96vw] xl:max-w-7xl">
    <form onSubmit={submit}><DialogHeader><DialogTitle>{editing?`Edit ${editing.reference}`:"New journal voucher"}</DialogTitle><DialogDescription>{editing?"Update the voucher details and balanced accounting lines.":"The JV number is generated when the balanced entry is posted."}</DialogDescription></DialogHeader>
     <div className="grid gap-4 py-5">
      <div className="grid gap-4 sm:grid-cols-2">
       <Field label="Date"><Input type="date" required value={form.voucherDate} onChange={event=>setForm({...form,voucherDate:event.target.value})}/></Field>
       <Field label="Local currency"><Input value={currencyInfo.localCurrency} readOnly className="bg-slate-50"/></Field>
      </div>
      <div className="grid gap-4 md:grid-cols-2"><Field label="External reference"><Input maxLength={200} value={form.externalReference} onChange={event=>setForm({...form,externalReference:event.target.value})} placeholder="Cheque, document, or memo no."/></Field><Field label="Notes"><Textarea maxLength={2000} rows={2} value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></Field></div>
      <div className="overflow-x-auto rounded-xl border"><Table className="min-w-[1240px]"><TableHeader><TableRow><TableHead className="min-w-64">Account</TableHead><TableHead className="min-w-52">Description</TableHead><TableHead className="w-32">Currency</TableHead><TableHead className="w-36 text-right">Debit · currency</TableHead><TableHead className="w-36 text-right">Credit · currency</TableHead><TableHead className="w-48 text-right">Countervalue · {currencyInfo.localCurrency}</TableHead><TableHead className="w-14"/></TableRow></TableHeader><TableBody>{form.lines.map((line,index)=><TableRow key={index}><TableCell><Combobox items={accounts} value={accounts.find(account=>account.accountNumber===line.accountNumber)??null} onValueChange={account=>updateLine(index,{accountNumber:account?.accountNumber??""})} itemToStringLabel={account=>`${account.accountNumber} · ${account.name}`} isItemEqualToValue={(item,value)=>item.id===value.id}><ComboboxInput className="w-full" aria-label="Search account" placeholder="Search number or name" showClear/><ComboboxContent portalContainer={dialogRef}><ComboboxEmpty>No matching account.</ComboboxEmpty><ComboboxList>{account=><ComboboxItem key={account.id} value={account}><span className="font-mono text-xs font-semibold text-slate-500">{account.accountNumber}</span><span>{account.name}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></TableCell><TableCell><Input maxLength={500} value={line.description} onChange={event=>updateLine(index,{description:event.target.value})} placeholder="Line description"/></TableCell><TableCell><Select value={line.currency} onValueChange={currency=>updateCurrency(index,currency)}><SelectTrigger className="w-full"><SelectValue placeholder="Currency"/></SelectTrigger><SelectContent>{currencies.map(currency=><SelectItem key={currency} value={currency}>{currency}</SelectItem>)}</SelectContent></Select></TableCell><TableCell><Input type="number" min="0" step="0.01" value={line.debit||""} onChange={event=>updateAmount(index,"debit",Number(event.target.value))} className="text-right"/></TableCell><TableCell><Input type="number" min="0" step="0.01" value={line.credit||""} onChange={event=>updateAmount(index,"credit",Number(event.target.value))} className="text-right"/></TableCell><TableCell><Input type="number" min="0" step="0.01" required value={line.localAmount||""} onChange={event=>updateLine(index,{localAmount:Number(event.target.value)})} className="bg-slate-50 text-right font-medium"/></TableCell><TableCell><Button type="button" size="icon-sm" variant="ghost" aria-label="Remove line" disabled={form.lines.length<=2} onClick={()=>removeLine(index)}><Trash2/></Button></TableCell></TableRow>)}</TableBody></Table></div>
      <p className="text-xs text-slate-500">The local countervalue is calculated when you enter a currency amount. You can change it before posting.</p>
      <Button type="button" variant="outline" className="w-fit" onClick={()=>setForm(current=>({...current,lines:[...current.lines,emptyLine(currencyInfo.defaultCurrency)]}))}><Plus/>Add line</Button>
      <div className={`grid gap-3 rounded-xl p-4 text-sm sm:grid-cols-3 ${balanced?"bg-emerald-50":"bg-amber-50"}`}><span>Debit local: <strong>{amount(totals.debitLocal)} {currencyInfo.localCurrency}</strong></span><span>Credit local: <strong>{amount(totals.creditLocal)} {currencyInfo.localCurrency}</strong></span><strong className={balanced?"text-emerald-700":"text-amber-700"}>{balanced?"Balanced in local currency":"Local debit and credit must balance"}</strong></div>
     </div>
     <DialogFooter><Button type="button" variant="outline" onClick={()=>{setEntryOpen(false);setEditing(null)}}>Cancel</Button><Button disabled={saving||!balanced} className="bg-[#ef4e6f] hover:bg-[#c93454]">{saving?"Saving…":editing?"Save changes":"Post JV"}</Button></DialogFooter>
    </form>
   </DialogContent>
  </Dialog>
  <Dialog open={!!selected} onOpenChange={value=>{if(!value)setSelected(null)}}><DialogContent className="max-w-4xl"><DialogHeader><DialogTitle>JV · {selected?.reference}</DialogTitle><DialogDescription>{selected&&`${new Date(selected.transactionDate+"T00:00:00").toLocaleDateString()} · ${source(selected.transactionType)} · ${selected.currency}${selected.externalReference?` · ${selected.externalReference}`:""}`}</DialogDescription></DialogHeader>{detailLoading?<p className="p-8 text-center text-slate-500">Loading entries…</p>:<div className="max-h-[60vh] overflow-auto rounded-xl border"><Table><TableHeader><TableRow><TableHead>Account</TableHead><TableHead>Description</TableHead><TableHead className="text-right">Debit</TableHead><TableHead className="text-right">Credit</TableHead><TableHead className="text-right">Local amount</TableHead></TableRow></TableHeader><TableBody>{lines.map(line=><TableRow key={line.id}><TableCell className="font-mono font-semibold">{line.accountNumber}<small className="block font-sans font-normal text-slate-500">{line.accountName}</small></TableCell><TableCell>{line.notes||"—"}</TableCell><TableCell className="text-right tabular-nums">{line.indicator==="debit"?`${amount(line.amountCurrency)} ${line.currency}`:"—"}</TableCell><TableCell className="text-right tabular-nums">{line.indicator==="credit"?`${amount(line.amountCurrency)} ${line.currency}`:"—"}</TableCell><TableCell className="text-right tabular-nums">{amount(line.amountLocalCurrency)}</TableCell></TableRow>)}</TableBody></Table></div>}</DialogContent></Dialog>
 </>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="grid gap-1.5"><Label>{label}</Label>{children}</div>}
