"use client";
import {useEffect,useRef,useState} from 'react';
import {ChevronDown,Download,Printer,RefreshCw,Save,X} from 'lucide-react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import InvoiceDetailDialog from './invoice-detail-dialog';
import {definitions,labels,validateFilters,type Filters,type ReportRow} from '../lib/operational-reports';
import {filterDescription,type ReportResult} from '../lib/operational-report-excel';

const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const defaults=(id=''):Filters=>({from:today().slice(0,8)+'01',to:today(),search:'',selections:{},min:'',max:'',mode:'detail',group:'',sort:['stock-balance','price-cost'].includes(id)?'sku':'date',descending:false});
const selectClass='h-9 max-w-full rounded-md border bg-white px-2 text-sm';
const display=(v:unknown)=>v===null?'Unavailable':typeof v==='number'?v.toLocaleString('en-US',{maximumFractionDigits:9}):String(v??'—');
async function api(url:string,body?:unknown,signal?:AbortSignal){const r=await fetch(url,{signal,...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'Request failed.');return d;}
function Multi({label,values,selected,onChange}:{label:string;values:string[];selected:string[];onChange:(v:string[])=>void}){const [search,setSearch]=useState('');return <details className="relative rounded-md border bg-white"><summary className="cursor-pointer p-2 text-sm">{label}{selected.length?` (${selected.length})`:''}</summary><div className="space-y-2 border-t p-2"><Input aria-label={'Search '+label} placeholder="Search…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="max-h-44 overflow-y-auto">{values.filter(v=>v.toLowerCase().includes(search.toLowerCase())).map(v=><label key={v} className="flex cursor-pointer items-start gap-2 rounded p-1 text-sm hover:bg-rose-50"><input type="checkbox" className="mt-1" checked={selected.includes(v)} onChange={()=>onChange(selected.includes(v)?selected.filter(x=>x!==v):[...selected,v])}/>{v}</label>)}{!values.length&&<p className="p-2 text-sm text-slate-500">No recorded values</p>}</div></div></details>}
export default function OperationalReport({id}:{id:string}){
 const d=definitions[id], [draft,setDraft]=useState<Filters>(()=>defaults(id)),[report,setReport]=useState<ReportResult|null>(null),[busy,setBusy]=useState(false),[exporting,setExporting]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[page,setPage]=useState(1),[advanced,setAdvanced]=useState(false),[presets,setPresets]=useState<{name:string;filters:Filters}[]>([]),[presetName,setPresetName]=useState(''),[chosenPreset,setChosenPreset]=useState(''),[invoiceId,setInvoiceId]=useState<number|null>(null),[document,setDocument]=useState<ReportRow|null>(null),[detail,setDetail]=useState<any>(null),[detailError,setDetailError]=useState('');
 const generation=useRef(0),trigger=useRef<HTMLButtonElement|null>(null);
 async function run(f:Filters,remember=true){try{validateFilters(f)}catch(e){setError((e as Error).message);return}const g=++generation.current;setBusy(true);setError('');try{const data=await api('/api/operational-reports',{id,filters:f});if(g!==generation.current)return;setReport(data);setPage(1);if(remember)try{await api('/api/report-presets',{report:id,name:'__last__',filters:f})}catch(e){setNotice((e as Error).message)}}catch(e){if(g===generation.current)setError((e as Error).message)}finally{if(g===generation.current)setBusy(false)}}
 useEffect(()=>{let alive=true;setReport(null);setError('');setNotice('');setDraft(defaults(id));setPresets([]);setChosenPreset('');void api('/api/report-presets?report='+id).then(data=>{if(!alive)return;setPresets(data.presets);const f=data.presets.find((p:{name:string})=>p.name==='__last__')?.filters||defaults(id);setDraft(f);void run(f,false)}).catch(e=>{if(alive){setNotice(e.message);void run(defaults(id),false)}});return()=>{alive=false;generation.current++}},[id]);
 useEffect(()=>{if(!document)return;setDetail(null);setDetailError('');const controller=new AbortController();const kind=document._document,url=kind==='purchase'?'/api/purchases?id=':kind==='return'?'/api/sales-returns?id=':kind==='receipt'?'/api/receipts?id=':'';if(!url){setDetail({record:document});return}void api(url+document._documentId,undefined,controller.signal).then(setDetail).catch(e=>{if(!controller.signal.aborted)setDetailError(e.message)});return()=>controller.abort()},[document]);
 function update(p:Partial<Filters>){setDraft(v=>({...v,...p}))}
 function datePreset(value:string){const end=today(),date=new Date(end+'T12:00:00');if(value==='today')update({from:end,to:end});if(value==='month')update({from:end.slice(0,8)+'01',to:end});if(value==='year')update({from:end.slice(0,4)+'-01-01',to:end});if(value==='last-month'){date.setDate(0);const to=date.toISOString().slice(0,10);update({from:to.slice(0,8)+'01',to})}}
 async function savePreset(){if(!presetName.trim()||presetName==='__last__'){setNotice('Enter a name for your preset.');return}try{validateFilters(draft);await api('/api/report-presets',{report:id,name:presetName,filters:draft});const data=await api('/api/report-presets?report='+id);setPresets(data.presets);setNotice('Preset saved.');setPresetName('')}catch(e){setNotice((e as Error).message)}}
 async function removePreset(){if(!chosenPreset)return;try{const r=await fetch('/api/report-presets',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({report:id,name:chosenPreset})});if(!r.ok)throw Error('Preset could not be deleted.');setPresets(p=>p.filter(x=>x.name!==chosenPreset));setChosenPreset('')}catch(e){setNotice((e as Error).message)}}
 async function exportExcel(){if(!report)return;setExporting(true);try{const {operationalWorkbook}=await import('../lib/operational-report-excel');const data=await operationalWorkbook(report);const url=URL.createObjectURL(new Blob([data],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=window.document.createElement('a');a.href=url;a.download=id+'-'+report.filters.to+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setError('Excel export failed. Please retry.')}finally{setExporting(false)}}
 function openDocument(row:ReportRow,e:React.MouseEvent<HTMLButtonElement>){trigger.current=e.currentTarget;if(row._document==='invoice')setInvoiceId(Number(row._documentId));else setDocument(row)}
 const pending=report&&JSON.stringify(draft)!==JSON.stringify(report.filters),ready=!!report&&!busy&&!error;
 function table(rows:ReportRow[],print=false,aggregate=false){if(!report)return null;const columns=aggregate?report.columns.filter(c=>c.sum||rows.some(r=>r[c.key]!==undefined&&!c.numeric)):report.columns;return <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{columns.map(c=><th key={c.key} className={'whitespace-nowrap border-b px-4 py-3 text-left font-semibold '+(c.numeric?'text-right':'')}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r._key??i)} className={r.type==='Opening balance'?'bg-rose-50':'border-b hover:bg-slate-50'}>{columns.map(c=><td key={c.key} className={'px-4 py-3 '+(c.numeric?'text-right tabular-nums whitespace-nowrap':'min-w-28')}>
 {!print&&c.key==='reference'&&r._document&&r.reference?<button className="font-medium text-[#bb3050] underline underline-offset-4" onClick={e=>openDocument(r,e)}>{r.reference}</button>:!print&&c.key==='original'&&r._originalId?<button className="text-[#bb3050] underline" onClick={()=>setInvoiceId(Number(r._originalId))}>{r.original}</button>:display(r[c.key])}</td>)}</tr>)}</tbody></table></div>}
 return <section className="operational-report space-y-4">
 <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">{d.title}</h2><p className="mt-1 text-sm text-slate-600">{report?.companyName} · Effective posted activity</p></div><div className="flex gap-2 report-controls"><Button variant="outline" disabled={!ready||exporting} onClick={()=>void exportExcel()}><Download/>{exporting?'Exporting…':'Excel'}</Button><Button variant="outline" disabled={!ready} onClick={()=>window.print()}><Printer/>Print / PDF</Button></div></header>
 <div className="report-controls rounded-xl border bg-white p-4 shadow-sm"><form onSubmit={e=>{e.preventDefault();void run(draft)}} className="flex flex-wrap items-end gap-3">
 {id!=='price-cost'&&<><label className="grid gap-1 text-sm">{d.asOf?'As of':'To'}<Input type="date" value={draft.to} onChange={e=>update({to:e.target.value,...(d.asOf?{from:e.target.value}:{})})}/></label>{!d.asOf&&<><label className="grid gap-1 text-sm">From<Input type="date" value={draft.from} onChange={e=>update({from:e.target.value})}/></label><label className="grid gap-1 text-sm">Period<select className={selectClass} defaultValue="" onChange={e=>datePreset(e.target.value)}><option value="">Custom range</option><option value="today">Today</option><option value="month">This month</option><option value="last-month">Last month</option><option value="year">This year</option></select></label></>}</>}
 {id!=='price-cost'&&id!=='stock-balance'&&<label className="grid gap-1 text-sm">Document / reference<Input placeholder="Contains…" value={draft.search} onChange={e=>update({search:e.target.value})}/></label>}
 <Button type="submit" disabled={busy}><RefreshCw className={busy?'animate-spin':''}/>Apply</Button><Button type="button" variant="outline" onClick={()=>{const f=defaults(id);setDraft(f);void run(f)}}>Reset</Button><Button type="button" variant="ghost" onClick={()=>setAdvanced(!advanced)} aria-expanded={advanced}><ChevronDown/>Advanced filters</Button>
 </form>
 {advanced&&<div className="mt-4 space-y-4 border-t pt-4"><p className="text-sm text-slate-500">Different filters combine with AND. Selections within one filter combine with OR.</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{d.filters.map(k=><Multi key={k} label={labels[k]||k} values={report?.options[k]||[]} selected={draft.selections[k]||[]} onChange={v=>update({selections:{...draft.selections,[k]:v}})}/>)}</div>{id==='outstanding'&&<div className="flex gap-3"><label className="text-sm">Minimum outstanding<Input type="number" step="any" value={draft.min} onChange={e=>update({min:e.target.value})}/></label><label className="text-sm">Maximum outstanding<Input type="number" step="any" value={draft.max} onChange={e=>update({max:e.target.value})}/></label></div>}
 <div className="flex flex-wrap items-end gap-3">{!['stock-card','stock-balance','price-cost'].includes(id)&&<label className="grid gap-1 text-sm">View<select className={selectClass} value={draft.mode} onChange={e=>update({mode:e.target.value,sort:e.target.value==='summary'?(draft.group||d.groups[0]):'date'})}><option value="detail">Detail</option><option value="summary">Summary</option></select></label>}<label className="grid gap-1 text-sm">Group / subtotals<select className={selectClass} value={draft.group} onChange={e=>update({group:e.target.value})}><option value="">None</option>{d.groups.map(k=><option key={k} value={k}>{labels[k]||k}</option>)}</select></label><label className="grid gap-1 text-sm">Sort<select className={selectClass} value={draft.sort} onChange={e=>update({sort:e.target.value})}>{(report?.columns||d.columns).map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select></label><label className="flex h-9 items-center gap-2 text-sm"><input type="checkbox" checked={draft.descending} onChange={e=>update({descending:e.target.checked})}/>Descending</label></div>
 <div className="flex flex-wrap items-end gap-2 border-t pt-3"><label className="grid gap-1 text-sm">Saved presets<select className={selectClass} value={chosenPreset} onChange={e=>{setChosenPreset(e.target.value);const p=presets.find(p=>p.name===e.target.value);if(p)setDraft(p.filters)}}><option value="">Select preset…</option>{presets.filter(p=>p.name!=='__last__').map(p=><option key={p.name}>{p.name}</option>)}</select></label><Button variant="outline" disabled={!chosenPreset} onClick={()=>void removePreset()}>Delete preset</Button><label className="grid gap-1 text-sm">Preset name<Input value={presetName} onChange={e=>setPresetName(e.target.value)} maxLength={80}/></label><Button variant="outline" onClick={()=>void savePreset()}><Save/>Save preset</Button></div></div>}
 {pending&&<p className="mt-3 text-sm text-amber-800">Filters changed. Apply to refresh the report and exports.</p>}
 {report&&<div className="mt-3 flex flex-wrap gap-2" aria-label="Active filters">{Object.entries(report.filters.selections).flatMap(([key,values])=>values.map(value=><button key={key+value} className="flex items-center gap-1 rounded-full bg-rose-50 px-3 py-1 text-sm text-rose-900" onClick={()=>{const f={...report.filters,selections:{...report.filters.selections,[key]:values.filter(v=>v!==value)}};setDraft(f);void run(f)}}>{labels[key]}: {value}<X size={14}/></button>))}{report.filters.search&&<button className="rounded-full bg-rose-50 px-3 py-1 text-sm" onClick={()=>{const f={...report.filters,search:''};setDraft(f);void run(f)}}>Reference: {report.filters.search} ×</button>}</div>}
 {notice&&<p role="status" className="mt-3 text-sm">{notice}</p>}</div>
 {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>}{busy&&<p role="status" className="rounded-xl border bg-white p-8 text-center">Preparing all matching records…</p>}
 {ready&&report&&<><div className="text-sm text-slate-600"><p>{filterDescription(report.filters)}</p><p className="mt-1">Generated {new Date(report.generatedAt).toLocaleString()} · {report.rows.length.toLocaleString()} rows · Currencies and base units shown separately</p></div>
 <div className="report-screen-table overflow-hidden rounded-xl border bg-white shadow-sm">{report.rows.length?table(report.rows.slice((page-1)*50,page*50)):<p className="p-10 text-center text-slate-500">No posted records match these filters. Adjust the period or reset filters.</p>}<div className="flex items-center justify-between border-t px-4 py-3 text-sm"><span>Page {page} of {Math.max(1,Math.ceil(report.rows.length/50))}</span><div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" disabled={page*50>=report.rows.length} onClick={()=>setPage(page+1)}>Next</Button></div></div></div>
 <div className="report-print-table hidden">{table(report.rows,true)}</div>
 {!!report.subtotals.length&&<details className="rounded-xl border bg-white p-4" open><summary className="cursor-pointer font-semibold">Subtotals</summary>{table(report.subtotals,false,true)}</details>}
 {report.columns.some(c=>c.sum)&&<div className="rounded-xl border bg-white p-4"><h3 className="mb-2 font-semibold">Grand totals · separate currencies and base units</h3>{report.totals.length?table(report.totals,false,true):<p className="text-sm text-slate-500">No totals to display.</p>}</div>}
 <details className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm" open><summary className="cursor-pointer font-semibold">Calculation notes and data prerequisites</summary><ul className="mt-2 list-disc space-y-2 pl-5">{report.warnings.map(w=><li key={w}>{w}</li>)}</ul></details></>}
 <InvoiceDetailDialog invoiceId={invoiceId} onClose={()=>setInvoiceId(null)} onReturnFocus={()=>trigger.current?.focus()}/>
 <Dialog open={!!document} onOpenChange={v=>{if(!v)setDocument(null)}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>{document?.reference}</DialogTitle><DialogDescription>Saved source document details</DialogDescription></DialogHeader>{detailError?<p role="alert">{detailError}</p>:!detail?<p role="status">Loading document…</p>:<DocumentDetails value={detail}/>}</DialogContent></Dialog>
 <style>{`@media print {body:has(.operational-report) aside,body:has(.operational-report) nav,body:has(.operational-report) main>header,.report-controls,.report-screen-table{display:none!important}body:has(.operational-report) main{padding:0!important}.report-print-table{display:block!important}.operational-report table{font-size:9pt}.operational-report th,.operational-report td{padding:5px!important;min-width:0!important;white-space:normal!important;overflow-wrap:anywhere}.operational-report thead{display:table-header-group}.operational-report tr{break-inside:avoid}.operational-report .overflow-x-auto{overflow:visible!important}.operational-report details{break-inside:auto}.operational-report button{color:black}@page{size:landscape;margin:10mm}}`}</style>
 </section>;
}
function DocumentDetails({value}:{value:any}){const allowed=Object.entries(value).filter(([k])=>['purchase','lines','note','savedLines','receipt','allocations','record'].includes(k));return <div className="space-y-5">{allowed.map(([key,val])=><div key={key}><h3 className="mb-2 font-semibold capitalize">{key.replace('savedLines','Return lines')}</h3>{Array.isArray(val)?<div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{val.map((v,i)=><tr key={i} className="border-b"><td className="p-2">{i+1}</td><td className="p-2"><DocumentFields value={v}/></td></tr>)}</tbody></table></div>:<DocumentFields value={val}/>}</div>)}</div>}
function DocumentFields({value}:{value:any}){return <dl className="grid gap-2 text-sm sm:grid-cols-2">{Object.entries(value||{}).filter(([k,v])=>!k.startsWith('_')&&!/token|hash|request_key|requestKey|Json|snapshot|logo|seller_|revision|company_code/i.test(k)&&v!==null&&typeof v!=='object').map(([k,v])=><div key={k} className="rounded border p-2"><dt className="text-slate-500">{k.replaceAll('_',' ').replace(/([a-z])([A-Z])/g,'$1 $2')}</dt><dd className="break-words">{display(v)}</dd></div>)}</dl>}
