"use client";
import {useEffect,useRef,useState,type ReactNode} from 'react';
import type {ItemMaster} from '../lib/item-master';
import ItemPicker,{UnitSelect} from './item-picker';
import {WarehouseSelect} from './warehouses';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Badge} from './ui/badge';
import {invoiceTotals} from '../lib/invoice-totals';
import {conversion,type OrderLine} from '../lib/sales-orders';
import type {Order} from '../db/sales-orders';
import type {CustomerRecord} from './customer-master-dialog';
import type {PriceList} from './price-list-register';
import {toast} from 'sonner';
type Item=ItemMaster&{id:number;sku:string;name:string;salePrice:number;vatRate:number;discountRate:number};
type Invoice={id:number;invoiceNumber:string;documentState:string;total:number;revision:number;currency:string};
type Summary=Order&{status:string;reserved?:number};
type Detail={order:Summary;lines:(OrderLine&{remaining:number})[];invoices:Invoice[];history:{action:string;actor:string;createdAt:string}[]};
type Form={warehouseCode:string;id?:number;revision?:number;state:string;customerId:number;currency:string;paymentTerms:string;orderDate:string;expectedDeliveryDate:string;purchaseOrderNumber:string;notes:string;discountRate:number;lines:OrderLine[]};
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const blankLine=():OrderLine=>({lineType:'labor',itemId:null,description:'',unit:'unit',quantity:1,unitPrice:0,lineDiscountRate:0,taxRate:0});
const money=(n:number,c:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(n||0);
const control='h-10 w-full rounded-md border bg-white px-3 text-sm';
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-1 text-sm font-medium">{label}{children}</label>}
export default function SalesOrders({customers,items,currencies,priceLists,paymentTerms,defaultTax,accounts,initialId=0,onInvoicesChanged}:{customers:CustomerRecord[];items:Item[];currencies:{code:string;active:boolean}[];priceLists:PriceList[];paymentTerms:{code:string;name:string;active:boolean}[];defaultTax:number;accounts:{accountNumber:string;name:string;currency:string;active:boolean}[];initialId?:number;onInvoicesChanged:()=>void}){
 const [orders,setOrders]=useState<Summary[]>([]),[detail,setDetail]=useState<Detail|null>(null),[form,setForm]=useState<Form|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[quantities,setQuantities]=useState<Record<number,string>|null>(null),[invoiceDate,setInvoiceDate]=useState(today()),[all,setAll]=useState(false),[notice,setNotice]=useState<{message:string;body:Record<string,unknown>;url:string;kind:string}|null>(null);
 const [receive,setReceive]=useState(false),[payment,setPayment]=useState({accountNumber:'',paymentMethod:'cash',reference:''});
 const lock=useRef(false),key=useRef('');
 async function api<T=unknown>(url:string,method='GET',body?:unknown){const r=await fetch(url,{method,headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),d=await r.json() as T&{error?:string};if(!r.ok)throw new Error(d.error||'Request failed.');return d}
 async function load(){try{const d=await api<{orders:Summary[]}>('/api/sales-orders');setOrders(d.orders);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 async function open(id:number){try{setDetail(await api<Detail>('/api/sales-orders?id='+id));setForm(null);setQuantities(null);setNotice(null);setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load();if(initialId)void open(initialId)},[initialId]);
 async function run(task:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await task()}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 function start(){key.current=crypto.randomUUID();setDetail(null);setForm({warehouseCode:'MAIN',state:'draft',customerId:0,currency:currencies.find(c=>c.active)?.code||'USD',paymentTerms:'cash',orderDate:today(),expectedDeliveryDate:'',purchaseOrderNumber:'',notes:'',discountRate:0,lines:[blankLine()]})}
 function selectCustomer(id:number){const c=customers.find(c=>c.id===id);if(!form||!c)return;setForm({...form,customerId:id,currency:c.defaultCurrency,paymentTerms:c.paymentTerms,discountRate:c.defaultDiscount,lines:form.lines.map(l=>{const item=items.find(i=>i.id===l.itemId),override=priceLists.find(p=>p.id===c.priceListId)?.items.find(p=>p.itemId===l.itemId);return{...l,...(item?{unitPrice:(override?.price??item.salePrice)*(item.units.find(u=>u.code===l.unit)?.factor??1)}:{}),taxRate:c.vatTreatment==='standard'?(item?.vatRate??defaultTax):0}})})}
 function changeLine(index:number,patch:Partial<OrderLine>){if(form)setForm({...form,lines:form.lines.map((l,i)=>i===index?{...l,...patch}:l)})}
 function selectItem(index:number,id:number,selectedUnit?:string){const item=items.find(i=>i.id===id),customer=customers.find(c=>c.id===form?.customerId),override=priceLists.find(p=>p.id===customer?.priceListId)?.items.find(p=>p.itemId===id);changeLine(index,item?{lineType:'part',itemId:id,description:item.name,unit:selectedUnit||item.salesUnit,unitFactor:item.units.find(u=>u.code===(selectedUnit||item.salesUnit))?.factor??1,unitPrice:(override?.price??item.salePrice)*(item.units.find(u=>u.code===(selectedUnit||item.salesUnit))?.factor??1),lineDiscountRate:item.discountRate,taxRate:customer?.vatTreatment==='standard'?item.vatRate:0}:{lineType:'labor',itemId:null,description:'',unitPrice:0,lineDiscountRate:0,taxRate:customer?.vatTreatment==='standard'?defaultTax:0})}
 async function save(){if(!form)return;await run(async()=>{const d=await api<{order:{id:number}}>('/api/sales-orders',form.id?'PUT':'POST',{...form,requestKey:key.current});await open(d.order.id);await load();toast.success('Sales order saved')})}
 async function action(action:string,invoiceId?:number){if(!detail)return;await run(async()=>{await api('/api/sales-orders','PATCH',{id:detail.order.id,revision:detail.order.revision,action,invoiceId});await open(detail.order.id);await load();onInvoicesChanged()})}
 function convert(useAll:boolean){if(!detail)return;setAll(useAll);setQuantities(Object.fromEntries(detail.lines.map(l=>[l.id!,useAll&&l.remaining>0?String(l.remaining):''])));setInvoiceDate(today());key.current=crypto.randomUUID();setNotice(null)}
 async function submitInvoice(body:Record<string,unknown>,url='/api/invoices'){await run(async()=>{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,...(receive&&body.action!=='draft'?{receivePayment:payment}:{})})}),d=await r.json() as {error?:string;requiresConfirmation?:boolean;confirmationType?:string};if(!r.ok){if(d.requiresConfirmation){setNotice({message:d.error||'Confirmation required',body,url,kind:d.confirmationType==='stock'?'stockWarningAcknowledged':'creditLimitConfirmed'});return}throw new Error(d.error||'Could not create invoice.')}setNotice(null);toast.success('Invoice saved');await open(detail!.order.id);await load();onInvoicesChanged()})}
 function createInvoice(draft:boolean){if(!detail||!quantities)return;const selected=Object.entries(quantities).filter(([,q])=>q!=='').map(([id,q])=>({id:Number(id),quantity:Number(q)}));try{conversion(detail.lines,detail.order.discountRate,selected)}catch(e){setError((e as Error).message);return}void submitInvoice({salesOrderId:detail.order.id,orderRevision:detail.order.revision,invoiceAllRemaining:all,orderLines:selected,invoiceDate,action:draft?'draft':'post',requestKey:key.current})}
 const totals=form?invoiceTotals(form.lines,form.discountRate):detail?invoiceTotals(detail.lines,detail.order.discountRate):null,currency=form?.currency??detail?.order.currency??'USD';
 let preview:ReturnType<typeof invoiceTotals>|null=null;try{if(detail&&quantities){const selected=conversion(detail.lines,detail.order.discountRate,Object.entries(quantities).filter(([,q])=>q!=='').map(([id,q])=>({id:Number(id),quantity:Number(q)})));preview=invoiceTotals(selected,detail.order.discountRate,selected.map(l=>l.orderDiscount))}}catch{}
 function totalBlock(t:ReturnType<typeof invoiceTotals>){return <dl className="ml-auto grid max-w-sm grid-cols-2 gap-2 rounded-xl bg-slate-50 p-4 text-sm"><dt>Subtotal</dt><dd className="text-right">{money(t.grossSubtotal,currency)}</dd><dt>Line discounts</dt><dd className="text-right">−{money(t.lineDiscountTotal,currency)}</dd><dt>Order discount</dt><dd className="text-right">−{money(t.discountAmount,currency)}</dd><dt>VAT</dt><dd className="text-right">{money(t.tax,currency)}</dd><dt className="font-bold">Grand total</dt><dd className="text-right font-bold">{money(t.total,currency)}</dd></dl>}
 return <section className="space-y-5">
 {error&&<div role="alert" className="rounded-lg border border-rose-300 bg-rose-50 p-4 text-rose-800">{error}<Button variant="ghost" onClick={()=>{void load();if(detail)void open(detail.order.id)}}>Refresh</Button></div>}
 {notice&&<div role="alert" className="space-y-3 rounded-lg border border-amber-300 bg-amber-50 p-4"><p>{notice.message}</p><Button disabled={busy} onClick={()=>void submitInvoice({...notice.body,[notice.kind]:true},notice.url)}>Acknowledge and continue</Button><Button variant="ghost" onClick={()=>setNotice(null)}>Back</Button></div>}
 <div className="flex flex-wrap items-center justify-between gap-3">{(detail||form)?<Button variant="outline" disabled={busy} onClick={()=>{setDetail(null);setForm(null);setQuantities(null);setNotice(null)}}>← Sales Orders</Button>:<p className="text-sm text-slate-500">{orders.length} sales orders</p>}{!form&&!detail&&<Button onClick={start} className="bg-[#ef4e6f] text-white">New sales order</Button>}</div>
 {form?<form onSubmit={e=>{e.preventDefault();void save()}} className="space-y-5 rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">{form.id?'Edit sales order':'New sales order'}</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
 <Field label="Customer"><select required className={control} value={form.customerId||''} onChange={e=>selectCustomer(Number(e.target.value))}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></Field>
 <Field label="Order date"><Input required type="date" value={form.orderDate} onChange={e=>setForm({...form,orderDate:e.target.value})}/></Field><Field label="Expected delivery"><Input type="date" min={form.orderDate} value={form.expectedDeliveryDate} onChange={e=>setForm({...form,expectedDeliveryDate:e.target.value})}/></Field>
 <Field label="Warehouse"><WarehouseSelect value={form.warehouseCode} onChange={warehouseCode=>setForm({...form,warehouseCode})}/></Field><Field label="Currency"><select className={control} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{currencies.filter(c=>c.active).map(c=><option key={c.code}>{c.code}</option>)}</select></Field><Field label="Payment terms"><select className={control} value={form.paymentTerms} onChange={e=>setForm({...form,paymentTerms:e.target.value})}>{paymentTerms.filter(t=>t.active||t.code===form.paymentTerms).map(t=><option key={t.code} value={t.code}>{t.name}</option>)}</select></Field><Field label="Customer PO number"><Input value={form.purchaseOrderNumber} onChange={e=>setForm({...form,purchaseOrderNumber:e.target.value})}/></Field></div>
 <div className="space-y-3">{form.lines.map((line,i)=><fieldset key={i} className="rounded-lg border p-4"><legend className="px-2 text-sm font-semibold">Line {i+1}</legend><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Product / service"><ItemPicker items={items} value={line.itemId} onSelect={(item,unit)=>selectItem(i,item?.id??0,unit)}/></Field><Field label="Description"><Input required value={line.description} onChange={e=>changeLine(i,{description:e.target.value})}/></Field><Field label="Quantity"><Input required type="number" min="0.000000001" step="any" value={line.quantity} onChange={e=>changeLine(i,{quantity:Number(e.target.value)})}/></Field><Field label="Unit">{line.itemId?<UnitSelect item={items.find(v=>v.id===line.itemId)} value={line.unit} onChange={(unit,factor,old)=>changeLine(i,{unit,unitFactor:factor,unitPrice:Number((line.unitPrice*factor/old).toFixed(4))})}/>:<Input required value={line.unit} onChange={e=>changeLine(i,{unit:e.target.value})}/>}</Field><Field label="Unit price"><Input required type="number" min="0" step="any" value={line.unitPrice} onChange={e=>changeLine(i,{unitPrice:Number(e.target.value)})}/></Field><Field label="Discount %"><Input required type="number" min="0" max="100" step="any" value={line.lineDiscountRate} onChange={e=>changeLine(i,{lineDiscountRate:Number(e.target.value)})}/></Field><Field label="VAT %"><Input required type="number" min="0" max="100" step="any" value={line.taxRate} onChange={e=>changeLine(i,{taxRate:Number(e.target.value)})}/></Field><div className="flex items-end justify-between gap-2"><strong>{money(totals!.lines[i].total,form.currency)}</strong><Button type="button" variant="ghost" disabled={form.lines.length===1} onClick={()=>setForm({...form,lines:form.lines.filter((_,n)=>n!==i)})}>Remove</Button></div></div></fieldset>)}</div>
 <Button type="button" variant="outline" onClick={()=>setForm({...form,lines:[...form.lines,blankLine()]})}>Add line</Button><div className="grid gap-4 sm:grid-cols-2"><Field label="Order discount %"><Input type="number" min="0" max="100" step="any" value={form.discountRate} onChange={e=>setForm({...form,discountRate:Number(e.target.value)})}/></Field><Field label="Notes"><textarea className={control+' min-h-20'} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div>{totals&&totalBlock(totals)}<Button disabled={busy} type="submit">{busy?'Saving…':'Save '+(form.state==='draft'?'draft':'changes')}</Button></form>
 :detail?<div className="space-y-5"><div className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold">{detail.order.orderNumber}<span className="ml-3 text-sm font-normal">Warehouse: {detail.order.warehouseCode}</span></h2><Badge variant="outline">{detail.order.status}</Badge></div><div className="my-4 grid gap-3 text-sm sm:grid-cols-3"><p><strong>{detail.order.customerName}</strong><br/>{detail.order.currency} · {detail.order.paymentTerms.replaceAll('_',' ')}</p><p>Order date: {detail.order.orderDate}<br/>Expected delivery: {detail.order.expectedDeliveryDate||'—'}</p><p>Customer PO: {detail.order.purchaseOrderNumber||'—'}</p></div><div className="flex flex-wrap gap-2">{detail.order.state!=='cancelled'&&!detail.invoices.length&&<Button variant="outline" disabled={busy} onClick={()=>{key.current=crypto.randomUUID();setForm({...detail.order,lines:detail.lines})}}>Edit order</Button>}{detail.order.state==='draft'&&<Button disabled={busy} onClick={()=>void action('confirm')}>Confirm order</Button>}{detail.order.state==='confirmed'&&detail.lines.some(l=>l.remaining>0)&&<><Button disabled={busy} onClick={()=>convert(true)}>Create Invoice · All Remaining</Button><Button variant="outline" disabled={busy} onClick={()=>convert(false)}>Partial Invoice</Button></>}{detail.order.state!=='cancelled'&&detail.order.status!=='Fully Invoiced'&&<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Cancel all remaining uninvoiced quantities? Existing invoices and history will be preserved.'))void action('cancel')}}>Cancel remaining</Button>}</div></div>
 {quantities&&<div className="space-y-4 rounded-xl border border-rose-200 bg-white p-5"><h3 className="text-lg font-bold">{all?'Invoice all remaining':'Partial invoice'}</h3><p className="text-sm text-slate-500">Draft invoices reserve quantities. Posting invoices records the sale and updates stock.</p><Field label="Invoice date"><Input className="max-w-xs" type="date" value={invoiceDate} onChange={e=>setInvoiceDate(e.target.value)}/></Field><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Select','Description','Ordered','Invoiced','Reserved','Remaining','Quantity to invoice'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{detail.lines.map(l=><tr key={l.id} className="border-t"><td className="p-3"><input aria-label={'Select '+l.description} type="checkbox" disabled={all||!l.remaining} checked={quantities[l.id!]!==''} onChange={e=>setQuantities({...quantities,[l.id!]:e.target.checked?String(l.remaining):''})}/></td><td className="p-3">{l.description}</td><td className="p-3">{l.quantity}</td><td className="p-3">{l.invoiced}</td><td className="p-3">{l.reserved}</td><td className="p-3">{l.remaining}</td><td className="p-3"><Input aria-label={'Quantity to invoice '+l.description} type="number" step="any" min="0.000000001" max={l.remaining} disabled={all||quantities[l.id!]===''} value={quantities[l.id!]} onChange={e=>setQuantities({...quantities,[l.id!]:e.target.value})}/></td></tr>)}</tbody></table></div>{preview&&totalBlock(preview)}<div className="flex flex-wrap gap-2"><Button disabled={busy||!preview} onClick={()=>createInvoice(false)}>Create and post invoice</Button><Button variant="outline" disabled={busy||!preview} onClick={()=>createInvoice(true)}>Save invoice draft</Button><Button variant="ghost" disabled={busy} onClick={()=>{setQuantities(null);setNotice(null)}}>Cancel</Button></div></div>}
 <div className="rounded-xl border bg-white p-5"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Description','Ordered / unit','Price','Discount %','VAT %','Total','Invoiced','Reserved','Remaining'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{detail.lines.map((l,i)=><tr key={l.id} className="border-t"><td className="p-3">{l.description}</td><td className="p-3">{l.quantity} {l.unit}</td><td className="p-3">{money(l.unitPrice,currency)}</td><td className="p-3">{l.lineDiscountRate}</td><td className="p-3">{l.taxRate}</td><td className="p-3">{money(totals!.lines[i].total,currency)}</td><td className="p-3">{l.invoiced}</td><td className="p-3">{l.reserved}</td><td className="p-3">{detail.order.state==='cancelled'?'Cancelled: '+l.remaining:l.remaining}</td></tr>)}</tbody></table></div>{totals&&totalBlock(totals)}{detail.order.notes&&<p className="mt-4 whitespace-pre-wrap text-sm">{detail.order.notes}</p>}</div>
 <div className="space-y-3 rounded-xl border bg-white p-5"><h3 className="font-bold">Invoice payment</h3><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={receive} onChange={e=>setReceive(e.target.checked)}/>Receive full payment when posting</label>{receive&&<div className="grid gap-3 sm:grid-cols-3"><Field label="Payment account"><select className={control} value={payment.accountNumber} onChange={e=>setPayment({...payment,accountNumber:e.target.value})}><option value="">Select account</option>{accounts.filter(a=>a.active&&/^[0-9]{10}$/.test(a.accountNumber)&&a.currency===currency).map(a=><option key={a.accountNumber} value={a.accountNumber}>{a.accountNumber} · {a.name}</option>)}</select></Field><Field label="Payment method"><select className={control} value={payment.paymentMethod} onChange={e=>setPayment({...payment,paymentMethod:e.target.value})}>{['cash','card','bank_transfer','check','other'].map(m=><option key={m} value={m}>{m.replaceAll('_',' ')}</option>)}</select></Field><Field label="Payment reference"><Input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></Field></div>}</div><div className="space-y-3 rounded-xl border bg-white p-5"><h3 className="font-bold">Linked invoices</h3>{!detail.invoices.length?<p className="text-sm text-slate-500">No invoices created.</p>:detail.invoices.map(i=><div key={i.id} className="flex flex-wrap items-center gap-3 border-t py-3"><a className="font-semibold text-[#a91f40] underline" href={'/invoice-print?id='+i.id} target="_blank" rel="noreferrer">{i.invoiceNumber}</a><Badge variant="outline">{i.documentState}</Badge><span>{money(i.total,i.currency)}</span>{i.documentState==='draft'&&<><Button size="sm" disabled={busy} onClick={()=>void submitInvoice({id:i.id,revision:i.revision,requestKey:crypto.randomUUID()},'/api/invoices/post')}>Post invoice</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Cancel this draft and release its reserved quantities?'))void action('cancelDraft',i.id)}}>Cancel draft</Button></>}</div>)}<p className="text-sm text-slate-500">Posted invoice returns remain in invoice history and do not reopen order quantities. Create a new order for replacement sales.</p></div><details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-semibold">Order history</summary>{detail.history.map((h,i)=><p key={i} className="mt-2 text-sm">{h.createdAt} · {h.action} · {h.actor}</p>)}</details></div>
 :<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Search order or customer"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Order number or customer"/></Field><Field label="Status"><select className={control} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['Draft','Confirmed','Partially Invoiced','Fully Invoiced','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Order date from"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Order date to"><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field></div><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr>{['Order','Customer','Order date','Expected delivery','Status','Total'].map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{orders.filter(o=>(o.orderNumber+' '+o.customerName).toLowerCase().includes(query.toLowerCase())&&(!status||o.status===status)&&(!from||o.orderDate>=from)&&(!to||o.orderDate<=to)).map(o=><tr key={o.id} className="border-t"><td className="p-4"><button className="font-semibold text-[#a91f40] underline" onClick={()=>void open(o.id)}>{o.orderNumber}</button></td><td className="p-4">{o.customerName}</td><td className="p-4">{o.orderDate}</td><td className="p-4">{o.expectedDeliveryDate||'—'}</td><td className="p-4"><Badge variant="outline">{o.status}</Badge>{!!o.reserved&&<small className="block text-slate-500">Draft quantities reserved</small>}</td><td className="p-4">{money(o.total,o.currency)}</td></tr>)}</tbody></table>{loading?<p className="p-6">Loading sales orders…</p>:!orders.length?<p className="p-6 text-slate-500">No sales orders yet. Create your first order.</p>:null}</div></>}
 </section>
}
