"use client";
import { FormEvent, useState } from "react";
import { Edit3, Plus, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
export type Salesman={id:number;code:string;name:string;phone:string;email:string;active:boolean;notes:string};
const blank:Salesman={id:0,code:"",name:"",phone:"",email:"",active:true,notes:""};
export default function SalesmanRegister({data,query,onSaved}:{data:Salesman[];query:string;onSaved:()=>void}){
 const[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(blank),filtered=data.filter(value=>`${value.code} ${value.name} ${value.phone} ${value.email}`.toLowerCase().includes(query.toLowerCase()));
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);try{const response=await fetch("/api/salesmen",{method:form.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),result=await response.json() as{error?:string};if(!response.ok)throw new Error(result.error);toast.success(form.id?"Salesman updated":"Salesman added");setOpen(false);onSaved()}catch(error){toast.error(error instanceof Error?error.message:"Could not save salesman.")}finally{setSaving(false)}}
 return <><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between gap-3 border-b p-5"><div><h2 className="font-bold">Salesman master data</h2><p className="text-sm text-slate-500">Sales representatives assigned to customers.</p></div><Button onClick={()=>{setForm(blank);setOpen(true)}}><Plus/>Add salesman</Button></div>{filtered.length?<Table><TableHeader><TableRow><TableHead>Code</TableHead><TableHead>Name</TableHead><TableHead>Phone</TableHead><TableHead>Email</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{filtered.map(value=><TableRow key={value.id}><TableCell className="font-mono font-semibold">{value.code}</TableCell><TableCell>{value.name}</TableCell><TableCell>{value.phone||"—"}</TableCell><TableCell>{value.email||"—"}</TableCell><TableCell>{value.active?"Active":"Inactive"}</TableCell><TableCell><Button size="icon-sm" variant="ghost" onClick={()=>{setForm({...value});setOpen(true)}}><Edit3/></Button></TableCell></TableRow>)}</TableBody></Table>:<div className="grid min-h-72 place-items-center text-center text-slate-500"><div><UserRound className="mx-auto mb-3 size-10"/><p>No salesmen found.</p></div></div>}</section><Dialog open={open} onOpenChange={value=>{if(!saving)setOpen(value)}}><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>{form.id?"Edit salesman":"Add salesman"}</DialogTitle><DialogDescription>Save the representative used on customer records.</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><Field label="Code"><Input required maxLength={40} value={form.code} onChange={event=>setForm({...form,code:event.target.value.toUpperCase()})}/></Field><Field label="Name"><Input required maxLength={200} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></Field><div className="grid grid-cols-2 gap-4"><Field label="Phone"><Input maxLength={100} value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></Field><Field label="Email"><Input type="email" maxLength={320} value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></Field></div><Field label="Notes"><Textarea rows={3} maxLength={2000} value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></Field><div className="flex items-center gap-3"><Switch checked={form.active} onCheckedChange={active=>setForm({...form,active})}/><Label>Active</Label></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving}>{saving?"Saving…":"Save salesman"}</Button></DialogFooter></form></DialogContent></Dialog></>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="grid gap-1.5"><Label>{label}</Label>{children}</div>}
