"use client";
import {useEffect,useRef,useState} from 'react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Label} from './ui/label';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from './ui/table';
import {Badge} from './ui/badge';
import {toast} from 'sonner';
import {returnAmounts,money,type ReturnLine} from '../lib/sales-returns';

type Note={id:number;workflow:string;document_state:string;credit_number:string;draft_number:string;original_invoice_id:number;customer_id:number;customer_name:string;invoice_number:string;credit_date:string;currency:string;currency_rate:number;subtotal:number;tax:number;total:number;reason:string;notes:string;revision:number;created_by:string;posted_by:string;posted_at:string;seller_company_name:string;seller_company_address:string};
type Saved={original_invoice_line_id:number;quantity_returned:number;gross_amount:number;line_discount_amount:number;invoice_discount_amount:number;subtotal:number;tax:number;total:number};
type Source={invoice:Record<string,unknown>;lines:ReturnLine[];note?:Note;savedLines?:Saved[]};
type Invoice={hasReturnable?:number;id:number;customerId:number;invoiceNumber:string;documentState:string};
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
async function api<T>(url:string,method='GET',body?:unknown):Promise<T>{const r=await fetch(url,{method,headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),d=await r.json() as T & {error?:string};if(!r.ok)throw new Error(d.error||'Request failed.');return d}
const selectClass='h-10 w-full rounded-md border bg-white px-3 text-sm disabled:bg-slate-50';
export default function SalesReturns({customers,invoices,initialInvoiceId=0,onSaved,printId=0}:{customers:{id:number;name:string}[];invoices:Invoice[];initialInvoiceId?:number;onSaved:()=>void;printId?:number}){
 const [list,setList]=useState<Note[]>([]),[source,setSource]=useState<Source|null>(null),[note,setNote]=useState<Note|null>(null),[open,setOpen]=useState(!!initialInvoiceId||!!printId),[customerId,setCustomerId]=useState(0),[invoiceId,setInvoiceId]=useState(0),[date,setDate]=useState(today()),[reason,setReason]=useState(''),[notes,setNotes]=useState(''),[quantities,setQuantities]=useState<Record<number,number>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('');
 const generation=useRef(0),saveKey=useRef(''),postKey=useRef('');
 const readonly=!!printId||!!note&&(note.document_state!=='draft'||note.workflow!=='sales_return');
 const currency=String(source?.invoice.currency??note?.currency??'USD');
 const fmt=(n:number)=>`${Number(n||0).toFixed(2)} ${currency}`;
 const draft=!note||note.document_state==='draft';
 async function loadList(){const d=await api<{notes:Note[]}>('/api/sales-returns');setList(d.notes)}
 function reset(){generation.current++;setSource(null);setNote(null);setCustomerId(0);setInvoiceId(0);setDate(today());setReason('');setNotes('');setQuantities({});setError('');saveKey.current='';postKey.current='';setOpen(true)}
 function fill(d:Source){setSource(d);setInvoiceId(Number(d.invoice.id));setCustomerId(Number(d.invoice.customer_id));setNote(d.note??null);setQuantities(Object.fromEntries(d.lines.map(l=>[l.id,d.savedLines?.find(s=>s.original_invoice_line_id===l.id)?.quantity_returned??0])));if(d.note){setDate(d.note.credit_date);setReason(d.note.reason);setNotes(d.note.notes)}saveKey.current='';postKey.current=''}
 async function selectInvoice(id:number){const g=++generation.current;setInvoiceId(id);setSource(null);setQuantities({});setError('');if(!id)return;setBusy(true);try{const d=await api<Source>('/api/sales-returns?invoiceId='+id);if(g===generation.current)fill(d)}catch(e){setError((e as Error).message)}finally{if(g===generation.current)setBusy(false)}}
 async function view(id:number){setOpen(true);setBusy(true);setError('');try{fill(await api<Source>('/api/sales-returns?id='+id))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(printId){void view(printId);return}void loadList().catch(e=>setError(e.message));if(initialInvoiceId)void selectInvoice(initialInvoiceId)},[]);
 const rows=(source?.lines??[]).map(line=>{const qty=quantities[line.id]??0,saved=source?.savedLines?.find(s=>s.original_invoice_line_id===line.id);return {line,qty,amounts:readonly&&saved?{gross:saved.gross_amount,lineDiscount:saved.line_discount_amount,invoiceDiscount:saved.invoice_discount_amount,subtotal:saved.subtotal,tax:saved.tax,total:saved.total}:returnAmounts(line,qty)}});
 const totals=rows.reduce((a,r)=>({gross:money(a.gross+r.amounts.gross),discount:money(a.discount+r.amounts.lineDiscount+r.amounts.invoiceDiscount),subtotal:money(a.subtotal+r.amounts.subtotal),tax:money(a.tax+r.amounts.tax),total:money(a.total+r.amounts.total)}),{gross:0,discount:0,subtotal:0,tax:0,total:0});
 function changed(){saveKey.current='';postKey.current=''}
 async function save(post=false){setBusy(true);setError('');try{saveKey.current||=crypto.randomUUID();const d=await api<{note:Note}>('/api/sales-returns',note?'PUT':'POST',{id:note?.id,revision:note?.revision,customerId,originalInvoiceId:invoiceId,returnDate:date,reason,notes,lines:rows.map(r=>({originalInvoiceLineId:r.line.id,quantity:r.qty})),requestKey:saveKey.current});setNote(d.note);saveKey.current="";if(post){postKey.current||=crypto.randomUUID();await api('/api/sales-returns/post','POST',{id:d.note.id,revision:d.note.revision,requestKey:postKey.current})}await view(d.note.id);await loadList();onSaved();toast.success(post?'Sales return posted':'Return draft saved; quantities reserved')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function cancel(){if(!note)return;setBusy(true);try{await api('/api/sales-returns','DELETE',{id:note.id,revision:note.revision});setOpen(false);setSource(null);setNote(null);await loadList();onSaved();toast.success('Draft cancelled; quantities released')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="space-y-4 sales-return-screen">
 {error&&<div role="alert" className="rounded-lg border border-red-300 bg-red-50 p-4 text-red-800">{error}</div>}
 {!open?<><div className="flex flex-wrap items-center justify-between gap-3"><Input className="max-w-sm" aria-label="Search returns" placeholder="Search return, invoice or customer" value={filter} onChange={e=>setFilter(e.target.value)}/><Button onClick={reset}>New return</Button></div><div className="overflow-x-auto rounded-xl border bg-white"><Table><TableHeader><TableRow>{['Return / credit','Date','Customer','Original invoice','Status','Total',''].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{list.filter(n=>`${n.credit_number} ${n.invoice_number} ${n.customer_name}`.toLowerCase().includes(filter.toLowerCase())).map(n=><TableRow key={n.id}><TableCell className="font-mono">{n.credit_number}{n.workflow==='legacy'&&<span className="block font-sans text-sm text-slate-500">Legacy credit / reversal</span>}</TableCell><TableCell>{n.credit_date}</TableCell><TableCell>{n.customer_name}</TableCell><TableCell>{n.invoice_number}</TableCell><TableCell className="capitalize">{n.document_state}</TableCell><TableCell>{n.total.toFixed(2)} {n.currency}</TableCell><TableCell><Button variant="outline" onClick={()=>void view(n.id)}>Open</Button></TableCell></TableRow>)}</TableBody></Table>{!list.length&&<p className="p-8 text-center text-slate-500">No sales returns yet.</p>}</div></>:<div className="rounded-xl border bg-white shadow-sm">
 <header className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="text-2xl font-bold">{note?.workflow==='legacy'?'Legacy credit / reversal':'Sales Return'}</h2><p className="mt-1 font-mono">{note?.credit_number??'New return'} <Badge variant="outline" className="ml-3 capitalize">{note?.document_state??'Draft'}</Badge></p></div><div className="flex gap-2 print:hidden">{note&&!printId&&<Button variant="outline" disabled={busy} onClick={()=>void view(note.id)}>Reload saved return</Button>}{note&&<Button variant="outline" onClick={()=>printId?window.print():window.open('/sales-return-print?id='+note.id,'_blank','noopener,noreferrer')}>Print</Button>}{!printId&&<Button variant="outline" disabled={busy} onClick={()=>{setOpen(false);setError('');void loadList()}}>Back to returns</Button>}</div></header>
 <div className="space-y-5 p-5"><p className="text-sm text-slate-600">Return warehouse: {String(source?.invoice.warehouse_code??'MAIN')} · Stock returns to the original sale warehouse.</p>
 {!!printId&&<div><strong>{String(source?.invoice.seller_company_name??'')}</strong><p>{String(source?.invoice.seller_company_address??'')}</p></div>}
 <div className="grid gap-4 md:grid-cols-3"><div><Label htmlFor="return-date">Return date</Label>{printId?<p className="pt-2">{date}</p>:<Input id="return-date" type="date" disabled={readonly||busy} value={date} onChange={e=>{setDate(e.target.value);changed()}}/>}</div><div><Label htmlFor="return-customer">Customer</Label>{note?<p className="pt-2">{note.customer_name??String(source?.invoice.customer_name??'')}</p>:<select id="return-customer" className={selectClass} disabled={busy||readonly} value={customerId} onChange={e=>{generation.current++;setCustomerId(Number(e.target.value));setInvoiceId(0);setSource(null);setQuantities({});changed()}}><option value="0">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}</div><div><Label htmlFor="return-invoice">Original invoice</Label>{note?<a className="block pt-2 underline" href={'/invoice-print?id='+invoiceId} target="_blank" rel="noreferrer">{String(source?.invoice.invoice_number??'')}</a>:<select id="return-invoice" className={selectClass} disabled={!customerId||busy||readonly} value={invoiceId} onChange={e=>void selectInvoice(Number(e.target.value))}><option value="0">Select posted invoice</option>{invoices.filter(i=>i.customerId===customerId&&i.documentState==='posted'&&i.hasReturnable!==0).map(i=><option key={i.id} value={i.id}>{i.invoiceNumber}</option>)}</select>}</div></div>
 {source&&<p className="text-sm text-slate-600">Original currency: {currency} · Exchange rate: {String(source.invoice.currency_rate)} {String(source.invoice.local_currency)}. Prices, discounts and VAT are taken from the original invoice.</p>}
 <div className="grid gap-4 md:grid-cols-2"><div><Label htmlFor="return-reason">Reason</Label>{printId?<p className="pt-2 whitespace-pre-wrap">{reason}</p>:<Input id="return-reason" disabled={readonly||busy} value={reason} onChange={e=>{setReason(e.target.value);changed()}} maxLength={2000}/>}</div><div><Label htmlFor="return-notes">Notes</Label>{printId?<p className="pt-2 whitespace-pre-wrap">{notes||"—"}</p>:<Input id="return-notes" disabled={readonly||busy} value={notes} onChange={e=>{setNotes(e.target.value);changed()}} maxLength={10000}/>}</div></div>
 {!readonly&&source&&<div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-slate-500">Enter positive quantities. Saving reserves them; stock and accounting change only when posted.</p><Button variant="outline" disabled={busy} onClick={()=>{setQuantities(Object.fromEntries(source.lines.map(l=>[l.id,l.remaining])));changed()}}>Return all remaining quantities</Button></div>}
 <div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow>{['Item / service','Original qty','Previously returned','Reserved in other drafts','Remaining returnable','Return qty','Original unit price','Discount','VAT','Total'].filter((_,i)=>!printId||i<1||i>4).map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.filter(r=>!readonly||r.qty>0||r.amounts.total>0).map(({line,qty,amounts})=><TableRow key={line.id}><TableCell className="min-w-48 whitespace-normal"><strong>{line.description}</strong><small className="block text-sm text-slate-500">{line.lineType==='part'?'Stock item':'Service · no stock movement'} · {line.unit||'unit'}</small>{!!line.legacyBlocked&&!readonly&&<small className="block text-sm text-amber-800">Unavailable: legacy credit or historical values require reconciliation.</small>}</TableCell>{!printId&&<><TableCell>{line.quantity}</TableCell><TableCell>{line.returned}</TableCell><TableCell>{line.reserved}</TableCell><TableCell>{note?.document_state==='posted'?Math.max(0,line.remaining-qty):line.remaining}</TableCell></>}<TableCell>{readonly?qty:<Input aria-label={'Return quantity for '+line.description} className="w-28" type="number" min="0" max={line.remaining} step="any" disabled={busy||!line.remaining} value={qty} onChange={e=>{setQuantities(v=>({...v,[line.id]:Number(e.target.value)}));changed()}}/>}</TableCell><TableCell>{fmt(line.unitPrice)}</TableCell><TableCell><span>{fmt(amounts.lineDiscount+amounts.invoiceDiscount)}</span><small className="block text-sm text-slate-500">Original: {fmt(line.lineDiscountAmount+line.discountAmount)}</small><small className="block text-sm text-slate-500">Invoice: {fmt(amounts.invoiceDiscount)}</small></TableCell><TableCell>{fmt(amounts.tax)}<small className="block text-sm text-slate-500">{line.taxRate}%</small></TableCell><TableCell className="font-semibold">{fmt(amounts.total)}</TableCell></TableRow>)}</TableBody></Table></div>
 {source&&<><div className="ml-auto max-w-sm space-y-2 rounded-lg bg-slate-50 p-4">{[['Gross',totals.gross],['Discount',totals.discount],['Net',readonly?note?.subtotal??totals.subtotal:totals.subtotal],['VAT',readonly?note?.tax??totals.tax:totals.tax],['Customer credit',readonly?note?.total??totals.total:totals.total]].map(([label,value])=><div className="flex justify-between gap-6" key={label}><span>{label}</span><strong>{fmt(Number(value))}</strong></div>)}</div><p className="text-sm text-slate-500">Physical items restore only quantities recorded as issued by the original sale. Historical issue costs may be unavailable. Paid invoices create customer credit; receipts remain unchanged.</p></>}
 {note&&<p className="text-sm text-slate-500">Created by {note.created_by}{note.posted_at?` · Posted by ${note.posted_by} on ${note.posted_at}`:''}</p>}
 {busy&&<p role="status">Working…</p>}
 </div>{!readonly&&draft&&<footer className="flex flex-wrap justify-end gap-3 border-t p-5 print:hidden">{note&&<Button variant="destructive" disabled={busy} onClick={()=>void cancel()}>Cancel draft</Button>}<Button variant="outline" disabled={busy||!source} onClick={()=>void save(false)}>Save draft</Button><Button disabled={busy||!source} onClick={()=>void save(true)}>Save and post return</Button></footer>}
 </div>}
 </section>
}
