"use client";

import { FormEvent, useState } from "react";
import { Edit3, Plus, Truck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";

export type Supplier = { id:number;code:string;accountNumber:string;name:string;mofNumber:string;phone:string;email:string;address:string };
const blank:Supplier={id:0,code:"",accountNumber:"",name:"",mofNumber:"",phone:"",email:"",address:""};

export default function SupplierRegister({data,query,onSaved}:{data:Supplier[];query:string;onSaved:()=>void}){
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(blank);
 const filtered=data.filter(supplier=>`${supplier.code} ${supplier.accountNumber} ${supplier.name} ${supplier.mofNumber} ${supplier.phone} ${supplier.email} ${supplier.address}`.toLowerCase().includes(query.toLowerCase()));
 function add(){setForm(blank);setOpen(true)}
 function edit(supplier:Supplier){setForm({...supplier});setOpen(true)}
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);try{const response=await fetch("/api/suppliers",{method:form.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error);toast.success(form.id?"Supplier updated":"Supplier added");setOpen(false);onSaved()}catch(error){toast.error(error instanceof Error?error.message:"Could not save supplier")}finally{setSaving(false)}}
 return <>
  <section className="overflow-hidden rounded-2xl border border-[#eadfe1] bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><h2 className="font-bold">Supplier master data</h2><p className="text-sm text-slate-500">Codes and contact details used on purchase invoices.</p></div><Button onClick={add} className="bg-[#ef4e6f] hover:bg-[#c93454]"><Plus/>Add supplier</Button></div>{filtered.length?<Table><TableHeader><TableRow><TableHead>Code</TableHead><TableHead>Account no.</TableHead><TableHead>Supplier</TableHead><TableHead>MOF number</TableHead><TableHead>Phone</TableHead><TableHead>Email</TableHead><TableHead>Address</TableHead><TableHead/></TableRow></TableHeader><TableBody>{filtered.map(supplier=><TableRow key={supplier.id}><TableCell className="font-mono text-xs font-semibold">{supplier.code}</TableCell><TableCell className="font-mono text-xs">{supplier.accountNumber||"—"}</TableCell><TableCell className="font-semibold">{supplier.name}</TableCell><TableCell>{supplier.mofNumber||"—"}</TableCell><TableCell>{supplier.phone||"—"}</TableCell><TableCell>{supplier.email||"—"}</TableCell><TableCell className="max-w-60 truncate">{supplier.address||"—"}</TableCell><TableCell><Button size="icon-sm" variant="ghost" aria-label={`Edit ${supplier.name}`} onClick={()=>edit(supplier)}><Edit3/></Button></TableCell></TableRow>)}</TableBody></Table>:<div className="grid min-h-80 place-items-center p-8 text-center"><div><span className="mx-auto mb-4 grid size-14 place-items-center rounded-2xl bg-slate-100 text-slate-500"><Truck/></span><h3 className="font-bold">No suppliers found</h3><p className="mb-5 mt-1 text-sm text-slate-500">Add the businesses you purchase parts from.</p><Button onClick={add} className="bg-[#ef4e6f] hover:bg-[#c93454]"><Plus/>Add supplier</Button></div></div>}</section>
  <Dialog open={open} onOpenChange={value=>{if(!saving)setOpen(value)}}><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>{form.id?"Edit supplier":"Add supplier"}</DialogTitle><DialogDescription>Save the details used to identify this supplier.</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><Field label="Supplier code"><Input required={!form.id} inputMode="numeric" pattern={form.id?undefined:"[0-9]{6}"} readOnly={!!form.accountNumber} maxLength={form.id?40:6} value={form.code} onChange={event=>setForm({...form,code:event.target.value.toUpperCase()})} placeholder="012345"/><p className="text-xs text-slate-500">Enter exactly 6 digits, including leading zeros.</p></Field><Field label="Account number"><Input readOnly value={form.accountNumber} placeholder="Generated from company prefix + supplier code"/></Field><Field label="Supplier name" required><Input required maxLength={2000} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></Field><Field label="MOF number"><Input maxLength={2000} value={form.mofNumber} onChange={event=>setForm({...form,mofNumber:event.target.value})}/></Field><div className="grid grid-cols-2 gap-4"><Field label="Phone"><Input type="tel" maxLength={2000} value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></Field><Field label="Email"><Input type="email" maxLength={2000} value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></Field></div><Field label="Address"><Textarea maxLength={2000} rows={2} value={form.address} onChange={event=>setForm({...form,address:event.target.value})}/></Field></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving} className="bg-[#ef4e6f] hover:bg-[#c93454]">{saving?"Saving…":"Save supplier"}</Button></DialogFooter></form></DialogContent></Dialog>
 </>
}
function Field({label,required,children}:{label:string;required?:boolean;children:React.ReactNode}){return <div className="grid gap-1.5"><Label>{label}{required&&<span className="text-red-500"> *</span>}</Label>{children}</div>}
