"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Row={accountNumber:string;name:string;accountType:string;openingBalance:number;periodDebit:number;periodCredit:number};
const today=()=>{const date=new Date(),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,10)};
const firstDay=()=>today().slice(0,8)+"01";
const amount=(value:number)=>new Intl.NumberFormat("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Math.abs(value));
const side=(value:number,wanted:"debit"|"credit")=>wanted==="debit"?Math.max(value,0):Math.max(-value,0);
const csvCell=(value:unknown)=>`"${String(value).replaceAll('"','""')}"`;

export default function TrialBalance(){
 const[from,setFrom]=useState(firstDay),[to,setTo]=useState(today),[rows,setRows]=useState<Row[]>([]),[currency,setCurrency]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[run,setRun]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");fetch(`/api/trial-balance?${new URLSearchParams({from,to})}`,{signal:controller.signal}).then(async response=>{const data=await response.json() as{accounts?:Row[];currency?:string;error?:string};if(!response.ok)throw new Error(data.error);setRows(data.accounts??[]);setCurrency(data.currency??"")}).catch(value=>{if(value.name!=="AbortError")setError(value instanceof Error?value.message:"Could not prepare the trial balance.")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[run]);
 const data=useMemo(()=>rows.map(row=>({...row,closingBalance:Number(row.openingBalance)+Number(row.periodDebit)-Number(row.periodCredit)})),[rows]);
 const hasUnassigned=data.some(row=>row.accountType==="unassigned");
 const totals=useMemo(()=>data.reduce((sum,row)=>({openingDebit:sum.openingDebit+side(row.openingBalance,"debit"),openingCredit:sum.openingCredit+side(row.openingBalance,"credit"),periodDebit:sum.periodDebit+Number(row.periodDebit),periodCredit:sum.periodCredit+Number(row.periodCredit),closingDebit:sum.closingDebit+side(row.closingBalance,"debit"),closingCredit:sum.closingCredit+side(row.closingBalance,"credit")}),{openingDebit:0,openingCredit:0,periodDebit:0,periodCredit:0,closingDebit:0,closingCredit:0}),[data]);
 const balanced=Math.abs(totals.closingDebit-totals.closingCredit)<0.005;
 function exportCsv(){const header=["Account","Name","Type","Opening debit","Opening credit","Period debit","Period credit","Closing debit","Closing credit"],body=data.map(row=>[row.accountNumber,row.name,row.accountType,side(row.openingBalance,"debit"),side(row.openingBalance,"credit"),row.periodDebit,row.periodCredit,side(row.closingBalance,"debit"),side(row.closingBalance,"credit")]),csv=[header,...body].map(line=>line.map(csvCell).join(",")).join("\r\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`trial-balance-${from}-to-${to}.csv`;link.click();URL.revokeObjectURL(url)}
 return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">
  <div className="flex flex-wrap items-end justify-between gap-4 border-b p-5"><div><h2 className="text-lg font-bold">Trial balance</h2><p className="text-sm text-slate-500">Opening, period and closing balances in {currency||"local currency"}.</p></div><div className="flex flex-wrap items-end gap-3"><Field label="From"><Input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></Field><Field label="To"><Input type="date" value={to} onChange={event=>setTo(event.target.value)}/></Field><Button onClick={()=>setRun(value=>value+1)} disabled={loading||!from||!to||from>to}><RefreshCw className={loading?"animate-spin":""}/>Generate</Button><Button variant="outline" disabled={!data.length} onClick={exportCsv}><Download/>Export CSV</Button></div></div>
  {hasUnassigned&&!loading&&!error&&<div className="border-b border-amber-200 bg-amber-50 px-5 py-3 text-sm text-amber-800"><strong>Account mapping needs attention.</strong> Some posted transactions have no account or use an account that is missing from the Chart of Accounts. They are included below so the trial balance remains complete.</div>}
  {error?<div className="p-8 text-center text-red-700">{error}</div>:loading?<div className="p-8 text-center text-slate-500">Preparing trial balance…</div>:data.length?<div className="overflow-x-auto"><Table className="min-w-[1120px]"><TableHeader><TableRow><TableHead rowSpan={2}>Account</TableHead><TableHead rowSpan={2}>Name</TableHead><TableHead colSpan={2} className="border-l text-center">Opening balance</TableHead><TableHead colSpan={2} className="border-l text-center">Period movement</TableHead><TableHead colSpan={2} className="border-l text-center">Closing balance</TableHead></TableRow><TableRow><TableHead className="border-l text-right">Debit</TableHead><TableHead className="text-right">Credit</TableHead><TableHead className="border-l text-right">Debit</TableHead><TableHead className="text-right">Credit</TableHead><TableHead className="border-l text-right">Debit</TableHead><TableHead className="text-right">Credit</TableHead></TableRow></TableHeader><TableBody>{data.map(row=><TableRow key={row.accountNumber||"__unassigned__"} className={row.accountType==="unassigned"?"bg-amber-50/60":""}><TableCell className="font-mono font-semibold">{row.accountNumber||"—"}</TableCell><TableCell>{row.name}<small className={`block capitalize ${row.accountType==="unassigned"?"font-medium text-amber-700":"text-slate-500"}`}>{row.accountType}</small></TableCell><Money value={side(row.openingBalance,"debit")} border/><Money value={side(row.openingBalance,"credit")}/><Money value={row.periodDebit} border/><Money value={row.periodCredit}/><Money value={side(row.closingBalance,"debit")} border strong/><Money value={side(row.closingBalance,"credit")} strong/></TableRow>)}</TableBody><TableFooter><TableRow><TableCell colSpan={2}>Totals · {currency}</TableCell><Money value={totals.openingDebit} border/><Money value={totals.openingCredit}/><Money value={totals.periodDebit} border/><Money value={totals.periodCredit}/><Money value={totals.closingDebit} border strong/><Money value={totals.closingCredit} strong/></TableRow></TableFooter></Table></div>:<div className="p-10 text-center text-slate-500">No accounting activity was found for this period.</div>}
  {!loading&&!error&&<div className={`flex flex-wrap items-center justify-between gap-3 border-t px-5 py-4 text-sm ${balanced?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}><strong>{balanced?"Trial balance is balanced":"Trial balance is out of balance"}</strong><span>Closing difference: {amount(totals.closingDebit-totals.closingCredit)} {currency}</span></div>}
 </section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="grid gap-1"><Label>{label}</Label>{children}</div>}
function Money({value,border,strong}:{value:number;border?:boolean;strong?:boolean}){return <TableCell className={`text-right tabular-nums ${border?"border-l":""} ${strong?"font-semibold":""}`}>{Math.abs(value)>=0.005?amount(value):"—"}</TableCell>}
