"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {toast} from 'sonner';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogTitle,DialogHeader,DialogFooter,DialogDescription} from './ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from './ui/table';
import ItemPicker,{UnitSelect} from './item-picker';
import type {MasterItem} from './item-master-dialog';
export type Warehouse={id:number;code:string;name:string;address:string;active:number;quantity:number};
export async function warehouseApi<T>(url:string,method='GET',body?:unknown):Promise<T>{const r=await fetch(url,{method,headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),d=await r.json() as T&{error?:string};if(!r.ok)throw new Error(d.error||'Could not save warehouse.');return d}
export function WarehouseSelect({value,onChange,all=false,disabled=false}:{value?:string;onChange:(code:string)=>void;all?:boolean;disabled?:boolean}){
 const [rows,setRows]=useState<Warehouse[]>([]),[error,setError]=useState('');
 useEffect(()=>{let current=true;warehouseApi<{warehouses:Warehouse[]}>('/api/warehouses').then(d=>{if(current)setRows(d.warehouses)}).catch(e=>{if(current)setError(e.message)});return()=>{current=false}},[]);
 return <div className="min-w-0"><select aria-label="Warehouse" className="h-10 w-full rounded-md border bg-white px-3 text-sm disabled:bg-slate-50" disabled={disabled} value={value??'MAIN'} onChange={e=>onChange(e.target.value)}>{all?<option value="">All warehouses</option>:!value?<option value="">Select warehouse</option>:null}{value&&!rows.some(w=>w.code===value)&&<option value={value}>{value}</option>}{rows.filter(w=>all||w.active||w.code===value).map(w=><option key={w.code} value={w.code}>{w.code} · {w.name}{w.active?'':' (inactive)'}</option>)}</select>{error&&<p role="alert" className="text-xs text-red-700">{error}</p>}</div>
}
export default function WarehouseMaster(){
 const [rows,setRows]=useState<Warehouse[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[form,setForm]=useState({id:0,code:'',name:'',address:'',active:1});
 async function load(){try{setRows((await warehouseApi<{warehouses:Warehouse[]}>('/api/warehouses')).warehouses);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{await warehouseApi('/api/warehouses',form.id?'PUT':'POST',form);setOpen(false);await load();toast.success('Warehouse saved')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <div className="space-y-5"><section className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-5"><div><h2 className="text-lg font-bold">Warehouses</h2><p className="text-sm text-slate-500">Locations used by purchases, sales and stock movements.</p></div><Button className="bg-[#ef4e6f] hover:bg-[#c93454]" onClick={()=>{setForm({id:0,code:'',name:'',address:'',active:1});setOpen(true)}}>New warehouse</Button></section><section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-4"><Input aria-label="Search warehouses" placeholder="Search warehouse…" value={query} onChange={e=>setQuery(e.target.value)} className="max-w-sm"/></div>{loading?<p className="p-6">Loading warehouses…</p>:error?<div role="alert" className="p-6">{error}<Button variant="outline" onClick={()=>void load()}>Retry</Button></div>:<Table><TableHeader><TableRow><TableHead>Code</TableHead><TableHead>Warehouse</TableHead><TableHead>Address</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.filter(w=>(w.code+' '+w.name).toLowerCase().includes(query.toLowerCase())).map(w=><TableRow key={w.id}><TableCell className="font-mono">{w.code}</TableCell><TableCell>{w.name}</TableCell><TableCell>{w.address||'—'}</TableCell><TableCell>{w.active?'Active':'Inactive'}</TableCell><TableCell><Button variant="outline" onClick={()=>{setForm(w);setOpen(true)}}>Edit</Button></TableCell></TableRow>)}</TableBody></Table>}</section><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent><form onSubmit={save}><DialogHeader><DialogTitle>{form.id?'Edit warehouse':'New warehouse'}</DialogTitle><DialogDescription>Codes remain fixed so historical transactions keep their warehouse.</DialogDescription></DialogHeader><div className="space-y-4 py-5"><label className="grid gap-1 text-sm">Code<Input required maxLength={20} pattern="[A-Za-z0-9_-]+" readOnly={!!form.id} value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label><label className="grid gap-1 text-sm">Name<Input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="grid gap-1 text-sm">Address<Input maxLength={1000} value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={!!form.active} disabled={form.code==='MAIN'} onChange={e=>setForm({...form,active:e.target.checked?1:0})}/>Active</label><p className="text-xs text-slate-500">Move all stock out before deactivating a warehouse.</p></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':'Save warehouse'}</Button></DialogFooter></form></DialogContent></Dialog></div>
}
export function WarehouseTransfer({items,onSaved}:{items:MasterItem[];onSaved:()=>void}){
 const [from,setFrom]=useState('MAIN'),[to,setTo]=useState(''),[itemId,setItemId]=useState(0),[unit,setUnit]=useState('unit'),[quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[key,setKey]=useState(()=>crypto.randomUUID()),[balances,setBalances]=useState<Warehouse[]>([]),[refresh,setRefresh]=useState(0);
 const item=items.find(i=>i.id===itemId);
 useEffect(()=>{let current=true;setBalances([]);if(itemId)warehouseApi<{warehouses:Warehouse[]}>('/api/warehouses?itemId='+itemId).then(d=>{if(current)setBalances(d.warehouses)}).catch(e=>toast.error(e.message));return()=>{current=false}},[itemId,refresh]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{await warehouseApi('/api/warehouse-transfers','POST',{fromWarehouse:from,toWarehouse:to,itemId,unit,quantity:Number(quantity),reason,requestKey:key});toast.success('Stock transferred');setQuantity('');setReason('');setKey(crypto.randomUUID());setRefresh(n=>n+1);onSaved()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={save} className="max-w-4xl space-y-5 rounded-2xl border bg-white p-5"><div><h2 className="text-lg font-bold">Warehouse transfer</h2><p className="text-sm text-slate-500">Move stock between locations. Total company stock stays unchanged.</p></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">From warehouse<WarehouseSelect value={from} onChange={setFrom}/></label><label className="grid gap-1 text-sm">To warehouse<WarehouseSelect value={to} onChange={setTo}/></label></div><label className="grid gap-1 text-sm">Item<ItemPicker items={items} value={itemId} onSelect={(i,u)=>{setItemId(i?.id??0);setUnit(u)}}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Quantity<Input required type="number" min="0.000001" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label className="grid gap-1 text-sm">Unit<UnitSelect item={item} value={unit} onChange={setUnit}/></label></div>{item&&<p className="text-sm">Available at {from}: {balances.find(w=>w.code===from)?.quantity??'…'} {item.baseUnit}</p>}<label className="grid gap-1 text-sm">Reason<Input required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={busy||!itemId||!to||from===to} className="bg-[#ef4e6f] hover:bg-[#c93454]">{busy?'Transferring…':'Transfer stock'}</Button><p className="text-xs text-slate-500">Both movements appear in Stock transactions under the same transfer reference.</p></form>
}
