export type Cell = string | number | null;
export type ReportRow = Record<string, Cell>;
export type Filters = { from:string; to:string; search:string; selections:Record<string,string[]>; min:string; max:string; mode:string; group:string; sort:string; descending:boolean };
export type Column = {key:string;label:string;numeric?:boolean;sum?:boolean};
export type Definition = {title:string;menu:string;columns:Column[];filters:string[];groups:string[];asOf?:boolean;statement?:boolean};
const cols=(text:string)=>text.split('|').map(s=>{const [key,label,kind]=s.split(':');return {key,label,numeric:!!kind,sum:kind==='sum'}});
const itemFilters=['item','group','subgroup','brand'];
const itemColumns='sku:Item code|item:Item|unit:Base unit';
const moneyColumns='currency:Currency|gross:Gross sales:sum|discount:Discounts:sum|sales:Sales before VAT:sum|returns:Returns before VAT:sum|net:Net before VAT:sum|vat:VAT:sum|total:Total:sum';
export const definitions:Record<string,Definition>={
 'stock-card':{title:'Stock Item Card',menu:'Stock flow',columns:cols('date:Date|type:Movement|reference:Document|'+itemColumns+'|party:Customer / supplier|warehouse:Warehouse|user:User|opening:Opening:num|qtyIn:Quantity in:sum|qtyOut:Quantity out:sum|balance:Running balance:num'),filters:[...itemFilters,'warehouse','type'],groups:['item','warehouse']},
 'sold-items':{title:'Sold Items',menu:'Sales',columns:cols('date:Date|reference:Invoice / return|original:Original invoice|'+itemColumns+'|customer:Customer|salesman:Salesman|warehouse:Warehouse|soldQty:Sold quantity:sum|returnQty:Returned quantity:sum|netQty:Net quantity:sum|'+moneyColumns),filters:[...itemFilters,'customer','customerGroup','salesman','warehouse','currency'],groups:['item','customer','salesman','warehouse']},
 'purchased-items':{title:'Purchased Items',menu:'Stock flow',columns:cols('date:Date|reference:Purchase|externalReference:Supplier reference|'+itemColumns+'|supplier:Supplier|warehouse:Warehouse|currency:Currency|quantity:Base quantity:sum|documentUnit:Purchase unit|price:Purchase unit price:num|discount:Discount:sum|net:Net value:sum|expenses:Allocated expenses:sum|landed:Landed value:sum'),filters:[...itemFilters,'supplier','warehouse','currency'],groups:['item','supplier','warehouse']},
 'stock-balance':{title:'Stock Balance by Warehouse',menu:'Stock flow',asOf:true,columns:cols(itemColumns+'|active:Status|companyQty:Company quantity:sum'),filters:[...itemFilters,'warehouse','active','stockStatus'],groups:['group','brand']},
 'customer-statement':{title:'Customer Statement',menu:'Accounting',statement:true,columns:cols('date:Date|reference:Document|type:Type|customer:Customer|account:Account|currency:Currency|opening:Opening balance:num|debit:Debit:sum|credit:Credit:sum|balance:Running balance:num'),filters:['customer','currency','type'],groups:['customer','type']},
 'supplier-statement':{title:'Supplier Statement',menu:'Accounting',statement:true,columns:cols('date:Date|reference:Document|type:Type|supplier:Supplier|account:Account|currency:Currency|opening:Opening balance:num|debit:Debit:sum|credit:Credit:sum|balance:Running payable:num'),filters:['supplier','currency','type'],groups:['supplier','type']},
 'returns-report':{title:'Sales Returns',menu:'Sales',columns:cols('date:Date|reference:Return / credit|original:Original invoice|'+itemColumns+'|customer:Customer|salesman:Salesman|warehouse:Warehouse|currency:Currency|returnQty:Returned quantity:sum|returns:Value before VAT:sum|vat:VAT:sum|total:Total:sum'),filters:[...itemFilters,'customer','salesman','warehouse','currency'],groups:['item','customer','salesman']},
 'transfers-report':{title:'Warehouse Transfers',menu:'Stock flow',columns:cols('date:Date|reference:Transfer|'+itemColumns+'|quantity:Quantity:sum|source:Source warehouse|destination:Destination warehouse|user:User|reason:Reason'),filters:[...itemFilters,'source','destination','user'],groups:['item','source','destination','user']},
 'adjustments-report':{title:'Stock Adjustments',menu:'Stock flow',columns:cols('date:Date|reference:Adjustment|'+itemColumns+'|warehouse:Warehouse|qtyIn:Increase:sum|qtyOut:Decrease:sum|direction:Direction|reason:Reason|user:User'),filters:[...itemFilters,'warehouse','direction','reason','user'],groups:['item','warehouse','direction','reason']},
 'daily-sales':{title:'Daily Sales and Collections',menu:'Sales',columns:cols('date:Date|reference:Document|customer:Customer|salesman:Salesman|paymentMethod:Payment method|account:Cash / bank account|currency:Currency|sales:Sales before VAT:sum|returns:Returns before VAT:sum|net:Net sales before VAT:sum|collections:Collections:sum'),filters:['customer','salesman','currency','paymentMethod','account'],groups:['date','customer','salesman','paymentMethod']},
 'outstanding':{title:'Outstanding Invoices',menu:'Accounting',asOf:true,columns:cols('date:Invoice date|due:Due date|reference:Invoice|customer:Customer|salesman:Salesman|currency:Currency|originalAmount:Original amount:sum|applied:Receipts / credits applied:sum|outstanding:Outstanding:sum|days:Days overdue:num|bucket:Aging bucket'),filters:['customer','salesman','currency','overdue','bucket'],groups:['customer','salesman','bucket']},
 'price-cost':{title:'Item Price and Cost List',menu:'Stock flow',columns:cols(itemColumns+'|active:Status|supplier:Supplier|currency:Currency|priceList:Price list|selling:Selling price:num|purchaseCost:Purchase cost / base unit:num|landedCost:Landed cost / base unit:num|costMethod:Cost basis'),filters:[...itemFilters,'supplier','priceList','currency','active'],groups:['group','brand','supplier']},
};
export const labels:Record<string,string>={item:'Items',group:'Groups',subgroup:'Subgroups',brand:'Brands',warehouse:'Warehouses',customer:'Customers',customerGroup:'Customer groups',salesman:'Salesmen',currency:'Currencies',supplier:'Suppliers',type:'Document / movement types',active:'Item status',stockStatus:'Stock quantity',source:'Source warehouses',destination:'Destination warehouses',user:'Users',direction:'Adjustment direction',reason:'Reasons',paymentMethod:'Payment methods',account:'Cash / bank accounts',overdue:'Overdue status',bucket:'Aging buckets',priceList:'Price lists',date:'Day'};
export const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
export function validDate(s:string){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s+'T00:00:00Z'))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s}
export function validateFilters(f:Filters){if(!validDate(f.from)||!validDate(f.to)||f.from>f.to)throw Error('Choose a valid date range; From must not be after To.');for(const v of [f.min,f.max])if(v!==''&&!Number.isFinite(Number(v)))throw Error('Enter valid numeric limits.');if(f.min!==''&&f.max!==''&&Number(f.min)>Number(f.max))throw Error('Minimum must not exceed maximum.');}
export function matches(row:ReportRow,f:Filters,ignore:string[]=[]){return Object.entries(f.selections).every(([key,values])=>ignore.includes(key)||!values.length||values.includes(String(row[key]??'')))&&(!f.search||[row.reference,row.original,row.externalReference].some(v=>String(v??'').toLowerCase().includes(f.search.toLowerCase())));}
export function aggregate(rows:ReportRow[],columns:Column[],keys:string[]):ReportRow[]{const groups=new Map<string,ReportRow>();for(const row of rows){const id=JSON.stringify(keys.map(k=>row[k]??''));let result=groups.get(id);if(!result){result=Object.fromEntries(keys.map(k=>[k,row[k]??'']));result._count=0;groups.set(id,result)}result._count=Number(result._count)+1;for(const col of columns.filter(c=>c.sum)){if(row[col.key]===null){result[col.key]=null;continue}if(result[col.key]!==null)result[col.key]=Number(result[col.key]??0)+Number(row[col.key]??0)}}return [...groups.values()].map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,typeof v==='number'?Math.round(v*1e9)/1e9:v])));}
export function finishReport(id:string,rows:ReportRow[],f:Filters,columns=definitions[id].columns){
 validateFilters(f);const d=definitions[id];
 const options=Object.fromEntries(d.filters.map(k=>[k,[...new Set(rows.map(r=>String(r[k]??'')).filter(Boolean))].sort()]));
 let filtered=rows.filter(r=>matches(r,f,id==='daily-sales'&&r._document!=='receipt'?['paymentMethod','account']:[])&&(!r.date||((d.asOf||id==='price-cost'||String(r.date)>=f.from)&&String(r.date)<=f.to))&&(f.min===''||Number(r.outstanding)>=Number(f.min))&&(f.max===''||Number(r.outstanding)<=Number(f.max)));
 const partition=['currency','unit'].filter(k=>columns.some(c=>c.key===k));
 const totals=aggregate(filtered,columns,partition);
 const group=d.groups.includes(f.group)?f.group:'';
 if(group&&!columns.some(c=>c.key===group))columns=[{key:group,label:labels[group]||group},...columns];
 const subtotals=group?aggregate(filtered,columns,[group,...partition]):[];
 if(f.mode==='summary'&&!d.statement&&!['stock-card','stock-balance','price-cost'].includes(id)){const keys=id==='purchased-items'?[...new Set([group||'item','item','supplier',...partition])]:[group||d.groups[0],...partition];if(keys.includes('item'))keys.push('sku');filtered=aggregate(filtered,columns,keys)}
 if(d.statement&&f.mode==='summary'){
  const keys=[d.filters[0],'account','currency'];const summaries=aggregate(filtered,columns,keys);
  for(const row of summaries){const entries=filtered.filter(r=>keys.every(k=>r[k]===row[k]));row.opening=entries[0]?.opening??0;row.balance=entries.at(-1)?.balance??0;row.type='Account summary';}filtered=summaries;
 }
 const sort=columns.some(c=>c.key===f.sort)?f.sort:'date';
 filtered.sort((a,b)=>{const x=a[sort]??'',y=b[sort]??'';return ((typeof x==='number'&&typeof y==='number')?x-y:String(x).localeCompare(String(y)))*(f.descending?-1:1)||Number(a._order??0)-Number(b._order??0)||String(a._key??'').localeCompare(String(b._key??''))});
 if(f.mode==='summary'&&!['stock-card','stock-balance','price-cost'].includes(id))columns=columns.filter(c=>filtered.some(r=>Object.hasOwn(r,c.key)));
 return {columns,rows:filtered,totals,subtotals,options,filters:f};
}
