"use client";

import {useEffect,useState} from "react";
import "./print.css";
import {savedLineTotal,localCountervalues} from "@/lib/invoice-totals";

type Invoice={warehouseCode:string;salesOrderId?:number;salesOrderNumber?:string;lineDiscountTotal:number;calculationVersion:number;invoiceNumber:string;draftNumber?:string;documentState:"draft"|"posted"|"reversed"|"cancelled";invoiceDate:string;dueDate:string;paymentTerms:string;salesmanName?:string;currency:string;currencyRate:number;localCurrency:string;purchaseOrderNumber:string;notes:string;discountRate:number;discountAmount:number;subtotal:number;tax:number;total:number;appliedAmount:number;outstanding:number;status:string;historicalFallbacks:string;reconciliationRequired:number;reconciliationReason?:string;createdAt:string};
type Customer={code:string;name:string;tradingName:string;mofNumber:string;phone:string;mobile:string;email:string;address:string;city:string;country:string};
type Line={unit?:string;lineDiscountRate:number;lineDiscountAmount:number;lineType:string;description:string;quantity:number;unitPrice:number;lineTotal:number;discountAmount:number;taxRate:number;taxAmount:number};
type Settings={companyName:string;companyAddress:string;sellerTaxRegistration:string;logoDataUrl:string;defaultCurrency:string;localCurrencyRate:number;localCurrency:string};
type Data={invoice:Invoice;customer:Customer|null;settings:Settings;lines:Line[]};
const money=(value:number,currency:string)=>new Intl.NumberFormat("en-US",{
 style:"currency",currency,
 maximumFractionDigits:2,
 minimumFractionDigits:2,
}).format(value);
const rate=(value:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:6}).format(value);
export default function InvoicePrint(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[retry,setRetry]=useState(0);
 useEffect(()=>{
  const controller=new AbortController();setError("");setData(null);
  const id=new URLSearchParams(window.location.search).get("id");
  if(!id||!/^\d+$/.test(id)){setError("Choose an invoice from the Invoices page.");return;}
  fetch("/api/invoices?id="+encodeURIComponent(id),{signal:controller.signal}).then(async r=>{
   const value=await r.json() as Data&{error?:string};
   if(!r.ok)throw new Error(value.error||"Could not load invoice.");
   setData(value);document.title=value.invoice.invoiceNumber+" — "+value.settings.companyName;
  }).catch(e=>{if(e.name!=="AbortError")setError(e.message)});
  return()=>controller.abort();
 },[retry]);
 const local=data?localCountervalues(data.invoice,data.invoice.currencyRate||data.settings.localCurrencyRate):null;
 return <main className="invoice-print-page">
  <nav className="print-toolbar" aria-label="Invoice print controls"><a href="/">Back to workshop</a><button disabled={!data} onClick={()=>window.print()}>Print / Save as PDF</button></nav>
  {error?<section className="print-message" role="alert"><h1>Invoice unavailable</h1><p>{error}</p><button onClick={()=>setRetry(n=>n+1)}>Try again</button></section>:!data?<p className="print-message" role="status">Loading invoice…</p>:<article className="invoice-paper">
   <header className="invoice-heading"><div>{data.settings.logoDataUrl&&<img src={data.settings.logoDataUrl} alt=""/>}<h1>{data.settings.companyName}</h1>{data.settings.companyAddress&&<p className="preserve-lines">{data.settings.companyAddress}</p>}{data.settings.sellerTaxRegistration&&<p>Tax registration / MOF: {data.settings.sellerTaxRegistration}</p>}</div><div className="invoice-identity"><h2>{data.invoice.documentState==="cancelled"?"CANCELLED DRAFT":data.invoice.documentState==="draft"?"DRAFT INVOICE":data.invoice.documentState==="reversed"?"REVERSED INVOICE":"INVOICE"}</h2><p><strong>{data.invoice.documentState==="draft"?(data.invoice.draftNumber||data.invoice.invoiceNumber):data.invoice.invoiceNumber}</strong></p><p>Invoice date: {new Date(data.invoice.invoiceDate+"T00:00:00").toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"})}</p><p>Due date: {new Date(data.invoice.dueDate+"T00:00:00").toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"})}</p>{data.invoice.salesOrderId&&<p>Sales order: <a href={"/?salesOrder="+data.invoice.salesOrderId}>{data.invoice.salesOrderNumber}</a></p>}<p>Warehouse: {data.invoice.warehouseCode}</p><p>Terms: {data.invoice.paymentTerms.replaceAll("_"," ")}</p><p className="payment-label">{data.invoice.documentState==="cancelled"?"Cancelled · no ledger impact":data.invoice.documentState==="draft"?"Draft · no ledger impact":data.invoice.documentState==="reversed"?"Reversed":data.invoice.status==="paid"?"Paid":data.invoice.status==="partial"?"Partially paid":"Unpaid"}</p></div></header>
   <section className="invoice-parties"><div><h3>Bill to</h3><strong>{data.customer?.name||"Customer not available"}</strong>{data.customer?.tradingName&&<p>{data.customer.tradingName}</p>}{data.customer?.code&&<p>Customer code: {data.customer.code}</p>}{data.customer?.mofNumber&&<p>MOF number: {data.customer.mofNumber}</p>}{data.invoice.purchaseOrderNumber&&<p>PO number: {data.invoice.purchaseOrderNumber}</p>}{data.invoice.salesmanName&&<p>Salesman: {data.invoice.salesmanName}</p>}{data.customer?.phone&&<p>{data.customer.phone}</p>}{data.customer?.mobile&&<p>{data.customer.mobile}</p>}{data.customer?.email&&<p>{data.customer.email}</p>}{(data.customer?.address||data.customer?.city||data.customer?.country)&&<p className="preserve-lines">{[data.customer.address,data.customer.city,data.customer.country].filter(Boolean).join(", ")}</p>}</div></section>
   <table className="invoice-lines"><caption>Non-item sales and items · amounts after both discounts · {data.invoice.currency}</caption><thead><tr><th scope="col">Description</th><th scope="col" className="number">Qty</th><th scope="col" className="number">Unit price</th><th scope="col" className="number">Line discount</th><th scope="col" className="number">Invoice discount</th><th scope="col" className="number">VAT %</th><th scope="col" className="number">VAT</th><th scope="col" className="number">Total incl. VAT</th></tr></thead><tbody>{data.lines.map((l,n)=><tr key={n}><td><span className="line-type">{l.lineType==="part"?"Item":"Non-item sales"}</span><div className="preserve-lines">{l.description}</div></td><td className="number">{l.quantity} {l.unit}</td><td className="number">{money(l.unitPrice,data.invoice.currency)}</td><td className="number"><span className="discount-rate">{l.lineDiscountRate??0}%</span>{money(l.lineDiscountAmount??0,data.invoice.currency)}</td><td className="number">{money(l.discountAmount??0,data.invoice.currency)}</td><td className="number">{l.taxRate}%</td><td className="number">{money(l.taxAmount,data.invoice.currency)}</td><td className="number">{money(savedLineTotal(l),data.invoice.currency)}</td></tr>)}</tbody></table>
   <section className={`invoice-summary ${data.settings.localCurrency===data.invoice.currency?"invoice-summary-single":""}`}>
    {data.invoice.localCurrency!==data.invoice.currency&&<div className="summary-card summary-card-local"><div className="summary-heading"><span>Local countervalue</span><strong>{data.invoice.localCurrency}</strong></div><dl><div><dt>Net before VAT</dt><dd>{money(local!.subtotal,data.invoice.localCurrency)}</dd></div><div><dt>VAT</dt><dd>{money(local!.tax,data.invoice.localCurrency)}</dd></div><div className="summary-total"><dt>Total incl. VAT</dt><dd>{money(local!.total,data.invoice.localCurrency)}</dd></div></dl><p className="exchange-rate">Exchange rate: 1 {data.invoice.currency} = {rate(data.invoice.currencyRate||data.settings.localCurrencyRate)} {data.invoice.localCurrency}</p></div>}
    <div className="summary-card summary-card-primary"><div className="summary-heading"><span>Invoice currency</span><strong>{data.invoice.currency}</strong></div><dl><div><dt>Gross subtotal</dt><dd>{money(data.invoice.subtotal+data.invoice.discountAmount+(data.invoice.lineDiscountTotal??0),data.invoice.currency)}</dd></div><div><dt>Line discounts</dt><dd>−{money(data.invoice.lineDiscountTotal??0,data.invoice.currency)}</dd></div><div><dt>Additional invoice discount ({data.invoice.discountRate}%)</dt><dd>−{money(data.invoice.discountAmount,data.invoice.currency)}</dd></div><div><dt>Net before VAT</dt><dd>{money(data.invoice.subtotal,data.invoice.currency)}</dd></div><div><dt>VAT</dt><dd>{money(data.invoice.tax,data.invoice.currency)}</dd></div><div className="summary-total"><dt>Total incl. VAT</dt><dd>{money(data.invoice.total,data.invoice.currency)}</dd></div><div><dt>Amount received</dt><dd>{money(data.invoice.appliedAmount,data.invoice.currency)}</dd></div><div className="amount-due"><dt>Outstanding amount</dt><dd>{money(data.invoice.outstanding,data.invoice.currency)}</dd></div></dl></div>
   </section>
   {!!data.invoice.reconciliationRequired&&<section className="invoice-notes"><h3>Payment reconciliation required</h3><p>{data.invoice.reconciliationReason}</p></section>}{data.invoice.historicalFallbacks&&<section className="invoice-notes"><h3>Historical value note</h3><p>{data.invoice.historicalFallbacks}</p></section>}{data.invoice.notes&&<section className="invoice-notes"><h3>Notes</h3><p className="preserve-lines">{data.invoice.notes}</p></section>}
  </article>}
 </main>;
}
